In [1]:
# imports
import pandas as pd

In [3]:
# Ruta relativa del xslx que contiene los datos
original_data_path = 'Data\\Original\\PERSONAS_DEMOGRAFICO_Cuadros_CNPV_2018.xlsx'

# Nombre del csv objetivo
csv_total_filename = 'caldas_viterbo_total_15PM.csv'
csv_filename = 'caldas_viterbo_15PM.csv'

# Ruta relativa del csv objetivo
csv_total_path = 'Data\\Datasets\\' + csv_total_filename
csv_path = 'Data\\Datasets\\' + csv_filename

In [4]:
# Lee archivo xlsx
df_15pm = pd.read_excel(original_data_path, sheet_name='15PM', skiprows=9)
df_15pm.head()

,"Departamento, municipio, areas (Total, Cabecera y Centros poblados y Rural disperso) y sexo",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Total personas menores de 5 años,Dónde o con quién permanece el menor,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,NaN,NaN,NaN,NaN,"Asiste a un hogar comunitario, jardín, centro ...",Con su padre o madre en la vivienda,Con su padre o madre en el trabajo,En la vivienda donde vive el niño al cuidado d...,En la vivienda donde vive el niño al cuidado d...,Al cuidado de un pariente o de otra persona en...,"En la vivienda, solo",Sin Información
1,Total Nacional,NaN,Total,Hombre,0,286111.0,15769,235039,4459,17975,1854,5835,599,4581
2,NaN,NaN,NaN,NaN,1,307827.0,63368,196516,4304,26363,2929,9417,322,4608
3,NaN,NaN,NaN,NaN,2,317844.0,143065,139878,3254,18192,2226,6302,263,4664
4,NaN,NaN,NaN,NaN,3,320040.0,190226,105623,2559,11350,1523,3562,188,5009

In [5]:
first_row = list(df_15pm.iloc[0])[:]
for (i, value) in enumerate(first_row):
    print(i, value)

0 nan
1 nan
2 nan
3 nan
4 nan
5 nan
6 Asiste a un hogar comunitario, jardín, centro de desarrollo infantil o colegio
7 Con su padre o madre en la vivienda
8 Con su padre o madre en el trabajo
9 En la vivienda donde vive el niño al cuidado de un pariente o una persona de 18 años o más
10 En la vivienda donde vive el niño al cuidado de un pariente o una persona menor de 18 años
11 Al cuidado de un pariente o de otra persona en otro lugar
12 En la vivienda, solo
13 Sin Información

Se extraen los headers correctos, y se renombran columnas que no se logran capturar.

In [6]:
actual_headers = list(df_15pm.iloc[0][2:])
actual_headers[0] = 'Area'
actual_headers[1] = 'Sexo'
actual_headers[2] = 'Edad'
actual_headers[3] = 'Total personas menores de 5 anios'
actual_headers

['Area',
 'Sexo',
 'Edad',
 'Total personas menores de 5 anios',
 'Asiste a un hogar comunitario, jardín, centro de desarrollo infantil o colegio',
 'Con su padre o madre en la vivienda',
 'Con su padre o madre en el trabajo',
 'En la vivienda donde vive el niño al cuidado de un pariente o una persona de 18 años o más',
 'En la vivienda donde vive el niño al cuidado de un pariente o una persona menor de 18 años',
 'Al cuidado de un pariente o de otra persona en otro lugar',
 'En la vivienda, solo',
 'Sin Información']

Se filtrarán los datos que no corresponden al municipio de Viterbo Caldas, para ello se propagará el municipio, el cual se encuentra en la columna "Unnamed: 1" y se seleccionarán solo los registros que contengan el identificador de Viterbo dentro del dataframe, para este caso es "17877_Viterbo".

In [7]:
df_15pm['Unnamed: 1'] = df_15pm['Unnamed: 1'].ffill()
df_15pm = df_15pm.loc[df_15pm['Unnamed: 1'] == '17877_Viterbo']
df_15pm

,"Departamento, municipio, areas (Total, Cabecera y Centros poblados y Rural disperso) y sexo",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Total personas menores de 5 años,Dónde o con quién permanece el menor,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
22599,NaN,17877_Viterbo,Total Departamental,Hombre,0,62.0,0,59,0,3,0,0,0,0
22600,NaN,17877_Viterbo,NaN,NaN,1,59.0,7,47,1,2,0,1,0,1
22601,NaN,17877_Viterbo,NaN,NaN,2,72.0,35,33,1,1,0,1,0,1
22602,NaN,17877_Viterbo,NaN,NaN,3,65.0,47,16,0,2,0,0,0,0
22603,NaN,17877_Viterbo,NaN,NaN,4,70.0,48,20,0,1,0,0,0,1
22604,NaN,17877_Viterbo,NaN,NaN,Total,328.0,137,175,2,9,0,2,0,3
22605,NaN,17877_Viterbo,NaN,Mujer,0,56.0,0,52,1,2,0,1,0,0
22606,NaN,17877_Viterbo,NaN,NaN,1,59.0,8,47,0,3,0,0,0,1
22607,NaN,17877_Viterbo,NaN,NaN,2,60.0,27,29,0,4,0,0,0,0
22608,NaN,17877_Viterbo,NaN,NaN,3,55.0,31,21,1,1,0,1,0,0
22609,NaN,17877_Viterbo,NaN,NaN,4,58.0,44,13,0,1,0,0,0,0
22610,NaN,17877_Viterbo,NaN,NaN,Total,288.0,110,162,2,11,0,2,0,1
22611,NaN,17877_Viterbo,NaN,Total,0,118.0,0,111,1,5,0,1,0,0
22612,NaN,17877_Viterbo,NaN,NaN,1,118.0,15,94,1,5,0,1,0,2
22613,NaN,17877_Viterbo,NaN,NaN,2,132.0,62,62,1,5,0,1,0,1
22614,NaN,17877_Viterbo,NaN,NaN,3,120.0,78,37,1,3,0,1,0,0
22615,NaN,17877_Viterbo,NaN,NaN,4,128.0,92,33,0,2,0,0,0,1
22616,NaN,17877_Viterbo,NaN,NaN,Total,616.0,247,337,4,20,0,4,0,4
22617,NaN,17877_Viterbo,Cabecera,Hombre,0,52.0,0,49,0,3,0,0,0,0
22618,NaN,17877_Viterbo,NaN,NaN,1,47.0,6,36,1,2,0,1,0,1
22619,NaN,17877_Viterbo,NaN,NaN,2,65.0,34,28,0,1,0,1,0,1
22620,NaN,17877_Viterbo,NaN,NaN,3,59.0,46,12,0,1,0,0,0,0
22621,NaN,17877_Viterbo,NaN,NaN,4,61.0,48,12,0,0,0,0,0,1
22622,NaN,17877_Viterbo,NaN,NaN,Total,284.0,134,137,1,7,0,2,0,3
22623,NaN,17877_Viterbo,NaN,Mujer,0,42.0,0,39,0,2,0,1,0,0
22624,NaN,17877_Viterbo,NaN,NaN,1,52.0,8,40,0,3,0,0,0,1
22625,NaN,17877_Viterbo,NaN,NaN,2,51.0,25,23,0,3,0,0,0,0
22626,NaN,17877_Viterbo,NaN,NaN,3,45.0,28,15,0,1,0,1,0,0
22627,NaN,17877_Viterbo,NaN,NaN,4,45.0,42,2,0,1,0,0,0,0
22628,NaN,17877_Viterbo,NaN,NaN,Total,235.0,103,119,0,10,0,2,0,1
22629,NaN,17877_Viterbo,NaN,Total,0,94.0,0,88,0,5,0,1,0,0
22630,NaN,17877_Viterbo,NaN,NaN,1,99.0,14,76,1,5,0,1,0,2
22631,NaN,17877_Viterbo,NaN,NaN,2,116.0,59,51,0,4,0,1,0,1
22632,NaN,17877_Viterbo,NaN,NaN,3,104.0,74,27,0,2,0,1,0,0
22633,NaN,17877_Viterbo,NaN,NaN,4,106.0,90,14,0,1,0,0,0,1
22634,NaN,17877_Viterbo,NaN,NaN,Total,519.0,237,256,1,17,0,4,0,4
22635,NaN,17877_Viterbo,Rural disperso,Hombre,0,10.0,0,10,0,0,0,0,0,0
22636,NaN,17877_Viterbo,NaN,NaN,1,12.0,1,11,0,0,0,0,0,0
22637,NaN,17877_Viterbo,NaN,NaN,2,7.0,1,5,1,0,0,0,0,0
22638,NaN,17877_Viterbo,NaN,NaN,3,6.0,1,4,0,1,0,0,0,0
22639,NaN,17877_Viterbo,NaN,NaN,4,9.0,0,8,0,1,0,0,0,0
22640,NaN,17877_Viterbo,NaN,NaN,Total,44.0,3,38,1,2,0,0,0,0
22641,NaN,17877_Viterbo,NaN,Mujer,0,14.0,0,13,1,0,0,0,0,0
22642,NaN,17877_Viterbo,NaN,NaN,1,7.0,0,7,0,0,0,0,0,0
22643,NaN,17877_Viterbo,NaN,NaN,2,9.0,2,6,0,1,0,0,0,0
22644,NaN,17877_Viterbo,NaN,NaN,3,10.0,3,6,1,0,0,0,0,0
22645,NaN,17877_Viterbo,NaN,NaN,4,13.0,2,11,0,0,0,0,0,0
22646,NaN,17877_Viterbo,NaN,NaN,Total,53.0,7,43,2,1,0,0,0,0
22647,NaN,17877_Viterbo,NaN,Total,0,24.0,0,23,1,0,0,0,0,0
22648,NaN,17877_Viterbo,NaN,NaN,1,19.0,1,18,0,0,0,0,0,0
22649,NaN,17877_Viterbo,NaN,NaN,2,16.0,3,11,1,1,0,0,0,0
22650,NaN,17877_Viterbo,NaN,NaN,3,16.0,4,10,1,1,0,0,0,0
22651,NaN,17877_Viterbo,NaN,NaN,4,22.0,2,19,0,1,0,0,0,0
22652,NaN,17877_Viterbo,NaN,NaN,Total,97.0,10,81,3,3,0,0,0,0

Se eliminan las columnas con datos no importantes.

In [8]:
df_15pm = df_15pm.drop(df_15pm.columns[:2], axis=1)
df_15pm

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Total personas menores de 5 años,Dónde o con quién permanece el menor,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
22599,Total Departamental,Hombre,0,62.0,0,59,0,3,0,0,0,0
22600,NaN,NaN,1,59.0,7,47,1,2,0,1,0,1
22601,NaN,NaN,2,72.0,35,33,1,1,0,1,0,1
22602,NaN,NaN,3,65.0,47,16,0,2,0,0,0,0
22603,NaN,NaN,4,70.0,48,20,0,1,0,0,0,1
22604,NaN,NaN,Total,328.0,137,175,2,9,0,2,0,3
22605,NaN,Mujer,0,56.0,0,52,1,2,0,1,0,0
22606,NaN,NaN,1,59.0,8,47,0,3,0,0,0,1
22607,NaN,NaN,2,60.0,27,29,0,4,0,0,0,0
22608,NaN,NaN,3,55.0,31,21,1,1,0,1,0,0
22609,NaN,NaN,4,58.0,44,13,0,1,0,0,0,0
22610,NaN,NaN,Total,288.0,110,162,2,11,0,2,0,1
22611,NaN,Total,0,118.0,0,111,1,5,0,1,0,0
22612,NaN,NaN,1,118.0,15,94,1,5,0,1,0,2
22613,NaN,NaN,2,132.0,62,62,1,5,0,1,0,1
22614,NaN,NaN,3,120.0,78,37,1,3,0,1,0,0
22615,NaN,NaN,4,128.0,92,33,0,2,0,0,0,1
22616,NaN,NaN,Total,616.0,247,337,4,20,0,4,0,4
22617,Cabecera,Hombre,0,52.0,0,49,0,3,0,0,0,0
22618,NaN,NaN,1,47.0,6,36,1,2,0,1,0,1
22619,NaN,NaN,2,65.0,34,28,0,1,0,1,0,1
22620,NaN,NaN,3,59.0,46,12,0,1,0,0,0,0
22621,NaN,NaN,4,61.0,48,12,0,0,0,0,0,1
22622,NaN,NaN,Total,284.0,134,137,1,7,0,2,0,3
22623,NaN,Mujer,0,42.0,0,39,0,2,0,1,0,0
22624,NaN,NaN,1,52.0,8,40,0,3,0,0,0,1
22625,NaN,NaN,2,51.0,25,23,0,3,0,0,0,0
22626,NaN,NaN,3,45.0,28,15,0,1,0,1,0,0
22627,NaN,NaN,4,45.0,42,2,0,1,0,0,0,0
22628,NaN,NaN,Total,235.0,103,119,0,10,0,2,0,1
22629,NaN,Total,0,94.0,0,88,0,5,0,1,0,0
22630,NaN,NaN,1,99.0,14,76,1,5,0,1,0,2
22631,NaN,NaN,2,116.0,59,51,0,4,0,1,0,1
22632,NaN,NaN,3,104.0,74,27,0,2,0,1,0,0
22633,NaN,NaN,4,106.0,90,14,0,1,0,0,0,1
22634,NaN,NaN,Total,519.0,237,256,1,17,0,4,0,4
22635,Rural disperso,Hombre,0,10.0,0,10,0,0,0,0,0,0
22636,NaN,NaN,1,12.0,1,11,0,0,0,0,0,0
22637,NaN,NaN,2,7.0,1,5,1,0,0,0,0,0
22638,NaN,NaN,3,6.0,1,4,0,1,0,0,0,0
22639,NaN,NaN,4,9.0,0,8,0,1,0,0,0,0
22640,NaN,NaN,Total,44.0,3,38,1,2,0,0,0,0
22641,NaN,Mujer,0,14.0,0,13,1,0,0,0,0,0
22642,NaN,NaN,1,7.0,0,7,0,0,0,0,0,0
22643,NaN,NaN,2,9.0,2,6,0,1,0,0,0,0
22644,NaN,NaN,3,10.0,3,6,1,0,0,0,0,0
22645,NaN,NaN,4,13.0,2,11,0,0,0,0,0,0
22646,NaN,NaN,Total,53.0,7,43,2,1,0,0,0,0
22647,NaN,Total,0,24.0,0,23,1,0,0,0,0,0
22648,NaN,NaN,1,19.0,1,18,0,0,0,0,0,0
22649,NaN,NaN,2,16.0,3,11,1,1,0,0,0,0
22650,NaN,NaN,3,16.0,4,10,1,1,0,0,0,0
22651,NaN,NaN,4,22.0,2,19,0,1,0,0,0,0
22652,NaN,NaN,Total,97.0,10,81,3,3,0,0,0,0

Se asignan los headers.

In [9]:
df_15pm.rename(columns=dict(zip(list(df_15pm.columns.values), actual_headers)), inplace=True)
df_15pm

,Area,Sexo,Edad,Total personas menores de 5 anios,"Asiste a un hogar comunitario, jardín, centro de desarrollo infantil o colegio",Con su padre o madre en la vivienda,Con su padre o madre en el trabajo,En la vivienda donde vive el niño al cuidado de un pariente o una persona de 18 años o más,En la vivienda donde vive el niño al cuidado de un pariente o una persona menor de 18 años,Al cuidado de un pariente o de otra persona en otro lugar,"En la vivienda, solo",Sin Información
22599,Total Departamental,Hombre,0,62.0,0,59,0,3,0,0,0,0
22600,NaN,NaN,1,59.0,7,47,1,2,0,1,0,1
22601,NaN,NaN,2,72.0,35,33,1,1,0,1,0,1
22602,NaN,NaN,3,65.0,47,16,0,2,0,0,0,0
22603,NaN,NaN,4,70.0,48,20,0,1,0,0,0,1
22604,NaN,NaN,Total,328.0,137,175,2,9,0,2,0,3
22605,NaN,Mujer,0,56.0,0,52,1,2,0,1,0,0
22606,NaN,NaN,1,59.0,8,47,0,3,0,0,0,1
22607,NaN,NaN,2,60.0,27,29,0,4,0,0,0,0
22608,NaN,NaN,3,55.0,31,21,1,1,0,1,0,0
22609,NaN,NaN,4,58.0,44,13,0,1,0,0,0,0
22610,NaN,NaN,Total,288.0,110,162,2,11,0,2,0,1
22611,NaN,Total,0,118.0,0,111,1,5,0,1,0,0
22612,NaN,NaN,1,118.0,15,94,1,5,0,1,0,2
22613,NaN,NaN,2,132.0,62,62,1,5,0,1,0,1
22614,NaN,NaN,3,120.0,78,37,1,3,0,1,0,0
22615,NaN,NaN,4,128.0,92,33,0,2,0,0,0,1
22616,NaN,NaN,Total,616.0,247,337,4,20,0,4,0,4
22617,Cabecera,Hombre,0,52.0,0,49,0,3,0,0,0,0
22618,NaN,NaN,1,47.0,6,36,1,2,0,1,0,1
22619,NaN,NaN,2,65.0,34,28,0,1,0,1,0,1
22620,NaN,NaN,3,59.0,46,12,0,1,0,0,0,0
22621,NaN,NaN,4,61.0,48,12,0,0,0,0,0,1
22622,NaN,NaN,Total,284.0,134,137,1,7,0,2,0,3
22623,NaN,Mujer,0,42.0,0,39,0,2,0,1,0,0
22624,NaN,NaN,1,52.0,8,40,0,3,0,0,0,1
22625,NaN,NaN,2,51.0,25,23,0,3,0,0,0,0
22626,NaN,NaN,3,45.0,28,15,0,1,0,1,0,0
22627,NaN,NaN,4,45.0,42,2,0,1,0,0,0,0
22628,NaN,NaN,Total,235.0,103,119,0,10,0,2,0,1
22629,NaN,Total,0,94.0,0,88,0,5,0,1,0,0
22630,NaN,NaN,1,99.0,14,76,1,5,0,1,0,2
22631,NaN,NaN,2,116.0,59,51,0,4,0,1,0,1
22632,NaN,NaN,3,104.0,74,27,0,2,0,1,0,0
22633,NaN,NaN,4,106.0,90,14,0,1,0,0,0,1
22634,NaN,NaN,Total,519.0,237,256,1,17,0,4,0,4
22635,Rural disperso,Hombre,0,10.0,0,10,0,0,0,0,0,0
22636,NaN,NaN,1,12.0,1,11,0,0,0,0,0,0
22637,NaN,NaN,2,7.0,1,5,1,0,0,0,0,0
22638,NaN,NaN,3,6.0,1,4,0,1,0,0,0,0
22639,NaN,NaN,4,9.0,0,8,0,1,0,0,0,0
22640,NaN,NaN,Total,44.0,3,38,1,2,0,0,0,0
22641,NaN,Mujer,0,14.0,0,13,1,0,0,0,0,0
22642,NaN,NaN,1,7.0,0,7,0,0,0,0,0,0
22643,NaN,NaN,2,9.0,2,6,0,1,0,0,0,0
22644,NaN,NaN,3,10.0,3,6,1,0,0,0,0,0
22645,NaN,NaN,4,13.0,2,11,0,0,0,0,0,0
22646,NaN,NaN,Total,53.0,7,43,2,1,0,0,0,0
22647,NaN,Total,0,24.0,0,23,1,0,0,0,0,0
22648,NaN,NaN,1,19.0,1,18,0,0,0,0,0,0
22649,NaN,NaN,2,16.0,3,11,1,1,0,0,0,0
22650,NaN,NaN,3,16.0,4,10,1,1,0,0,0,0
22651,NaN,NaN,4,22.0,2,19,0,1,0,0,0,0
22652,NaN,NaN,Total,97.0,10,81,3,3,0,0,0,0

Se propagan los datos de las columnas 'Area' y 'Sexo' para completar los datos faltantes.

In [10]:
df_15pm['Area'] = df_15pm['Area'].ffill()
df_15pm['Sexo'] = df_15pm['Sexo'].ffill()
df_15pm

,Area,Sexo,Edad,Total personas menores de 5 anios,"Asiste a un hogar comunitario, jardín, centro de desarrollo infantil o colegio",Con su padre o madre en la vivienda,Con su padre o madre en el trabajo,En la vivienda donde vive el niño al cuidado de un pariente o una persona de 18 años o más,En la vivienda donde vive el niño al cuidado de un pariente o una persona menor de 18 años,Al cuidado de un pariente o de otra persona en otro lugar,"En la vivienda, solo",Sin Información
22599,Total Departamental,Hombre,0,62.0,0,59,0,3,0,0,0,0
22600,Total Departamental,Hombre,1,59.0,7,47,1,2,0,1,0,1
22601,Total Departamental,Hombre,2,72.0,35,33,1,1,0,1,0,1
22602,Total Departamental,Hombre,3,65.0,47,16,0,2,0,0,0,0
22603,Total Departamental,Hombre,4,70.0,48,20,0,1,0,0,0,1
22604,Total Departamental,Hombre,Total,328.0,137,175,2,9,0,2,0,3
22605,Total Departamental,Mujer,0,56.0,0,52,1,2,0,1,0,0
22606,Total Departamental,Mujer,1,59.0,8,47,0,3,0,0,0,1
22607,Total Departamental,Mujer,2,60.0,27,29,0,4,0,0,0,0
22608,Total Departamental,Mujer,3,55.0,31,21,1,1,0,1,0,0
22609,Total Departamental,Mujer,4,58.0,44,13,0,1,0,0,0,0
22610,Total Departamental,Mujer,Total,288.0,110,162,2,11,0,2,0,1
22611,Total Departamental,Total,0,118.0,0,111,1,5,0,1,0,0
22612,Total Departamental,Total,1,118.0,15,94,1,5,0,1,0,2
22613,Total Departamental,Total,2,132.0,62,62,1,5,0,1,0,1
22614,Total Departamental,Total,3,120.0,78,37,1,3,0,1,0,0
22615,Total Departamental,Total,4,128.0,92,33,0,2,0,0,0,1
22616,Total Departamental,Total,Total,616.0,247,337,4,20,0,4,0,4
22617,Cabecera,Hombre,0,52.0,0,49,0,3,0,0,0,0
22618,Cabecera,Hombre,1,47.0,6,36,1,2,0,1,0,1
22619,Cabecera,Hombre,2,65.0,34,28,0,1,0,1,0,1
22620,Cabecera,Hombre,3,59.0,46,12,0,1,0,0,0,0
22621,Cabecera,Hombre,4,61.0,48,12,0,0,0,0,0,1
22622,Cabecera,Hombre,Total,284.0,134,137,1,7,0,2,0,3
22623,Cabecera,Mujer,0,42.0,0,39,0,2,0,1,0,0
22624,Cabecera,Mujer,1,52.0,8,40,0,3,0,0,0,1
22625,Cabecera,Mujer,2,51.0,25,23,0,3,0,0,0,0
22626,Cabecera,Mujer,3,45.0,28,15,0,1,0,1,0,0
22627,Cabecera,Mujer,4,45.0,42,2,0,1,0,0,0,0
22628,Cabecera,Mujer,Total,235.0,103,119,0,10,0,2,0,1
22629,Cabecera,Total,0,94.0,0,88,0,5,0,1,0,0
22630,Cabecera,Total,1,99.0,14,76,1,5,0,1,0,2
22631,Cabecera,Total,2,116.0,59,51,0,4,0,1,0,1
22632,Cabecera,Total,3,104.0,74,27,0,2,0,1,0,0
22633,Cabecera,Total,4,106.0,90,14,0,1,0,0,0,1
22634,Cabecera,Total,Total,519.0,237,256,1,17,0,4,0,4
22635,Rural disperso,Hombre,0,10.0,0,10,0,0,0,0,0,0
22636,Rural disperso,Hombre,1,12.0,1,11,0,0,0,0,0,0
22637,Rural disperso,Hombre,2,7.0,1,5,1,0,0,0,0,0
22638,Rural disperso,Hombre,3,6.0,1,4,0,1,0,0,0,0
22639,Rural disperso,Hombre,4,9.0,0,8,0,1,0,0,0,0
22640,Rural disperso,Hombre,Total,44.0,3,38,1,2,0,0,0,0
22641,Rural disperso,Mujer,0,14.0,0,13,1,0,0,0,0,0
22642,Rural disperso,Mujer,1,7.0,0,7,0,0,0,0,0,0
22643,Rural disperso,Mujer,2,9.0,2,6,0,1,0,0,0,0
22644,Rural disperso,Mujer,3,10.0,3,6,1,0,0,0,0,0
22645,Rural disperso,Mujer,4,13.0,2,11,0,0,0,0,0,0
22646,Rural disperso,Mujer,Total,53.0,7,43,2,1,0,0,0,0
22647,Rural disperso,Total,0,24.0,0,23,1,0,0,0,0,0
22648,Rural disperso,Total,1,19.0,1,18,0,0,0,0,0,0
22649,Rural disperso,Total,2,16.0,3,11,1,1,0,0,0,0
22650,Rural disperso,Total,3,16.0,4,10,1,1,0,0,0,0
22651,Rural disperso,Total,4,22.0,2,19,0,1,0,0,0,0
22652,Rural disperso,Total,Total,97.0,10,81,3,3,0,0,0,0

Se renombran los headers que tienen tildes y ñ.

In [11]:
df_15pm.rename(columns={
    'Asiste a un hogar comunitario, jardín, centro de desarrollo infantil o colegio': 'Asiste a un hogar comunitario, jardin, centro de desarrollo infantil o colegio',
    'En la vivienda donde vive el niño al cuidado de un pariente o una persona de 18 años o más': 'En la vivienda donde vive el ninioo al cuidado de un pariente o una persona de 18 anios o mas',
    'En la vivienda donde vive el niño al cuidado de un pariente o una persona menor de 18 años': 'En la vivienda donde vive el ninio al cuidado de un pariente o una persona menor de 18 anios',
    'Sin Información': 'Sin Informacion'
}, inplace=True)

df_15pm

,Area,Sexo,Edad,Total personas menores de 5 anios,"Asiste a un hogar comunitario, jardin, centro de desarrollo infantil o colegio",Con su padre o madre en la vivienda,Con su padre o madre en el trabajo,En la vivienda donde vive el ninioo al cuidado de un pariente o una persona de 18 anios o mas,En la vivienda donde vive el ninio al cuidado de un pariente o una persona menor de 18 anios,Al cuidado de un pariente o de otra persona en otro lugar,"En la vivienda, solo",Sin Informacion
22599,Total Departamental,Hombre,0,62.0,0,59,0,3,0,0,0,0
22600,Total Departamental,Hombre,1,59.0,7,47,1,2,0,1,0,1
22601,Total Departamental,Hombre,2,72.0,35,33,1,1,0,1,0,1
22602,Total Departamental,Hombre,3,65.0,47,16,0,2,0,0,0,0
22603,Total Departamental,Hombre,4,70.0,48,20,0,1,0,0,0,1
22604,Total Departamental,Hombre,Total,328.0,137,175,2,9,0,2,0,3
22605,Total Departamental,Mujer,0,56.0,0,52,1,2,0,1,0,0
22606,Total Departamental,Mujer,1,59.0,8,47,0,3,0,0,0,1
22607,Total Departamental,Mujer,2,60.0,27,29,0,4,0,0,0,0
22608,Total Departamental,Mujer,3,55.0,31,21,1,1,0,1,0,0
22609,Total Departamental,Mujer,4,58.0,44,13,0,1,0,0,0,0
22610,Total Departamental,Mujer,Total,288.0,110,162,2,11,0,2,0,1
22611,Total Departamental,Total,0,118.0,0,111,1,5,0,1,0,0
22612,Total Departamental,Total,1,118.0,15,94,1,5,0,1,0,2
22613,Total Departamental,Total,2,132.0,62,62,1,5,0,1,0,1
22614,Total Departamental,Total,3,120.0,78,37,1,3,0,1,0,0
22615,Total Departamental,Total,4,128.0,92,33,0,2,0,0,0,1
22616,Total Departamental,Total,Total,616.0,247,337,4,20,0,4,0,4
22617,Cabecera,Hombre,0,52.0,0,49,0,3,0,0,0,0
22618,Cabecera,Hombre,1,47.0,6,36,1,2,0,1,0,1
22619,Cabecera,Hombre,2,65.0,34,28,0,1,0,1,0,1
22620,Cabecera,Hombre,3,59.0,46,12,0,1,0,0,0,0
22621,Cabecera,Hombre,4,61.0,48,12,0,0,0,0,0,1
22622,Cabecera,Hombre,Total,284.0,134,137,1,7,0,2,0,3
22623,Cabecera,Mujer,0,42.0,0,39,0,2,0,1,0,0
22624,Cabecera,Mujer,1,52.0,8,40,0,3,0,0,0,1
22625,Cabecera,Mujer,2,51.0,25,23,0,3,0,0,0,0
22626,Cabecera,Mujer,3,45.0,28,15,0,1,0,1,0,0
22627,Cabecera,Mujer,4,45.0,42,2,0,1,0,0,0,0
22628,Cabecera,Mujer,Total,235.0,103,119,0,10,0,2,0,1
22629,Cabecera,Total,0,94.0,0,88,0,5,0,1,0,0
22630,Cabecera,Total,1,99.0,14,76,1,5,0,1,0,2
22631,Cabecera,Total,2,116.0,59,51,0,4,0,1,0,1
22632,Cabecera,Total,3,104.0,74,27,0,2,0,1,0,0
22633,Cabecera,Total,4,106.0,90,14,0,1,0,0,0,1
22634,Cabecera,Total,Total,519.0,237,256,1,17,0,4,0,4
22635,Rural disperso,Hombre,0,10.0,0,10,0,0,0,0,0,0
22636,Rural disperso,Hombre,1,12.0,1,11,0,0,0,0,0,0
22637,Rural disperso,Hombre,2,7.0,1,5,1,0,0,0,0,0
22638,Rural disperso,Hombre,3,6.0,1,4,0,1,0,0,0,0
22639,Rural disperso,Hombre,4,9.0,0,8,0,1,0,0,0,0
22640,Rural disperso,Hombre,Total,44.0,3,38,1,2,0,0,0,0
22641,Rural disperso,Mujer,0,14.0,0,13,1,0,0,0,0,0
22642,Rural disperso,Mujer,1,7.0,0,7,0,0,0,0,0,0
22643,Rural disperso,Mujer,2,9.0,2,6,0,1,0,0,0,0
22644,Rural disperso,Mujer,3,10.0,3,6,1,0,0,0,0,0
22645,Rural disperso,Mujer,4,13.0,2,11,0,0,0,0,0,0
22646,Rural disperso,Mujer,Total,53.0,7,43,2,1,0,0,0,0
22647,Rural disperso,Total,0,24.0,0,23,1,0,0,0,0,0
22648,Rural disperso,Total,1,19.0,1,18,0,0,0,0,0,0
22649,Rural disperso,Total,2,16.0,3,11,1,1,0,0,0,0
22650,Rural disperso,Total,3,16.0,4,10,1,1,0,0,0,0
22651,Rural disperso,Total,4,22.0,2,19,0,1,0,0,0,0
22652,Rural disperso,Total,Total,97.0,10,81,3,3,0,0,0,0

Se creará una copia del dataframe y se removerán las filas y columnas con resumenes de datos para el csv que no contiene resúmenes.

In [12]:
df_15pm_cleaned = df_15pm.copy()
df_15pm_cleaned.drop(['Total personas menores de 5 anios'], axis=1, inplace=True)
df_15pm_cleaned

,Area,Sexo,Edad,"Asiste a un hogar comunitario, jardin, centro de desarrollo infantil o colegio",Con su padre o madre en la vivienda,Con su padre o madre en el trabajo,En la vivienda donde vive el ninioo al cuidado de un pariente o una persona de 18 anios o mas,En la vivienda donde vive el ninio al cuidado de un pariente o una persona menor de 18 anios,Al cuidado de un pariente o de otra persona en otro lugar,"En la vivienda, solo",Sin Informacion
22599,Total Departamental,Hombre,0,0,59,0,3,0,0,0,0
22600,Total Departamental,Hombre,1,7,47,1,2,0,1,0,1
22601,Total Departamental,Hombre,2,35,33,1,1,0,1,0,1
22602,Total Departamental,Hombre,3,47,16,0,2,0,0,0,0
22603,Total Departamental,Hombre,4,48,20,0,1,0,0,0,1
22604,Total Departamental,Hombre,Total,137,175,2,9,0,2,0,3
22605,Total Departamental,Mujer,0,0,52,1,2,0,1,0,0
22606,Total Departamental,Mujer,1,8,47,0,3,0,0,0,1
22607,Total Departamental,Mujer,2,27,29,0,4,0,0,0,0
22608,Total Departamental,Mujer,3,31,21,1,1,0,1,0,0
22609,Total Departamental,Mujer,4,44,13,0,1,0,0,0,0
22610,Total Departamental,Mujer,Total,110,162,2,11,0,2,0,1
22611,Total Departamental,Total,0,0,111,1,5,0,1,0,0
22612,Total Departamental,Total,1,15,94,1,5,0,1,0,2
22613,Total Departamental,Total,2,62,62,1,5,0,1,0,1
22614,Total Departamental,Total,3,78,37,1,3,0,1,0,0
22615,Total Departamental,Total,4,92,33,0,2,0,0,0,1
22616,Total Departamental,Total,Total,247,337,4,20,0,4,0,4
22617,Cabecera,Hombre,0,0,49,0,3,0,0,0,0
22618,Cabecera,Hombre,1,6,36,1,2,0,1,0,1
22619,Cabecera,Hombre,2,34,28,0,1,0,1,0,1
22620,Cabecera,Hombre,3,46,12,0,1,0,0,0,0
22621,Cabecera,Hombre,4,48,12,0,0,0,0,0,1
22622,Cabecera,Hombre,Total,134,137,1,7,0,2,0,3
22623,Cabecera,Mujer,0,0,39,0,2,0,1,0,0
22624,Cabecera,Mujer,1,8,40,0,3,0,0,0,1
22625,Cabecera,Mujer,2,25,23,0,3,0,0,0,0
22626,Cabecera,Mujer,3,28,15,0,1,0,1,0,0
22627,Cabecera,Mujer,4,42,2,0,1,0,0,0,0
22628,Cabecera,Mujer,Total,103,119,0,10,0,2,0,1
22629,Cabecera,Total,0,0,88,0,5,0,1,0,0
22630,Cabecera,Total,1,14,76,1,5,0,1,0,2
22631,Cabecera,Total,2,59,51,0,4,0,1,0,1
22632,Cabecera,Total,3,74,27,0,2,0,1,0,0
22633,Cabecera,Total,4,90,14,0,1,0,0,0,1
22634,Cabecera,Total,Total,237,256,1,17,0,4,0,4
22635,Rural disperso,Hombre,0,0,10,0,0,0,0,0,0
22636,Rural disperso,Hombre,1,1,11,0,0,0,0,0,0
22637,Rural disperso,Hombre,2,1,5,1,0,0,0,0,0
22638,Rural disperso,Hombre,3,1,4,0,1,0,0,0,0
22639,Rural disperso,Hombre,4,0,8,0,1,0,0,0,0
22640,Rural disperso,Hombre,Total,3,38,1,2,0,0,0,0
22641,Rural disperso,Mujer,0,0,13,1,0,0,0,0,0
22642,Rural disperso,Mujer,1,0,7,0,0,0,0,0,0
22643,Rural disperso,Mujer,2,2,6,0,1,0,0,0,0
22644,Rural disperso,Mujer,3,3,6,1,0,0,0,0,0
22645,Rural disperso,Mujer,4,2,11,0,0,0,0,0,0
22646,Rural disperso,Mujer,Total,7,43,2,1,0,0,0,0
22647,Rural disperso,Total,0,0,23,1,0,0,0,0,0
22648,Rural disperso,Total,1,1,18,0,0,0,0,0,0
22649,Rural disperso,Total,2,3,11,1,1,0,0,0,0
22650,Rural disperso,Total,3,4,10,1,1,0,0,0,0
22651,Rural disperso,Total,4,2,19,0,1,0,0,0,0
22652,Rural disperso,Total,Total,10,81,3,3,0,0,0,0

In [13]:
df_15pm_cleaned = df_15pm_cleaned.loc[(df_15pm_cleaned['Area'] != 'Total Departamental') & (df_15pm_cleaned['Sexo'] != 'Total') & (df_15pm_cleaned['Edad'] != 'Total')]
df_15pm_cleaned

,Area,Sexo,Edad,"Asiste a un hogar comunitario, jardin, centro de desarrollo infantil o colegio",Con su padre o madre en la vivienda,Con su padre o madre en el trabajo,En la vivienda donde vive el ninioo al cuidado de un pariente o una persona de 18 anios o mas,En la vivienda donde vive el ninio al cuidado de un pariente o una persona menor de 18 anios,Al cuidado de un pariente o de otra persona en otro lugar,"En la vivienda, solo",Sin Informacion
22617,Cabecera,Hombre,0,0,49,0,3,0,0,0,0
22618,Cabecera,Hombre,1,6,36,1,2,0,1,0,1
22619,Cabecera,Hombre,2,34,28,0,1,0,1,0,1
22620,Cabecera,Hombre,3,46,12,0,1,0,0,0,0
22621,Cabecera,Hombre,4,48,12,0,0,0,0,0,1
22623,Cabecera,Mujer,0,0,39,0,2,0,1,0,0
22624,Cabecera,Mujer,1,8,40,0,3,0,0,0,1
22625,Cabecera,Mujer,2,25,23,0,3,0,0,0,0
22626,Cabecera,Mujer,3,28,15,0,1,0,1,0,0
22627,Cabecera,Mujer,4,42,2,0,1,0,0,0,0
22635,Rural disperso,Hombre,0,0,10,0,0,0,0,0,0
22636,Rural disperso,Hombre,1,1,11,0,0,0,0,0,0
22637,Rural disperso,Hombre,2,1,5,1,0,0,0,0,0
22638,Rural disperso,Hombre,3,1,4,0,1,0,0,0,0
22639,Rural disperso,Hombre,4,0,8,0,1,0,0,0,0
22641,Rural disperso,Mujer,0,0,13,1,0,0,0,0,0
22642,Rural disperso,Mujer,1,0,7,0,0,0,0,0,0
22643,Rural disperso,Mujer,2,2,6,0,1,0,0,0,0
22644,Rural disperso,Mujer,3,3,6,1,0,0,0,0,0
22645,Rural disperso,Mujer,4,2,11,0,0,0,0,0,0

Los dataframes están listos para ser exportados a CSV.

In [14]:
df_15pm.to_csv(csv_total_path, index=False)
df_15pm_cleaned.to_csv(csv_path, index=False)