In [62]:
# imports
import pandas as pd

In [63]:
# Ruta relativa del xslx que contiene los datos
original_data_path = 'Data\\Original\\PERSONAS_DEMOGRAFICO_Cuadros_CNPV_2018.xlsx'

# Nombre del csv objetivo
csv_filename = 'caldas_viterbo_12PM.csv'

# Ruta relativa del csv objetivo
csv_path = 'Data\\Datasets\\' + csv_filename

In [64]:
# Lee archivo xlsx
df_12pm = pd.read_excel(original_data_path, sheet_name='12PM', skiprows=9)
df_12pm.head()

,"Departamento, municipio y grupos de edad",Unnamed: 1,Unnamed: 2,Total,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Rural disperso,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
0,NaN,NaN,NaN,Total,Indígena,Gitano(a) o Rrom,"Raizal del Archipielago de San Andrés, Provide...",Palenquero(a) de San Basilio,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",Ningún grupo étnico,...,Sin información,NaN,Total,Indígena,Gitano(a) o Rrom,"Raizal del Archipielago de San Andrés, Provide...",Palenquero(a) de San Basilio,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",Ningún grupo étnico,Sin información
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Total Nacional,NaN,Total,43835324,1876752,2606,25344,6635,2942859,38459411,...,22264,NaN,6808647,1261154,169,1099,374,421506,5044245,80100
3,NaN,NaN,0-4 años,3033307,205766,175,1776,373,231856,2557741,...,2349,NaN,564834,154875,8,87,18,37497,360194,12155
4,NaN,NaN,5-9 años,3319877,216780,206,1866,448,267401,2802604,...,1622,NaN,629955,159996,11,76,30,45793,416384,7665

Ya que las columnas están agrupadas por área, y es necesario modificar los headers, se extraerán los headers correctos en una lista y se utilizarán apra modificar los headers actuales en un paso futuro cuando se tengan conjuntos de datos más reducidos.

In [65]:
first_row = list(df_12pm.iloc[0])[:]
for (i, value) in enumerate(first_row):
    print(i, value)

0 nan
1 nan
2 nan
3 Total
4 Indígena
5 Gitano(a) o Rrom
6 Raizal del Archipielago de San Andrés, Providencia y Santa Catalina
7 Palenquero(a) de San Basilio
8 Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)
9 Ningún grupo étnico
10 Sin información
11 nan
12 Total
13 Indígena
14 Gitano(a) o Rrom
15 Raizal del Archipielago de San Andrés, Providencia y Santa Catalina
16 Palenquero(a) de San Basilio
17 Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)
18 Ningún grupo étnico
19 Sin información
20 nan
21 Total
22 Indígena
23 Gitano(a) o Rrom
24 Raizal del Archipielago de San Andrés, Providencia y Santa Catalina
25 Palenquero(a) de San Basilio
26 Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)
27 Ningún grupo étnico
28 Sin información
29 nan
30 Total
31 Indígena
32 Gitano(a) o Rrom
33 Raizal del Archipielago de San Andrés, Providencia y Santa Catalina
34 Palenquero(a) de San Basilio
35 Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)
36 Ningún grupo étnico
37 Sin información

In [66]:
actual_headers = list(df_12pm.iloc[0][4:11])
actual_headers

['Indígena',
 'Gitano(a) o Rrom',
 'Raizal del Archipielago de San Andrés, Providencia y Santa Catalina',
 'Palenquero(a) de San Basilio',
 'Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)',
 'Ningún grupo étnico',
 'Sin información']

Se filtrarán los datos que no corresponden al municipio de Viterbo Caldas, para ello se propagará el municipio, el cual se encuentra en la columna "Unnamed: 1" y se seleccionarán solo los registros que contengan el identificador de Viterbo dentro del dataframe, para este caso es "17877_Viterbo".

In [67]:
df_12pm['Unnamed: 1'] = df_12pm['Unnamed: 1'].ffill()
df_12pm = df_12pm.loc[df_12pm['Unnamed: 1'] == '17877_Viterbo']
df_12pm

,"Departamento, municipio y grupos de edad",Unnamed: 1,Unnamed: 2,Total,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Rural disperso,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
6557,NaN,17877_Viterbo,Total,12425,172,1,0,1,97,12097,...,0,NaN,1761,102,0,0,0,8,1646,5
6558,NaN,17877_Viterbo,0-4 años,616,17,0,0,0,10,586,...,0,NaN,97,13,0,0,0,0,84,0
6559,NaN,17877_Viterbo,5-9 años,742,10,0,0,0,6,725,...,0,NaN,122,7,0,0,0,0,115,0
6560,NaN,17877_Viterbo,10-14 años,941,21,0,0,0,5,912,...,0,NaN,162,16,0,0,0,0,146,0
6561,NaN,17877_Viterbo,15-19 años,1070,23,0,0,0,13,1029,...,0,NaN,187,12,0,0,0,1,174,0
6562,NaN,17877_Viterbo,20-24 años,958,18,1,0,0,12,918,...,0,NaN,123,8,0,0,0,1,114,0
6563,NaN,17877_Viterbo,25-29 años,855,17,0,0,0,8,824,...,0,NaN,107,10,0,0,0,0,97,0
6564,NaN,17877_Viterbo,30-34 años,779,11,0,0,0,4,759,...,0,NaN,105,6,0,0,0,0,99,0
6565,NaN,17877_Viterbo,35-39 años,840,10,0,0,1,8,817,...,0,NaN,117,7,0,0,0,0,109,1
6566,NaN,17877_Viterbo,40-44 años,747,9,0,0,0,1,731,...,0,NaN,113,6,0,0,0,0,107,0
6567,NaN,17877_Viterbo,45-49 años,852,10,0,0,0,7,832,...,0,NaN,116,5,0,0,0,0,110,1
6568,NaN,17877_Viterbo,50-54 años,846,5,0,0,0,6,830,...,0,NaN,116,3,0,0,0,0,111,2
6569,NaN,17877_Viterbo,55-59 años,785,3,0,0,0,2,780,...,0,NaN,99,0,0,0,0,2,97,0
6570,NaN,17877_Viterbo,60-64 años,650,6,0,0,0,3,638,...,0,NaN,101,3,0,0,0,2,95,1
6571,NaN,17877_Viterbo,65-69 años,573,5,0,0,0,3,563,...,0,NaN,77,3,0,0,0,0,74,0
6572,NaN,17877_Viterbo,70-74 años,434,2,0,0,0,3,429,...,0,NaN,60,0,0,0,0,1,59,0
6573,NaN,17877_Viterbo,75-79 años,352,3,0,0,0,3,346,...,0,NaN,30,3,0,0,0,1,26,0
6574,NaN,17877_Viterbo,80-84 años,212,1,0,0,0,1,209,...,0,NaN,16,0,0,0,0,0,16,0
6575,NaN,17877_Viterbo,85 años y más,173,1,0,0,0,2,169,...,0,NaN,13,0,0,0,0,0,13,0

Debido a la agrupación de columnas por área, se separan los datos por subconjuntos dependiendo del área y al final serán reunidos en un mismo dataframe con el área presente en las filas, se eliminan columnas con resumenes de datos, aka totales.

In [68]:
# Pendiente de automatizar con loops, resolver problemas de manipulación de dataframes dentro de for loops
ls_df = []
df_12pm_grupo_edad = df_12pm['Unnamed: 2']
df_12pm_cabecera = pd.concat([df_12pm_grupo_edad, df_12pm.iloc[:,13:20]], axis=1)
ls_df.append(df_12pm_cabecera)
df_12pm_centros_poblados = pd.concat([df_12pm_grupo_edad, df_12pm.iloc[:,22:29]], axis=1)
ls_df.append(df_12pm_centros_poblados)
df_12pm_rural_disperso = pd.concat([df_12pm_grupo_edad, df_12pm.iloc[:,31:]], axis=1)
ls_df.append(df_12pm_rural_disperso)
ls_df
df_12pm_cabecera = df_12pm_cabecera.rename(columns={'Unnamed: 2':'Grupo edad'})
df_12pm_centros_poblados = df_12pm_centros_poblados.rename(columns={'Unnamed: 2':'Grupo edad'})
df_12pm_rural_disperso = df_12pm_rural_disperso.rename(columns={'Unnamed: 2':'Grupo edad'})
df_12pm_cabecera.columns.values[1:] = actual_headers[:]
df_12pm_centros_poblados.columns.values[1:] = actual_headers[:]
df_12pm_rural_disperso.columns.values[1:] = actual_headers[:]
df_12pm_cabecera = df_12pm_cabecera.assign(Area='cabecera')
df_12pm_centros_poblados = df_12pm_centros_poblados.assign(Area='centro poblado')
df_12pm_rural_disperso = df_12pm_rural_disperso.assign(Area='rural disperso')
df_12pm = pd.concat([df_12pm_cabecera, df_12pm_centros_poblados, df_12pm_rural_disperso])
df_12pm

,Grupo edad,Indígena,Gitano(a) o Rrom,"Raizal del Archipielago de San Andrés, Providencia y Santa Catalina",Palenquero(a) de San Basilio,"Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)",Ningún grupo étnico,Sin información,Area
6557,Total,70,1,0,1,89,10451,52,cabecera
6558,0-4 años,4,0,0,0,10,502,3,cabecera
6559,5-9 años,3,0,0,0,6,610,1,cabecera
6560,10-14 años,5,0,0,0,5,766,3,cabecera
6561,15-19 años,11,0,0,0,12,855,5,cabecera
6562,20-24 años,10,1,0,0,11,804,9,cabecera
6563,25-29 años,7,0,0,0,8,727,6,cabecera
6564,30-34 años,5,0,0,0,4,660,5,cabecera
6565,35-39 años,3,0,0,1,8,708,3,cabecera
6566,40-44 años,3,0,0,0,1,624,6,cabecera
6567,45-49 años,5,0,0,0,7,722,2,cabecera
6568,50-54 años,2,0,0,0,6,719,3,cabecera
6569,55-59 años,3,0,0,0,0,683,0,cabecera
6570,60-64 años,3,0,0,0,1,543,2,cabecera
6571,65-69 años,2,0,0,0,3,489,2,cabecera
6572,70-74 años,2,0,0,0,2,370,0,cabecera
6573,75-79 años,0,0,0,0,2,320,0,cabecera
6574,80-84 años,1,0,0,0,1,193,1,cabecera
6575,85 años y más,1,0,0,0,2,156,1,cabecera
6557,Total,0,0,0,0,0,0,0,centro poblado
6558,0-4 años,0,0,0,0,0,0,0,centro poblado
6559,5-9 años,0,0,0,0,0,0,0,centro poblado
6560,10-14 años,0,0,0,0,0,0,0,centro poblado
6561,15-19 años,0,0,0,0,0,0,0,centro poblado
6562,20-24 años,0,0,0,0,0,0,0,centro poblado
6563,25-29 años,0,0,0,0,0,0,0,centro poblado
6564,30-34 años,0,0,0,0,0,0,0,centro poblado
6565,35-39 años,0,0,0,0,0,0,0,centro poblado
6566,40-44 años,0,0,0,0,0,0,0,centro poblado
6567,45-49 años,0,0,0,0,0,0,0,centro poblado
6568,50-54 años,0,0,0,0,0,0,0,centro poblado
6569,55-59 años,0,0,0,0,0,0,0,centro poblado
6570,60-64 años,0,0,0,0,0,0,0,centro poblado
6571,65-69 años,0,0,0,0,0,0,0,centro poblado
6572,70-74 años,0,0,0,0,0,0,0,centro poblado
6573,75-79 años,0,0,0,0,0,0,0,centro poblado
6574,80-84 años,0,0,0,0,0,0,0,centro poblado
6575,85 años y más,0,0,0,0,0,0,0,centro poblado
6557,Total,102,0,0,0,8,1646,5,rural disperso
6558,0-4 años,13,0,0,0,0,84,0,rural disperso
6559,5-9 años,7,0,0,0,0,115,0,rural disperso
6560,10-14 años,16,0,0,0,0,146,0,rural disperso
6561,15-19 años,12,0,0,0,1,174,0,rural disperso
6562,20-24 años,8,0,0,0,1,114,0,rural disperso
6563,25-29 años,10,0,0,0,0,97,0,rural disperso
6564,30-34 años,6,0,0,0,0,99,0,rural disperso
6565,35-39 años,7,0,0,0,0,109,1,rural disperso
6566,40-44 años,6,0,0,0,0,107,0,rural disperso
6567,45-49 años,5,0,0,0,0,110,1,rural disperso
6568,50-54 años,3,0,0,0,0,111,2,rural disperso
6569,55-59 años,0,0,0,0,2,97,0,rural disperso
6570,60-64 años,3,0,0,0,2,95,1,rural disperso
6571,65-69 años,3,0,0,0,0,74,0,rural disperso
6572,70-74 años,0,0,0,0,1,59,0,rural disperso
6573,75-79 años,3,0,0,0,1,26,0,rural disperso
6574,80-84 años,0,0,0,0,0,16,0,rural disperso
6575,85 años y más,0,0,0,0,0,13,0,rural disperso

Se renombran los headers que tienen tildes y ñ.

In [69]:
df_12pm = df_12pm.rename(columns={'Indígena':'Indigena', 
                        'Raizal del Archipielago de San Andrés, Providencia y Santa Catalina':'Raizal del Archipielago de San Andres, Providencia y Santa Catalina', 
                        'Ningún grupo étnico':'Ningun grupo etnico',
                        'Sin información':'Sin informacion'})
df_12pm

,Grupo edad,Indigena,Gitano(a) o Rrom,"Raizal del Archipielago de San Andres, Providencia y Santa Catalina",Palenquero(a) de San Basilio,"Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)",Ningun grupo etnico,Sin informacion,Area
6557,Total,70,1,0,1,89,10451,52,cabecera
6558,0-4 años,4,0,0,0,10,502,3,cabecera
6559,5-9 años,3,0,0,0,6,610,1,cabecera
6560,10-14 años,5,0,0,0,5,766,3,cabecera
6561,15-19 años,11,0,0,0,12,855,5,cabecera
6562,20-24 años,10,1,0,0,11,804,9,cabecera
6563,25-29 años,7,0,0,0,8,727,6,cabecera
6564,30-34 años,5,0,0,0,4,660,5,cabecera
6565,35-39 años,3,0,0,1,8,708,3,cabecera
6566,40-44 años,3,0,0,0,1,624,6,cabecera
6567,45-49 años,5,0,0,0,7,722,2,cabecera
6568,50-54 años,2,0,0,0,6,719,3,cabecera
6569,55-59 años,3,0,0,0,0,683,0,cabecera
6570,60-64 años,3,0,0,0,1,543,2,cabecera
6571,65-69 años,2,0,0,0,3,489,2,cabecera
6572,70-74 años,2,0,0,0,2,370,0,cabecera
6573,75-79 años,0,0,0,0,2,320,0,cabecera
6574,80-84 años,1,0,0,0,1,193,1,cabecera
6575,85 años y más,1,0,0,0,2,156,1,cabecera
6557,Total,0,0,0,0,0,0,0,centro poblado
6558,0-4 años,0,0,0,0,0,0,0,centro poblado
6559,5-9 años,0,0,0,0,0,0,0,centro poblado
6560,10-14 años,0,0,0,0,0,0,0,centro poblado
6561,15-19 años,0,0,0,0,0,0,0,centro poblado
6562,20-24 años,0,0,0,0,0,0,0,centro poblado
6563,25-29 años,0,0,0,0,0,0,0,centro poblado
6564,30-34 años,0,0,0,0,0,0,0,centro poblado
6565,35-39 años,0,0,0,0,0,0,0,centro poblado
6566,40-44 años,0,0,0,0,0,0,0,centro poblado
6567,45-49 años,0,0,0,0,0,0,0,centro poblado
6568,50-54 años,0,0,0,0,0,0,0,centro poblado
6569,55-59 años,0,0,0,0,0,0,0,centro poblado
6570,60-64 años,0,0,0,0,0,0,0,centro poblado
6571,65-69 años,0,0,0,0,0,0,0,centro poblado
6572,70-74 años,0,0,0,0,0,0,0,centro poblado
6573,75-79 años,0,0,0,0,0,0,0,centro poblado
6574,80-84 años,0,0,0,0,0,0,0,centro poblado
6575,85 años y más,0,0,0,0,0,0,0,centro poblado
6557,Total,102,0,0,0,8,1646,5,rural disperso
6558,0-4 años,13,0,0,0,0,84,0,rural disperso
6559,5-9 años,7,0,0,0,0,115,0,rural disperso
6560,10-14 años,16,0,0,0,0,146,0,rural disperso
6561,15-19 años,12,0,0,0,1,174,0,rural disperso
6562,20-24 años,8,0,0,0,1,114,0,rural disperso
6563,25-29 años,10,0,0,0,0,97,0,rural disperso
6564,30-34 años,6,0,0,0,0,99,0,rural disperso
6565,35-39 años,7,0,0,0,0,109,1,rural disperso
6566,40-44 años,6,0,0,0,0,107,0,rural disperso
6567,45-49 años,5,0,0,0,0,110,1,rural disperso
6568,50-54 años,3,0,0,0,0,111,2,rural disperso
6569,55-59 años,0,0,0,0,2,97,0,rural disperso
6570,60-64 años,3,0,0,0,2,95,1,rural disperso
6571,65-69 años,3,0,0,0,0,74,0,rural disperso
6572,70-74 años,0,0,0,0,1,59,0,rural disperso
6573,75-79 años,3,0,0,0,1,26,0,rural disperso
6574,80-84 años,0,0,0,0,0,16,0,rural disperso
6575,85 años y más,0,0,0,0,0,13,0,rural disperso

Se eliminan las filas que contienen resumenes de datos.

In [70]:
df_12pm = df_12pm.loc[df_12pm['Grupo edad'] != 'Total']
df_12pm

,Grupo edad,Indigena,Gitano(a) o Rrom,"Raizal del Archipielago de San Andres, Providencia y Santa Catalina",Palenquero(a) de San Basilio,"Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)",Ningun grupo etnico,Sin informacion,Area
6558,0-4 años,4,0,0,0,10,502,3,cabecera
6559,5-9 años,3,0,0,0,6,610,1,cabecera
6560,10-14 años,5,0,0,0,5,766,3,cabecera
6561,15-19 años,11,0,0,0,12,855,5,cabecera
6562,20-24 años,10,1,0,0,11,804,9,cabecera
6563,25-29 años,7,0,0,0,8,727,6,cabecera
6564,30-34 años,5,0,0,0,4,660,5,cabecera
6565,35-39 años,3,0,0,1,8,708,3,cabecera
6566,40-44 años,3,0,0,0,1,624,6,cabecera
6567,45-49 años,5,0,0,0,7,722,2,cabecera
6568,50-54 años,2,0,0,0,6,719,3,cabecera
6569,55-59 años,3,0,0,0,0,683,0,cabecera
6570,60-64 años,3,0,0,0,1,543,2,cabecera
6571,65-69 años,2,0,0,0,3,489,2,cabecera
6572,70-74 años,2,0,0,0,2,370,0,cabecera
6573,75-79 años,0,0,0,0,2,320,0,cabecera
6574,80-84 años,1,0,0,0,1,193,1,cabecera
6575,85 años y más,1,0,0,0,2,156,1,cabecera
6558,0-4 años,0,0,0,0,0,0,0,centro poblado
6559,5-9 años,0,0,0,0,0,0,0,centro poblado
6560,10-14 años,0,0,0,0,0,0,0,centro poblado
6561,15-19 años,0,0,0,0,0,0,0,centro poblado
6562,20-24 años,0,0,0,0,0,0,0,centro poblado
6563,25-29 años,0,0,0,0,0,0,0,centro poblado
6564,30-34 años,0,0,0,0,0,0,0,centro poblado
6565,35-39 años,0,0,0,0,0,0,0,centro poblado
6566,40-44 años,0,0,0,0,0,0,0,centro poblado
6567,45-49 años,0,0,0,0,0,0,0,centro poblado
6568,50-54 años,0,0,0,0,0,0,0,centro poblado
6569,55-59 años,0,0,0,0,0,0,0,centro poblado
6570,60-64 años,0,0,0,0,0,0,0,centro poblado
6571,65-69 años,0,0,0,0,0,0,0,centro poblado
6572,70-74 años,0,0,0,0,0,0,0,centro poblado
6573,75-79 años,0,0,0,0,0,0,0,centro poblado
6574,80-84 años,0,0,0,0,0,0,0,centro poblado
6575,85 años y más,0,0,0,0,0,0,0,centro poblado
6558,0-4 años,13,0,0,0,0,84,0,rural disperso
6559,5-9 años,7,0,0,0,0,115,0,rural disperso
6560,10-14 años,16,0,0,0,0,146,0,rural disperso
6561,15-19 años,12,0,0,0,1,174,0,rural disperso
6562,20-24 años,8,0,0,0,1,114,0,rural disperso
6563,25-29 años,10,0,0,0,0,97,0,rural disperso
6564,30-34 años,6,0,0,0,0,99,0,rural disperso
6565,35-39 años,7,0,0,0,0,109,1,rural disperso
6566,40-44 años,6,0,0,0,0,107,0,rural disperso
6567,45-49 años,5,0,0,0,0,110,1,rural disperso
6568,50-54 años,3,0,0,0,0,111,2,rural disperso
6569,55-59 años,0,0,0,0,2,97,0,rural disperso
6570,60-64 años,3,0,0,0,2,95,1,rural disperso
6571,65-69 años,3,0,0,0,0,74,0,rural disperso
6572,70-74 años,0,0,0,0,1,59,0,rural disperso
6573,75-79 años,3,0,0,0,1,26,0,rural disperso
6574,80-84 años,0,0,0,0,0,16,0,rural disperso
6575,85 años y más,0,0,0,0,0,13,0,rural disperso

In [71]:
replacements = str.maketrans({'ñ':'ni', 'á':'a'})
df_12pm.loc[:,'Grupo edad'] = df_12pm['Grupo edad'].str.translate(replacements)
df_12pm

,Grupo edad,Indigena,Gitano(a) o Rrom,"Raizal del Archipielago de San Andres, Providencia y Santa Catalina",Palenquero(a) de San Basilio,"Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)",Ningun grupo etnico,Sin informacion,Area
6558,0-4 anios,4,0,0,0,10,502,3,cabecera
6559,5-9 anios,3,0,0,0,6,610,1,cabecera
6560,10-14 anios,5,0,0,0,5,766,3,cabecera
6561,15-19 anios,11,0,0,0,12,855,5,cabecera
6562,20-24 anios,10,1,0,0,11,804,9,cabecera
6563,25-29 anios,7,0,0,0,8,727,6,cabecera
6564,30-34 anios,5,0,0,0,4,660,5,cabecera
6565,35-39 anios,3,0,0,1,8,708,3,cabecera
6566,40-44 anios,3,0,0,0,1,624,6,cabecera
6567,45-49 anios,5,0,0,0,7,722,2,cabecera
6568,50-54 anios,2,0,0,0,6,719,3,cabecera
6569,55-59 anios,3,0,0,0,0,683,0,cabecera
6570,60-64 anios,3,0,0,0,1,543,2,cabecera
6571,65-69 anios,2,0,0,0,3,489,2,cabecera
6572,70-74 anios,2,0,0,0,2,370,0,cabecera
6573,75-79 anios,0,0,0,0,2,320,0,cabecera
6574,80-84 anios,1,0,0,0,1,193,1,cabecera
6575,85 anios y mas,1,0,0,0,2,156,1,cabecera
6558,0-4 anios,0,0,0,0,0,0,0,centro poblado
6559,5-9 anios,0,0,0,0,0,0,0,centro poblado
6560,10-14 anios,0,0,0,0,0,0,0,centro poblado
6561,15-19 anios,0,0,0,0,0,0,0,centro poblado
6562,20-24 anios,0,0,0,0,0,0,0,centro poblado
6563,25-29 anios,0,0,0,0,0,0,0,centro poblado
6564,30-34 anios,0,0,0,0,0,0,0,centro poblado
6565,35-39 anios,0,0,0,0,0,0,0,centro poblado
6566,40-44 anios,0,0,0,0,0,0,0,centro poblado
6567,45-49 anios,0,0,0,0,0,0,0,centro poblado
6568,50-54 anios,0,0,0,0,0,0,0,centro poblado
6569,55-59 anios,0,0,0,0,0,0,0,centro poblado
6570,60-64 anios,0,0,0,0,0,0,0,centro poblado
6571,65-69 anios,0,0,0,0,0,0,0,centro poblado
6572,70-74 anios,0,0,0,0,0,0,0,centro poblado
6573,75-79 anios,0,0,0,0,0,0,0,centro poblado
6574,80-84 anios,0,0,0,0,0,0,0,centro poblado
6575,85 anios y mas,0,0,0,0,0,0,0,centro poblado
6558,0-4 anios,13,0,0,0,0,84,0,rural disperso
6559,5-9 anios,7,0,0,0,0,115,0,rural disperso
6560,10-14 anios,16,0,0,0,0,146,0,rural disperso
6561,15-19 anios,12,0,0,0,1,174,0,rural disperso
6562,20-24 anios,8,0,0,0,1,114,0,rural disperso
6563,25-29 anios,10,0,0,0,0,97,0,rural disperso
6564,30-34 anios,6,0,0,0,0,99,0,rural disperso
6565,35-39 anios,7,0,0,0,0,109,1,rural disperso
6566,40-44 anios,6,0,0,0,0,107,0,rural disperso
6567,45-49 anios,5,0,0,0,0,110,1,rural disperso
6568,50-54 anios,3,0,0,0,0,111,2,rural disperso
6569,55-59 anios,0,0,0,0,2,97,0,rural disperso
6570,60-64 anios,3,0,0,0,2,95,1,rural disperso
6571,65-69 anios,3,0,0,0,0,74,0,rural disperso
6572,70-74 anios,0,0,0,0,1,59,0,rural disperso
6573,75-79 anios,3,0,0,0,1,26,0,rural disperso
6574,80-84 anios,0,0,0,0,0,16,0,rural disperso
6575,85 anios y mas,0,0,0,0,0,13,0,rural disperso

El dataframe está listo para ser exportado a csv.

In [72]:
df_12pm.to_csv(csv_path, index=False)