In [1]:
# imports
import pandas as pd

In [2]:
# Ruta relativa del xslx que contiene los datos
original_data_path = 'Data\\Original\\PERSONAS_DEMOGRAFICO_Cuadros_CNPV_2018.xlsx'

# Nombre del csv objetivo
csv_filename = 'caldas_viterbo_1PM.csv'

# Ruta relativa del csv objetivo
csv_path = 'Data\\Datasets\\' + csv_filename

In [3]:
# Lee archivo xlsx
df_1PM = pd.read_excel(original_data_path, sheet_name='1PM', skiprows=9)
df_1PM.head()

,"Grupos de edad, municipio y áreas (Total, Cabecera y Centros poblados y Rural disperso)",Unnamed: 1,Unnamed: 2,Unnamed: 3,Total,Sexo,Unnamed: 6,Índice de masculinidad,Índice de feminidad
0,NaN,NaN,NaN,NaN,NaN,Hombre,Mujer,NaN,NaN
1,Total Nacional,NaN,Total,Total,44164417.0,21570493,22593924,95.470326,104.744588
2,NaN,NaN,NaN,0 a 4,3037781.0,1555605,1482176,104.954135,95.279714
3,NaN,NaN,NaN,5 a 9,3335240.0,1705574,1629666,104.657887,95.549416
4,NaN,NaN,NaN,10 a 14,3610584.0,1848218,1762366,104.871406,95.354877

In [4]:
list(df_1PM.columns.values)

['Grupos de edad, municipio y áreas  (Total, Cabecera y Centros poblados y Rural disperso) ',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Total',
 'Sexo',
 'Unnamed: 6',
 'Índice de  masculinidad',
 'Índice de  feminidad']

Se reajustan los headers para que sean más descriptivos y para que 'Hombre' y 'Mujer' sean parte de estos.
A simple vista se observa que los headers 'Unnamed: 2' y 'Unnamed: 3' corresponden a Áreas y Grupos de edad respecrivamente. También se eliminarán las tildes de los headers existentes.

In [5]:
df_1PM = df_1PM.rename(columns={'Unnamed: 2': 'Area','Unnamed: 3': 'Grupo de edad','Sexo':'Hombre', 'Unnamed: 6':'Mujer', 
                                'Índice de  masculinidad':'Indice de  masculinidad', 'Índice de  feminidad':'Indice de  feminidad'})
list(df_1PM.columns.values)

['Grupos de edad, municipio y áreas  (Total, Cabecera y Centros poblados y Rural disperso) ',
 'Unnamed: 1',
 'Area',
 'Grupo de edad',
 'Total',
 'Hombre',
 'Mujer',
 'Indice de  masculinidad',
 'Indice de  feminidad']

In [6]:
df_1PM.iloc[24185:24242]

,"Grupos de edad, municipio y áreas (Total, Cabecera y Centros poblados y Rural disperso)",Unnamed: 1,Area,Grupo de edad,Total,Hombre,Mujer,Indice de masculinidad,Indice de feminidad
24185,NaN,17877_Viterbo,Total,Total,12432.0,5889,6543,90.004585,111.105451
24186,NaN,NaN,NaN,0 a 4,620.0,330,290,113.793103,87.878788
24187,NaN,NaN,NaN,5 a 9,742.0,372,370,100.540541,99.462366
24188,NaN,NaN,NaN,10 a 14,941.0,461,480,96.041667,104.121475
24189,NaN,NaN,NaN,15 a 19,1073.0,534,539,99.072356,100.93633
24190,NaN,NaN,NaN,20 a 24,958.0,448,510,87.843137,113.839286
24191,NaN,NaN,NaN,25 a 29,855.0,423,432,97.916667,102.12766
24192,NaN,NaN,NaN,30 a 34,779.0,360,419,85.918854,116.388889
24193,NaN,NaN,NaN,35 a 39,840.0,392,448,87.5,114.285714
24194,NaN,NaN,NaN,40 a 44,747.0,338,409,82.640587,121.005917
24195,NaN,NaN,NaN,45 a 49,852.0,388,464,83.62069,119.587629
24196,NaN,NaN,NaN,50 a 54,846.0,383,463,82.721382,120.887728
24197,NaN,NaN,NaN,55 a 59,785.0,345,440,78.409091,127.536232
24198,NaN,NaN,NaN,60 a 64,650.0,322,328,98.170732,101.863354
24199,NaN,NaN,NaN,65 a 69,573.0,266,307,86.644951,115.413534
24200,NaN,NaN,NaN,70 a 74,434.0,193,241,80.082988,124.870466
24201,NaN,NaN,NaN,75 a 79,352.0,149,203,73.399015,136.241611
24202,NaN,NaN,NaN,80 a 84,212.0,98,114,85.964912,116.326531
24203,NaN,NaN,NaN,85 y más,173.0,87,86,101.162791,98.850575
24204,NaN,NaN,Cabecera,Total,10671.0,4960,5711,86.849939,115.141129
24205,NaN,NaN,NaN,0 a 4,523.0,286,237,120.675105,82.867133
24206,NaN,NaN,NaN,5 a 9,620.0,307,313,98.083067,101.954397
24207,NaN,NaN,NaN,10 a 14,779.0,373,406,91.871921,108.847185
24208,NaN,NaN,NaN,15 a 19,886.0,429,457,93.873085,106.526807
24209,NaN,NaN,NaN,20 a 24,835.0,391,444,88.063063,113.554987
24210,NaN,NaN,NaN,25 a 29,748.0,365,383,95.300261,104.931507
24211,NaN,NaN,NaN,30 a 34,674.0,317,357,88.795518,112.618297
24212,NaN,NaN,NaN,35 a 39,723.0,333,390,85.384615,117.117117
24213,NaN,NaN,NaN,40 a 44,634.0,283,351,80.626781,124.028269
24214,NaN,NaN,NaN,45 a 49,736.0,321,415,77.349398,129.283489
24215,NaN,NaN,NaN,50 a 54,730.0,325,405,80.246914,124.615385
24216,NaN,NaN,NaN,55 a 59,686.0,287,399,71.929825,139.02439
24217,NaN,NaN,NaN,60 a 64,549.0,269,280,96.071429,104.089219
24218,NaN,NaN,NaN,65 a 69,496.0,223,273,81.684982,122.421525
24219,NaN,NaN,NaN,70 a 74,374.0,158,216,73.148148,136.708861
24220,NaN,NaN,NaN,75 a 79,322.0,130,192,67.708333,147.692308
24221,NaN,NaN,NaN,80 a 84,196.0,85,111,76.576577,130.588235
24222,NaN,NaN,NaN,85 y más,160.0,78,82,95.121951,105.128205
24223,NaN,NaN,Rural disperso,Total,1761.0,929,832,111.658654,89.558665
24224,NaN,NaN,NaN,0 a 4,97.0,44,53,83.018868,120.454545
24225,NaN,NaN,NaN,5 a 9,122.0,65,57,114.035088,87.692308
24226,NaN,NaN,NaN,10 a 14,162.0,88,74,118.918919,84.090909
24227,NaN,NaN,NaN,15 a 19,187.0,105,82,128.04878,78.095238
24228,NaN,NaN,NaN,20 a 24,123.0,57,66,86.363636,115.789474
24229,NaN,NaN,NaN,25 a 29,107.0,58,49,118.367347,84.482759
24230,NaN,NaN,NaN,30 a 34,105.0,43,62,69.354839,144.186047
24231,NaN,NaN,NaN,35 a 39,117.0,59,58,101.724138,98.305085
24232,NaN,NaN,NaN,40 a 44,113.0,55,58,94.827586,105.454545
24233,NaN,NaN,NaN,45 a 49,116.0,67,49,136.734694,73.134328
24234,NaN,NaN,NaN,50 a 54,116.0,58,58,100,100
24235,NaN,NaN,NaN,55 a 59,99.0,58,41,141.463415,70.689655
24236,NaN,NaN,NaN,60 a 64,101.0,53,48,110.416667,90.566038
24237,NaN,NaN,NaN,65 a 69,77.0,43,34,126.470588,79.069767
24238,NaN,NaN,NaN,70 a 74,60.0,35,25,140,71.428571
24239,NaN,NaN,NaN,75 a 79,30.0,19,11,172.727273,57.894737
24240,NaN,NaN,NaN,80 a 84,16.0,13,3,433.333333,23.076923
24241,NaN,NaN,NaN,85 y más,13.0,9,4,225,44.444444

Se observa que el header 'Unnamed: 1' corresponde al municipio, y la primera columna no contiene información importante para el dataset, por lo tanto se pueden eliminar.

In [7]:
df_1PM = df_1PM.iloc[24185:24242]
df_1PM = df_1PM.drop(['Grupos de edad, municipio y áreas  (Total, Cabecera y Centros poblados y Rural disperso) ', 'Unnamed: 1'], axis=1)

In [8]:
df_1PM

,Area,Grupo de edad,Total,Hombre,Mujer,Indice de masculinidad,Indice de feminidad
24185,Total,Total,12432.0,5889,6543,90.004585,111.105451
24186,NaN,0 a 4,620.0,330,290,113.793103,87.878788
24187,NaN,5 a 9,742.0,372,370,100.540541,99.462366
24188,NaN,10 a 14,941.0,461,480,96.041667,104.121475
24189,NaN,15 a 19,1073.0,534,539,99.072356,100.93633
24190,NaN,20 a 24,958.0,448,510,87.843137,113.839286
24191,NaN,25 a 29,855.0,423,432,97.916667,102.12766
24192,NaN,30 a 34,779.0,360,419,85.918854,116.388889
24193,NaN,35 a 39,840.0,392,448,87.5,114.285714
24194,NaN,40 a 44,747.0,338,409,82.640587,121.005917
24195,NaN,45 a 49,852.0,388,464,83.62069,119.587629
24196,NaN,50 a 54,846.0,383,463,82.721382,120.887728
24197,NaN,55 a 59,785.0,345,440,78.409091,127.536232
24198,NaN,60 a 64,650.0,322,328,98.170732,101.863354
24199,NaN,65 a 69,573.0,266,307,86.644951,115.413534
24200,NaN,70 a 74,434.0,193,241,80.082988,124.870466
24201,NaN,75 a 79,352.0,149,203,73.399015,136.241611
24202,NaN,80 a 84,212.0,98,114,85.964912,116.326531
24203,NaN,85 y más,173.0,87,86,101.162791,98.850575
24204,Cabecera,Total,10671.0,4960,5711,86.849939,115.141129
24205,NaN,0 a 4,523.0,286,237,120.675105,82.867133
24206,NaN,5 a 9,620.0,307,313,98.083067,101.954397
24207,NaN,10 a 14,779.0,373,406,91.871921,108.847185
24208,NaN,15 a 19,886.0,429,457,93.873085,106.526807
24209,NaN,20 a 24,835.0,391,444,88.063063,113.554987
24210,NaN,25 a 29,748.0,365,383,95.300261,104.931507
24211,NaN,30 a 34,674.0,317,357,88.795518,112.618297
24212,NaN,35 a 39,723.0,333,390,85.384615,117.117117
24213,NaN,40 a 44,634.0,283,351,80.626781,124.028269
24214,NaN,45 a 49,736.0,321,415,77.349398,129.283489
24215,NaN,50 a 54,730.0,325,405,80.246914,124.615385
24216,NaN,55 a 59,686.0,287,399,71.929825,139.02439
24217,NaN,60 a 64,549.0,269,280,96.071429,104.089219
24218,NaN,65 a 69,496.0,223,273,81.684982,122.421525
24219,NaN,70 a 74,374.0,158,216,73.148148,136.708861
24220,NaN,75 a 79,322.0,130,192,67.708333,147.692308
24221,NaN,80 a 84,196.0,85,111,76.576577,130.588235
24222,NaN,85 y más,160.0,78,82,95.121951,105.128205
24223,Rural disperso,Total,1761.0,929,832,111.658654,89.558665
24224,NaN,0 a 4,97.0,44,53,83.018868,120.454545
24225,NaN,5 a 9,122.0,65,57,114.035088,87.692308
24226,NaN,10 a 14,162.0,88,74,118.918919,84.090909
24227,NaN,15 a 19,187.0,105,82,128.04878,78.095238
24228,NaN,20 a 24,123.0,57,66,86.363636,115.789474
24229,NaN,25 a 29,107.0,58,49,118.367347,84.482759
24230,NaN,30 a 34,105.0,43,62,69.354839,144.186047
24231,NaN,35 a 39,117.0,59,58,101.724138,98.305085
24232,NaN,40 a 44,113.0,55,58,94.827586,105.454545
24233,NaN,45 a 49,116.0,67,49,136.734694,73.134328
24234,NaN,50 a 54,116.0,58,58,100,100
24235,NaN,55 a 59,99.0,58,41,141.463415,70.689655
24236,NaN,60 a 64,101.0,53,48,110.416667,90.566038
24237,NaN,65 a 69,77.0,43,34,126.470588,79.069767
24238,NaN,70 a 74,60.0,35,25,140,71.428571
24239,NaN,75 a 79,30.0,19,11,172.727273,57.894737
24240,NaN,80 a 84,16.0,13,3,433.333333,23.076923
24241,NaN,85 y más,13.0,9,4,225,44.444444

Los valores NaN en la columna 'Area' deben ser reemplazados por el primer valor válido de la columna hasta el siguiente valor válido, es decir, propagar el valor hasta encontrar el siguiente.

In [9]:
df_1PM['Area'] = df_1PM['Area'].ffill()
df_1PM

,Area,Grupo de edad,Total,Hombre,Mujer,Indice de masculinidad,Indice de feminidad
24185,Total,Total,12432.0,5889,6543,90.004585,111.105451
24186,Total,0 a 4,620.0,330,290,113.793103,87.878788
24187,Total,5 a 9,742.0,372,370,100.540541,99.462366
24188,Total,10 a 14,941.0,461,480,96.041667,104.121475
24189,Total,15 a 19,1073.0,534,539,99.072356,100.93633
24190,Total,20 a 24,958.0,448,510,87.843137,113.839286
24191,Total,25 a 29,855.0,423,432,97.916667,102.12766
24192,Total,30 a 34,779.0,360,419,85.918854,116.388889
24193,Total,35 a 39,840.0,392,448,87.5,114.285714
24194,Total,40 a 44,747.0,338,409,82.640587,121.005917
24195,Total,45 a 49,852.0,388,464,83.62069,119.587629
24196,Total,50 a 54,846.0,383,463,82.721382,120.887728
24197,Total,55 a 59,785.0,345,440,78.409091,127.536232
24198,Total,60 a 64,650.0,322,328,98.170732,101.863354
24199,Total,65 a 69,573.0,266,307,86.644951,115.413534
24200,Total,70 a 74,434.0,193,241,80.082988,124.870466
24201,Total,75 a 79,352.0,149,203,73.399015,136.241611
24202,Total,80 a 84,212.0,98,114,85.964912,116.326531
24203,Total,85 y más,173.0,87,86,101.162791,98.850575
24204,Cabecera,Total,10671.0,4960,5711,86.849939,115.141129
24205,Cabecera,0 a 4,523.0,286,237,120.675105,82.867133
24206,Cabecera,5 a 9,620.0,307,313,98.083067,101.954397
24207,Cabecera,10 a 14,779.0,373,406,91.871921,108.847185
24208,Cabecera,15 a 19,886.0,429,457,93.873085,106.526807
24209,Cabecera,20 a 24,835.0,391,444,88.063063,113.554987
24210,Cabecera,25 a 29,748.0,365,383,95.300261,104.931507
24211,Cabecera,30 a 34,674.0,317,357,88.795518,112.618297
24212,Cabecera,35 a 39,723.0,333,390,85.384615,117.117117
24213,Cabecera,40 a 44,634.0,283,351,80.626781,124.028269
24214,Cabecera,45 a 49,736.0,321,415,77.349398,129.283489
24215,Cabecera,50 a 54,730.0,325,405,80.246914,124.615385
24216,Cabecera,55 a 59,686.0,287,399,71.929825,139.02439
24217,Cabecera,60 a 64,549.0,269,280,96.071429,104.089219
24218,Cabecera,65 a 69,496.0,223,273,81.684982,122.421525
24219,Cabecera,70 a 74,374.0,158,216,73.148148,136.708861
24220,Cabecera,75 a 79,322.0,130,192,67.708333,147.692308
24221,Cabecera,80 a 84,196.0,85,111,76.576577,130.588235
24222,Cabecera,85 y más,160.0,78,82,95.121951,105.128205
24223,Rural disperso,Total,1761.0,929,832,111.658654,89.558665
24224,Rural disperso,0 a 4,97.0,44,53,83.018868,120.454545
24225,Rural disperso,5 a 9,122.0,65,57,114.035088,87.692308
24226,Rural disperso,10 a 14,162.0,88,74,118.918919,84.090909
24227,Rural disperso,15 a 19,187.0,105,82,128.04878,78.095238
24228,Rural disperso,20 a 24,123.0,57,66,86.363636,115.789474
24229,Rural disperso,25 a 29,107.0,58,49,118.367347,84.482759
24230,Rural disperso,30 a 34,105.0,43,62,69.354839,144.186047
24231,Rural disperso,35 a 39,117.0,59,58,101.724138,98.305085
24232,Rural disperso,40 a 44,113.0,55,58,94.827586,105.454545
24233,Rural disperso,45 a 49,116.0,67,49,136.734694,73.134328
24234,Rural disperso,50 a 54,116.0,58,58,100,100
24235,Rural disperso,55 a 59,99.0,58,41,141.463415,70.689655
24236,Rural disperso,60 a 64,101.0,53,48,110.416667,90.566038
24237,Rural disperso,65 a 69,77.0,43,34,126.470588,79.069767
24238,Rural disperso,70 a 74,60.0,35,25,140,71.428571
24239,Rural disperso,75 a 79,30.0,19,11,172.727273,57.894737
24240,Rural disperso,80 a 84,16.0,13,3,433.333333,23.076923
24241,Rural disperso,85 y más,13.0,9,4,225,44.444444

Se reemplazarán las tildes del contenido, en este caso específico, solo la columna 'Grupo de edad contiene datos con tildes.

In [10]:
df_1PM['Grupo de edad'] = df_1PM['Grupo de edad'].str.replace('á', 'a')
df_1PM

,Area,Grupo de edad,Total,Hombre,Mujer,Indice de masculinidad,Indice de feminidad
24185,Total,Total,12432.0,5889,6543,90.004585,111.105451
24186,Total,0 a 4,620.0,330,290,113.793103,87.878788
24187,Total,5 a 9,742.0,372,370,100.540541,99.462366
24188,Total,10 a 14,941.0,461,480,96.041667,104.121475
24189,Total,15 a 19,1073.0,534,539,99.072356,100.93633
24190,Total,20 a 24,958.0,448,510,87.843137,113.839286
24191,Total,25 a 29,855.0,423,432,97.916667,102.12766
24192,Total,30 a 34,779.0,360,419,85.918854,116.388889
24193,Total,35 a 39,840.0,392,448,87.5,114.285714
24194,Total,40 a 44,747.0,338,409,82.640587,121.005917
24195,Total,45 a 49,852.0,388,464,83.62069,119.587629
24196,Total,50 a 54,846.0,383,463,82.721382,120.887728
24197,Total,55 a 59,785.0,345,440,78.409091,127.536232
24198,Total,60 a 64,650.0,322,328,98.170732,101.863354
24199,Total,65 a 69,573.0,266,307,86.644951,115.413534
24200,Total,70 a 74,434.0,193,241,80.082988,124.870466
24201,Total,75 a 79,352.0,149,203,73.399015,136.241611
24202,Total,80 a 84,212.0,98,114,85.964912,116.326531
24203,Total,85 y mas,173.0,87,86,101.162791,98.850575
24204,Cabecera,Total,10671.0,4960,5711,86.849939,115.141129
24205,Cabecera,0 a 4,523.0,286,237,120.675105,82.867133
24206,Cabecera,5 a 9,620.0,307,313,98.083067,101.954397
24207,Cabecera,10 a 14,779.0,373,406,91.871921,108.847185
24208,Cabecera,15 a 19,886.0,429,457,93.873085,106.526807
24209,Cabecera,20 a 24,835.0,391,444,88.063063,113.554987
24210,Cabecera,25 a 29,748.0,365,383,95.300261,104.931507
24211,Cabecera,30 a 34,674.0,317,357,88.795518,112.618297
24212,Cabecera,35 a 39,723.0,333,390,85.384615,117.117117
24213,Cabecera,40 a 44,634.0,283,351,80.626781,124.028269
24214,Cabecera,45 a 49,736.0,321,415,77.349398,129.283489
24215,Cabecera,50 a 54,730.0,325,405,80.246914,124.615385
24216,Cabecera,55 a 59,686.0,287,399,71.929825,139.02439
24217,Cabecera,60 a 64,549.0,269,280,96.071429,104.089219
24218,Cabecera,65 a 69,496.0,223,273,81.684982,122.421525
24219,Cabecera,70 a 74,374.0,158,216,73.148148,136.708861
24220,Cabecera,75 a 79,322.0,130,192,67.708333,147.692308
24221,Cabecera,80 a 84,196.0,85,111,76.576577,130.588235
24222,Cabecera,85 y mas,160.0,78,82,95.121951,105.128205
24223,Rural disperso,Total,1761.0,929,832,111.658654,89.558665
24224,Rural disperso,0 a 4,97.0,44,53,83.018868,120.454545
24225,Rural disperso,5 a 9,122.0,65,57,114.035088,87.692308
24226,Rural disperso,10 a 14,162.0,88,74,118.918919,84.090909
24227,Rural disperso,15 a 19,187.0,105,82,128.04878,78.095238
24228,Rural disperso,20 a 24,123.0,57,66,86.363636,115.789474
24229,Rural disperso,25 a 29,107.0,58,49,118.367347,84.482759
24230,Rural disperso,30 a 34,105.0,43,62,69.354839,144.186047
24231,Rural disperso,35 a 39,117.0,59,58,101.724138,98.305085
24232,Rural disperso,40 a 44,113.0,55,58,94.827586,105.454545
24233,Rural disperso,45 a 49,116.0,67,49,136.734694,73.134328
24234,Rural disperso,50 a 54,116.0,58,58,100,100
24235,Rural disperso,55 a 59,99.0,58,41,141.463415,70.689655
24236,Rural disperso,60 a 64,101.0,53,48,110.416667,90.566038
24237,Rural disperso,65 a 69,77.0,43,34,126.470588,79.069767
24238,Rural disperso,70 a 74,60.0,35,25,140,71.428571
24239,Rural disperso,75 a 79,30.0,19,11,172.727273,57.894737
24240,Rural disperso,80 a 84,16.0,13,3,433.333333,23.076923
24241,Rural disperso,85 y mas,13.0,9,4,225,44.444444

El DataFrame está listo para ser exportado a csv

In [11]:
df_1PM.to_csv(csv_path, index=False)