In [1]:
# imports
import pandas as pd

In [2]:
# Ruta relativa del xslx que contiene los datos
original_data_path = 'Data\\Original\\PERSONAS_DEMOGRAFICO_Cuadros_CNPV_2018.xlsx'

# Nombre del csv objetivo
csv_filename = 'caldas_viterbo_13PM.csv'

# Ruta relativa del csv objetivo
csv_path = 'Data\\Datasets\\' + csv_filename

In [19]:
# Lee archivo xlsx
df_13pm = pd.read_excel(original_data_path, sheet_name='13PM', skiprows=9)
df_13pm.head()

,Departamento y grupos de edad,Unnamed: 1,Unnamed: 2,Total,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Rural disperso,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
0,NaN,NaN,NaN,Total,Indígena,Gitano(a) o Rrom,"Raizal del Archipielago de San Andrés, Provide...",Palenquero(a) de San Basilio,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",Ningún grupo étnico,...,Sin información,NaN,Total,Indígena,Gitano(a) o Rrom,"Raizal del Archipielago de San Andrés, Provide...",Palenquero(a) de San Basilio,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",Ningún grupo étnico,Sin información
1,Total Nacional,NaN,Total,43835324,1876752,2606,25344,6635,2942859,38459411,...,22264,NaN,6808647,1261154,169,1099,374,421506,5044245,80100
2,NaN,NaN,Territorio no étnico,42426844,835823,2549,25227,4062,2675951,38402939,...,16679,NaN,5618503,315126,120,1013,222,252075,5005686,44261
3,NaN,NaN,Resguardo indígena,1092280,1021612,48,59,24,6643,42103,...,977,NaN,988381,928764,43,56,20,5451,33233,20814
4,NaN,NaN,Territorio CCN,316200,19317,9,58,2549,260265,14369,...,4608,NaN,201763,17264,6,30,132,163980,5326,15025

Ya que las columnas están agrupadas por área, y es necesario modificar los headers, se extraerán los headers correctos en una lista y se utilizarán apra modificar los headers actuales en un paso futuro cuando se tengan conjuntos de datos más reducidos.

In [20]:
first_row = list(df_13pm.iloc[0])[:]
for (i, value) in enumerate(first_row):
    print(i, value)

0 nan
1 nan
2 nan
3 Total
4 Indígena
5 Gitano(a) o Rrom
6 Raizal del Archipielago de San Andrés, Providencia y Santa Catalina
7 Palenquero(a) de San Basilio
8 Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)
9 Ningún grupo étnico
10 Sin información
11 nan
12 Total
13 Indígena
14 Gitano(a) o Rrom
15 Raizal del Archipielago de San Andrés, Providencia y Santa Catalina
16 Palenquero(a) de San Basilio
17 Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)
18 Ningún grupo étnico
19 Sin información
20 nan
21 Total
22 Indígena
23 Gitano(a) o Rrom
24 Raizal del Archipielago de San Andrés, Providencia y Santa Catalina
25 Palenquero(a) de San Basilio
26 Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)
27 Ningún grupo étnico
28 Sin información
29 nan
30 Total
31 Indígena
32 Gitano(a) o Rrom
33 Raizal del Archipielago de San Andrés, Providencia y Santa Catalina
34 Palenquero(a) de San Basilio
35 Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)
36 Ningún grupo étnico
37 Sin información

In [21]:
actual_headers = list(df_13pm.iloc[0][4:11])
actual_headers

['Indígena',
 'Gitano(a) o Rrom',
 'Raizal del Archipielago de San Andrés, Providencia y Santa Catalina',
 'Palenquero(a) de San Basilio',
 'Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)',
 'Ningún grupo étnico',
 'Sin información']

Se filtrarán los datos que no corresponden al municipio de Viterbo Caldas, para ello se propagará el municipio, el cual se encuentra en la columna "Unnamed: 1" y se seleccionarán solo los registros que contengan el identificador de Viterbo dentro del dataframe, para este caso es "17877_Viterbo".

In [22]:
df_13pm['Unnamed: 1'] = df_13pm['Unnamed: 1'].ffill()
df_13pm = df_13pm.loc[df_13pm['Unnamed: 1'] == '17877_Viterbo']
df_13pm

,Departamento y grupos de edad,Unnamed: 1,Unnamed: 2,Total,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Rural disperso,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
738,NaN,17877_Viterbo,Total,12425,172,1,0,1,97,12097,...,0,NaN,1761,102,0,0,0,8,1646,5
739,NaN,17877_Viterbo,Territorio no étnico,12413,160,1,0,1,97,12097,...,0,NaN,1749,90,0,0,0,8,1646,5
740,NaN,17877_Viterbo,Resguardo indígena,12,12,0,0,0,0,0,...,0,NaN,12,12,0,0,0,0,0,0

Debido a la agrupación de columnas por área, se separan los datos por subconjuntos dependiendo del área y al final serán reunidos en un mismo dataframe con el área presente en las filas, se eliminan columnas con resumenes de datos, aka totales.

In [23]:
ls_df = []
df_13pm_territorio_etnico = df_13pm['Unnamed: 2']
df_13pm_cabecera = pd.concat([df_13pm_territorio_etnico, df_13pm.iloc[:,13:20].assign(Area='cabecera')], axis=1)
ls_df.append(df_13pm_cabecera)
df_13pm_centros_poblados = pd.concat([df_13pm_territorio_etnico, df_13pm.iloc[:,22:29].assign(Area='centro_poblado')], axis=1)
ls_df.append(df_13pm_centros_poblados)
df_13pm_rural_disperso = pd.concat([df_13pm_territorio_etnico, df_13pm.iloc[:,31:].assign(Area='rural_disperso')], axis=1)
ls_df.append(df_13pm_rural_disperso)
for df in ls_df:
    df.rename(columns={'Unnamed: 2':'Territorio etnico'}, inplace=True)
    df.rename(columns=dict(zip(list(df.columns.values[1:-1]), actual_headers[:])), inplace=True)
df_13pm = pd.concat(ls_df)
df_13pm

,Territorio etnico,Indígena,Gitano(a) o Rrom,"Raizal del Archipielago de San Andrés, Providencia y Santa Catalina",Palenquero(a) de San Basilio,"Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)",Ningún grupo étnico,Sin información,Area
738,Total,70,1,0,1,89,10451,52,cabecera
739,Territorio no étnico,70,1,0,1,89,10451,52,cabecera
740,Resguardo indígena,0,0,0,0,0,0,0,cabecera
738,Total,0,0,0,0,0,0,0,centro_poblado
739,Territorio no étnico,0,0,0,0,0,0,0,centro_poblado
740,Resguardo indígena,0,0,0,0,0,0,0,centro_poblado
738,Total,102,0,0,0,8,1646,5,rural_disperso
739,Territorio no étnico,90,0,0,0,8,1646,5,rural_disperso
740,Resguardo indígena,12,0,0,0,0,0,0,rural_disperso

Se renombran los headers que tienen tildes y ñ.

In [24]:
df_13pm = df_13pm.rename(columns={'Indígena':'Indigena', 
                        'Raizal del Archipielago de San Andrés, Providencia y Santa Catalina':'Raizal del Archipielago de San Andres, Providencia y Santa Catalina', 
                        'Ningún grupo étnico':'Ningun grupo etnico',
                        'Sin información':'Sin informacion'})
df_13pm

,Territorio etnico,Indigena,Gitano(a) o Rrom,"Raizal del Archipielago de San Andres, Providencia y Santa Catalina",Palenquero(a) de San Basilio,"Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)",Ningun grupo etnico,Sin informacion,Area
738,Total,70,1,0,1,89,10451,52,cabecera
739,Territorio no étnico,70,1,0,1,89,10451,52,cabecera
740,Resguardo indígena,0,0,0,0,0,0,0,cabecera
738,Total,0,0,0,0,0,0,0,centro_poblado
739,Territorio no étnico,0,0,0,0,0,0,0,centro_poblado
740,Resguardo indígena,0,0,0,0,0,0,0,centro_poblado
738,Total,102,0,0,0,8,1646,5,rural_disperso
739,Territorio no étnico,90,0,0,0,8,1646,5,rural_disperso
740,Resguardo indígena,12,0,0,0,0,0,0,rural_disperso

Se eliminan las filas que contienen resumenes de datos.

In [25]:
df_13pm = df_13pm.loc[df_13pm['Territorio etnico'] != 'Total']
df_13pm

,Territorio etnico,Indigena,Gitano(a) o Rrom,"Raizal del Archipielago de San Andres, Providencia y Santa Catalina",Palenquero(a) de San Basilio,"Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)",Ningun grupo etnico,Sin informacion,Area
739,Territorio no étnico,70,1,0,1,89,10451,52,cabecera
740,Resguardo indígena,0,0,0,0,0,0,0,cabecera
739,Territorio no étnico,0,0,0,0,0,0,0,centro_poblado
740,Resguardo indígena,0,0,0,0,0,0,0,centro_poblado
739,Territorio no étnico,90,0,0,0,8,1646,5,rural_disperso
740,Resguardo indígena,12,0,0,0,0,0,0,rural_disperso

In [26]:
replacements = str.maketrans({'é':'e', 'í':'i'})
df_13pm.loc[:,'Territorio etnico'] = df_13pm['Territorio etnico'].str.translate(replacements)
df_13pm

,Territorio etnico,Indigena,Gitano(a) o Rrom,"Raizal del Archipielago de San Andres, Providencia y Santa Catalina",Palenquero(a) de San Basilio,"Negro(a), Mulato(a), Afrodescendiente, Afrocolombiano(a)",Ningun grupo etnico,Sin informacion,Area
739,Territorio no etnico,70,1,0,1,89,10451,52,cabecera
740,Resguardo indigena,0,0,0,0,0,0,0,cabecera
739,Territorio no etnico,0,0,0,0,0,0,0,centro_poblado
740,Resguardo indigena,0,0,0,0,0,0,0,centro_poblado
739,Territorio no etnico,90,0,0,0,8,1646,5,rural_disperso
740,Resguardo indigena,12,0,0,0,0,0,0,rural_disperso

El dataframe está listo para ser exportado a csv.

In [27]:
df_13pm.to_csv(csv_path, index=False)