In [12]:
# imports
import pandas as pd # type: ignore

In [13]:
# Ruta relativa del xslx que contiene los datos
data_path = 'Data\\Original\\PERSONAS_DEMOGRAFICO_Cuadros_CNPV_2018.xlsx'

# Nombre del csv objetivo
csv_filename = 'caldas_viterbo_3PM.csv'

# Ruta relativa del csv objetivo
csv_path = 'Data\\Datasets\\' + csv_filename

In [14]:
# Lee archivo xlsx
df_3pm = pd.read_excel(data_path, sheet_name='3PM', skiprows=9)
df_3pm.head()

,Muniicpios y edades simples,Unnamed: 1,Unnamed: 2,Unnamed: 3,Total,Sexo,Unnamed: 6,Cabecera,Unnamed: 8,Unnamed: 9,Centro Poblado,Unnamed: 11,Unnamed: 12,Rural disperso,Unnamed: 14,Unnamed: 15
0,NaN,NaN,NaN,NaN,NaN,Hombre,Mujer,Total,Hombre,Mujer,Total,Hombre,Mujer,Total,Hombre,Mujer
1,Total,NaN,0 a 4,0,560377.0,286536,273841,410654,210110,200544,47548,24335,23213,102175,52091,50084
2,NaN,NaN,NaN,1,602549.0,308380,294169,438701,224544,214157,50452,25911,24541,113396,57925,55471
3,NaN,NaN,NaN,2,621308.0,318301,303007,455649,233499,222150,51122,26232,24890,114537,58570,55967
4,NaN,NaN,NaN,3,626208.0,320496,305712,458882,234641,224241,51264,26222,25042,116062,59633,56429

In [15]:
list(df_3pm.columns.values)

['Muniicpios y edades simples',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Total',
 'Sexo',
 'Unnamed: 6',
 'Cabecera',
 'Unnamed: 8',
 'Unnamed: 9',
 'Centro Poblado',
 'Unnamed: 11',
 'Unnamed: 12',
 'Rural disperso',
 'Unnamed: 14',
 'Unnamed: 15']

Se filtrarán los datos que no corresponden al municipio de Viterbo Caldas, para ello se propagará el municipio, el cual se encuentra en la columna "Unnamed: 1" y se seleccionarán solo los registros que contengan el identificador de Viterbo dentro del dataframe, para este caso es "17877_Viterbo".

In [16]:
df_3pm['Unnamed: 1'] = df_3pm['Unnamed: 1'].ffill()
df_3pm = df_3pm[df_3pm['Unnamed: 1'] == '17877_Viterbo']
df_3pm

,Muniicpios y edades simples,Unnamed: 1,Unnamed: 2,Unnamed: 3,Total,Sexo,Unnamed: 6,Cabecera,Unnamed: 8,Unnamed: 9,Centro Poblado,Unnamed: 11,Unnamed: 12,Rural disperso,Unnamed: 14,Unnamed: 15
42474,NaN,17877_Viterbo,0 a 4,0,119.0,63,56,95,53,42,0,0,0,24,10,14
42475,NaN,17877_Viterbo,NaN,1,120.0,60,60,101,48,53,0,0,0,19,12,7
42476,NaN,17877_Viterbo,NaN,2,133.0,72,61,117,65,52,0,0,0,16,7,9
42477,NaN,17877_Viterbo,NaN,3,120.0,65,55,104,59,45,0,0,0,16,6,10
42478,NaN,17877_Viterbo,NaN,4,128.0,70,58,106,61,45,0,0,0,22,9,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42592,NaN,17877_Viterbo,NaN,Total grupo edad,8.0,4,4,8,4,4,0,0,0,0,0,0
42593,NaN,17877_Viterbo,100 a 104,101,2.0,1,1,2,1,1,0,0,0,0,0,0
42594,NaN,17877_Viterbo,NaN,102,1.0,0,1,1,0,1,0,0,0,0,0,0
42595,NaN,17877_Viterbo,NaN,103,1.0,0,1,1,0,1,0,0,0,0,0,0
42596,NaN,17877_Viterbo,NaN,Total grupo edad,4.0,1,3,4,1,3,0,0,0,0,0,0

Se elimina la primera columna ya que no tiene información relevante.

In [17]:
df_3pm = df_3pm.drop(['Muniicpios y edades simples'], axis=1)
df_3pm

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Total,Sexo,Unnamed: 6,Cabecera,Unnamed: 8,Unnamed: 9,Centro Poblado,Unnamed: 11,Unnamed: 12,Rural disperso,Unnamed: 14,Unnamed: 15
42474,17877_Viterbo,0 a 4,0,119.0,63,56,95,53,42,0,0,0,24,10,14
42475,17877_Viterbo,NaN,1,120.0,60,60,101,48,53,0,0,0,19,12,7
42476,17877_Viterbo,NaN,2,133.0,72,61,117,65,52,0,0,0,16,7,9
42477,17877_Viterbo,NaN,3,120.0,65,55,104,59,45,0,0,0,16,6,10
42478,17877_Viterbo,NaN,4,128.0,70,58,106,61,45,0,0,0,22,9,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42592,17877_Viterbo,NaN,Total grupo edad,8.0,4,4,8,4,4,0,0,0,0,0,0
42593,17877_Viterbo,100 a 104,101,2.0,1,1,2,1,1,0,0,0,0,0,0
42594,17877_Viterbo,NaN,102,1.0,0,1,1,0,1,0,0,0,0,0,0
42595,17877_Viterbo,NaN,103,1.0,0,1,1,0,1,0,0,0,0,0,0
42596,17877_Viterbo,NaN,Total grupo edad,4.0,1,3,4,1,3,0,0,0,0,0,0

Debido a la agrupación de columnas por área, se separan los datos por subconjuntos dependiendo del área y al final serán reunidos en un mismo dataframe con el área presente en las filas, se eliminan columnas con resumenes de datos, aka totales.

In [18]:
df_3pm_cabecera = df_3pm[['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 8', 'Unnamed: 9']]
df_3pm_centro_poblado = df_3pm[['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 11', 'Unnamed: 12']]
df_3pm_rural_disperso = df_3pm[['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 14', 'Unnamed: 15']]

Ahora que se tienen los grupos individualizados, es necesario cambiar el nombre de las columnas. La primera columna corresponde al grupo de edad y se filtrará ya que contiene resumenes de datos que pueden ser alcanzados mediante la exploración del dataset, la segunda a la edad específica y se denominará 'Edad', en la columna que contiene el tipo de área se muestra el resumen del grupo de datos y se denominará 'Total', las últimas dos columnas corresponden a los datos de hombres y mujeres respectivamente y se denominarán 'Hombre' y 'Mujer' respectivamente.

In [19]:
df_3pm_cabecera = df_3pm_cabecera.drop(['Unnamed: 2'], axis=1)
df_3pm_centro_poblado = df_3pm_centro_poblado.drop(['Unnamed: 2'], axis=1)
df_3pm_rural_disperso = df_3pm_rural_disperso.drop(['Unnamed: 2'], axis=1)

In [20]:
df_3pm_cabecera = df_3pm_cabecera.rename(columns={'Unnamed: 3': 'Edad', 'Unnamed: 8': 'Hombre', 'Unnamed: 9': 'Mujer'})
df_3pm_centro_poblado = df_3pm_centro_poblado.rename(columns={'Unnamed: 3': 'Edad', 'Unnamed: 11': 'Hombre', 'Unnamed: 12': 'Mujer'})
df_3pm_rural_disperso = df_3pm_rural_disperso.rename(columns={'Unnamed: 3': 'Edad', 'Unnamed: 14': 'Hombre', 'Unnamed: 15': 'Mujer'})
print(list(df_3pm_cabecera.columns.values), list(df_3pm_centro_poblado.columns.values), list(df_3pm_rural_disperso.columns.values))

['Edad', 'Hombre', 'Mujer'] ['Edad', 'Hombre', 'Mujer'] ['Edad', 'Hombre', 'Mujer']

In [21]:
df_3pm_cabecera = df_3pm_cabecera.assign(Area='cabecera')
df_3pm_centro_poblado = df_3pm_centro_poblado.assign(Area='centro poblado')
df_3pm_rural_disperso = df_3pm_rural_disperso.assign(Area='rural disperso')
print(list(df_3pm_cabecera.columns.values), list(df_3pm_centro_poblado.columns.values), list(df_3pm_rural_disperso.columns.values))

['Edad', 'Hombre', 'Mujer', 'Area'] ['Edad', 'Hombre', 'Mujer', 'Area'] ['Edad', 'Hombre', 'Mujer', 'Area']

In [22]:
df_3pm = pd.concat([df_3pm_cabecera, df_3pm_centro_poblado, df_3pm_rural_disperso], axis=0, ignore_index=True)
df_3pm

                 Edad Hombre Mujer            Area
0                   0     53    42        cabecera
1                   1     48    53        cabecera
2                   2     65    52        cabecera
3                   3     59    45        cabecera
4                   4     61    45        cabecera
..                ...    ...   ...             ...
364  Total grupo edad      0     0  rural disperso
365               101      0     0  rural disperso
366               102      0     0  rural disperso
367               103      0     0  rural disperso
368  Total grupo edad      0     0  rural disperso

[369 rows x 4 columns]

Se eliminan filas con resumenes de datos.

In [24]:
df_3pm = df_3pm.loc[df_3pm['Edad'] != 'Total grupo edad']
df_3pm

    Edad Hombre Mujer            Area
0      0     53    42        cabecera
1      1     48    53        cabecera
2      2     65    52        cabecera
3      3     59    45        cabecera
4      4     61    45        cabecera
..   ...    ...   ...             ...
362   97      0     0  rural disperso
363   98      0     0  rural disperso
365  101      0     0  rural disperso
366  102      0     0  rural disperso
367  103      0     0  rural disperso

[306 rows x 4 columns]

El dataframe está listo para ser exportado a csv

In [25]:
df_3pm.to_csv(csv_path, index=False)