In [1]:
# imports
import pandas as pd

In [14]:
# Ruta relativa del xslx que contiene los datos
original_data_path = 'Data\\Original\\PERSONAS_DEMOGRAFICO_Cuadros_CNPV_2018.xlsx'

# Nombre del csv objetivo
csv_total_filename = 'caldas_viterbo_total_5_1PM.csv'
csv_filename = 'caldas_viterbo_5_1PM.csv'

# Ruta relativa del csv objetivo
csv_total_path = 'Data\\Datasets\\' + csv_total_filename
csv_path = 'Data\\Datasets\\' + csv_filename

In [3]:
# Lee archivo xlsx
df_5_1pm = pd.read_excel(original_data_path, sheet_name='5.1PM', skiprows=9)
df_5_1pm.head()

,"Grupos de edad y áreas (Total, Cabecera y Centros poblados y Rural disperso) y",Unnamed: 1,Unnamed: 2,Unnamed: 3,Total,Relación o parentesco con el Jefe(a) del hogar,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,NaN,NaN,NaN,NaN,NaN,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
1,Total Nacional,NaN,Total,Total,43835324.0,14243223,7562979,15194806,811145,386171,...,24573,195901,782684,17996,188590,2139901,35640,1029584,50822,551032
2,NaN,NaN,NaN,0 a 4,3033307.0,0,0,2244046,44629,0,...,0,0,2905,255,564,599569,0,106573,0,34766
3,NaN,NaN,NaN,5 a 9,3319877.0,0,0,2505535,154903,0,...,0,0,8899,523,1701,515454,0,101513,0,31349
4,NaN,NaN,NaN,10 a 14,3579469.0,12358,7679,2739427,224491,1368,...,2383,0,23292,1055,5847,419365,0,109367,93,32744

Se observa que los headers se encuentran en la primera fila, para ellos se creará un diccionario con el nombre actual de la columna como llave y el nombre correspondiente de la primera fila como valor, para luego reemplazarlos.

In [4]:
df_new_headers = {}
current_headers = list(df_5_1pm.columns.values)[5:]
actual_headers = list(df_5_1pm.iloc[0])[5:]

for key, value in zip(current_headers, actual_headers):
    df_new_headers[key] = value

df_5_1pm = df_5_1pm.rename(columns=df_new_headers)
df_5_1pm

,"Grupos de edad y áreas (Total, Cabecera y Centros poblados y Rural disperso) y",Unnamed: 1,Unnamed: 2,Unnamed: 3,Total,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
0,NaN,NaN,NaN,NaN,NaN,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
1,Total Nacional,NaN,Total,Total,43835324.0,14243223,7562979,15194806,811145,386171,...,24573,195901,782684,17996,188590,2139901,35640,1029584,50822,551032
2,NaN,NaN,NaN,0 a 4,3033307.0,0,0,2244046,44629,0,...,0,0,2905,255,564,599569,0,106573,0,34766
3,NaN,NaN,NaN,5 a 9,3319877.0,0,0,2505535,154903,0,...,0,0,8899,523,1701,515454,0,101513,0,31349
4,NaN,NaN,NaN,10 a 14,3579469.0,12358,7679,2739427,224491,1368,...,2383,0,23292,1055,5847,419365,0,109367,93,32744
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80980,NaN,NaN,NaN,75 a 79,198.0,131,26,0,0,0,...,0,10,1,0,0,0,3,5,0,0
80981,NaN,NaN,NaN,80 a 84,129.0,83,12,0,0,0,...,1,9,0,0,0,0,12,0,0,1
80982,NaN,NaN,NaN,85 y más,77.0,35,11,0,0,0,...,1,6,1,0,2,0,6,5,0,0
80983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80984,Fuente: DANE - Censo Nacional de Población y V...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Se cambian los nombres de las columnas restantes por nombres más descriptivos.

In [5]:
df_5_1pm = df_5_1pm.rename(columns={'Unnamed: 1':'Municipio', 'Unnamed: 2':'Area', 'Unnamed: 3':'Grupo de edad'})
df_5_1pm

,"Grupos de edad y áreas (Total, Cabecera y Centros poblados y Rural disperso) y",Municipio,Area,Grupo de edad,Total,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
0,NaN,NaN,NaN,NaN,NaN,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
1,Total Nacional,NaN,Total,Total,43835324.0,14243223,7562979,15194806,811145,386171,...,24573,195901,782684,17996,188590,2139901,35640,1029584,50822,551032
2,NaN,NaN,NaN,0 a 4,3033307.0,0,0,2244046,44629,0,...,0,0,2905,255,564,599569,0,106573,0,34766
3,NaN,NaN,NaN,5 a 9,3319877.0,0,0,2505535,154903,0,...,0,0,8899,523,1701,515454,0,101513,0,31349
4,NaN,NaN,NaN,10 a 14,3579469.0,12358,7679,2739427,224491,1368,...,2383,0,23292,1055,5847,419365,0,109367,93,32744
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80980,NaN,NaN,NaN,75 a 79,198.0,131,26,0,0,0,...,0,10,1,0,0,0,3,5,0,0
80981,NaN,NaN,NaN,80 a 84,129.0,83,12,0,0,0,...,1,9,0,0,0,0,12,0,0,1
80982,NaN,NaN,NaN,85 y más,77.0,35,11,0,0,0,...,1,6,1,0,2,0,6,5,0,0
80983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80984,Fuente: DANE - Censo Nacional de Población y V...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Se propagan los identificadores de municipio para filtrar los datos que no corresponden a Viterbo, Caldas.

In [6]:
df_5_1pm['Municipio'] = df_5_1pm['Municipio'].ffill()
df_5_1pm = df_5_1pm.loc[df_5_1pm['Municipio'] == '17877_Viterbo']
df_5_1pm

,"Grupos de edad y áreas (Total, Cabecera y Centros poblados y Rural disperso) y",Municipio,Area,Grupo de edad,Total,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
24185,NaN,17877_Viterbo,Total,Total,12425.0,4069,2102,3703,347,133,...,11,77,315,7,95,785,10,325,6,229
24186,NaN,17877_Viterbo,NaN,0 a 4,616.0,0,0,366,13,0,...,0,0,0,0,0,178,0,32,0,27
24187,NaN,17877_Viterbo,NaN,5 a 9,742.0,0,0,448,49,0,...,0,0,0,0,0,195,0,33,0,17
24188,NaN,17877_Viterbo,NaN,10 a 14,941.0,1,1,603,92,0,...,2,0,2,0,1,177,0,42,0,20
24189,NaN,17877_Viterbo,NaN,15 a 19,1070.0,21,31,692,91,18,...,4,0,6,2,6,122,0,51,0,26
24190,NaN,17877_Viterbo,NaN,20 a 24,958.0,125,118,488,56,20,...,0,0,16,1,12,78,0,23,0,21
24191,NaN,17877_Viterbo,NaN,25 a 29,855.0,225,175,340,21,22,...,0,0,12,0,4,20,0,25,0,11
24192,NaN,17877_Viterbo,NaN,30 a 34,779.0,278,215,192,13,19,...,2,0,15,0,7,6,0,16,2,14
24193,NaN,17877_Viterbo,NaN,35 a 39,840.0,370,212,178,5,12,...,0,1,11,0,13,8,0,17,0,12
24194,NaN,17877_Viterbo,NaN,40 a 44,747.0,332,231,121,4,14,...,0,0,14,0,7,1,0,11,0,9
24195,NaN,17877_Viterbo,NaN,45 a 49,852.0,437,229,116,0,8,...,0,4,24,1,6,0,0,11,2,6
24196,NaN,17877_Viterbo,NaN,50 a 54,846.0,451,254,71,2,7,...,0,3,22,2,5,0,1,8,1,8
24197,NaN,17877_Viterbo,NaN,55 a 59,785.0,437,199,55,1,5,...,0,13,40,0,3,0,0,8,0,11
24198,NaN,17877_Viterbo,NaN,60 a 64,650.0,347,166,20,0,3,...,0,5,52,0,15,0,1,7,1,16
24199,NaN,17877_Viterbo,NaN,65 a 69,573.0,332,122,12,0,4,...,0,9,33,0,5,0,0,13,0,7
24200,NaN,17877_Viterbo,NaN,70 a 74,434.0,267,69,1,0,0,...,1,11,34,0,4,0,0,9,0,5
24201,NaN,17877_Viterbo,NaN,75 a 79,352.0,223,48,0,0,1,...,2,11,16,0,4,0,3,7,0,7
24202,NaN,17877_Viterbo,NaN,80 a 84,212.0,127,20,0,0,0,...,0,13,13,1,0,0,2,4,0,6
24203,NaN,17877_Viterbo,NaN,85 y más,173.0,96,12,0,0,0,...,0,7,5,0,3,0,3,8,0,6
24204,NaN,17877_Viterbo,Cabecera,Total,10664.0,3544,1729,3176,280,115,...,5,65,289,4,76,710,10,276,3,192
24205,NaN,17877_Viterbo,NaN,0 a 4,519.0,0,0,301,10,0,...,0,0,0,0,0,157,0,29,0,22
24206,NaN,17877_Viterbo,NaN,5 a 9,620.0,0,0,373,35,0,...,0,0,0,0,0,174,0,24,0,14
24207,NaN,17877_Viterbo,NaN,10 a 14,779.0,1,0,493,75,0,...,0,0,2,0,1,161,0,33,0,13
24208,NaN,17877_Viterbo,NaN,15 a 19,883.0,14,24,568,72,12,...,1,0,5,1,6,110,0,47,0,23
24209,NaN,17877_Viterbo,NaN,20 a 24,835.0,114,92,427,46,18,...,0,0,14,0,12,73,0,21,0,18
24210,NaN,17877_Viterbo,NaN,25 a 29,748.0,192,146,311,17,18,...,0,0,11,0,2,20,0,23,0,8
24211,NaN,17877_Viterbo,NaN,30 a 34,674.0,251,171,172,13,18,...,1,0,12,0,5,6,0,12,0,13
24212,NaN,17877_Viterbo,NaN,35 a 39,723.0,319,171,164,5,11,...,0,1,10,0,11,8,0,12,0,11
24213,NaN,17877_Viterbo,NaN,40 a 44,634.0,284,187,110,4,12,...,0,0,14,0,5,1,0,9,0,5
24214,NaN,17877_Viterbo,NaN,45 a 49,736.0,376,189,108,0,8,...,0,3,23,0,4,0,0,10,1,6
24215,NaN,17877_Viterbo,NaN,50 a 54,730.0,389,211,67,2,6,...,0,3,22,2,3,0,1,7,1,5
24216,NaN,17877_Viterbo,NaN,55 a 59,686.0,379,171,50,1,5,...,0,11,38,0,3,0,0,8,0,9
24217,NaN,17877_Viterbo,NaN,60 a 64,549.0,300,129,19,0,3,...,0,2,45,0,11,0,1,7,1,16
24218,NaN,17877_Viterbo,NaN,65 a 69,496.0,285,105,12,0,4,...,0,7,31,0,5,0,0,10,0,7
24219,NaN,17877_Viterbo,NaN,70 a 74,374.0,228,61,1,0,0,...,1,9,30,0,2,0,0,7,0,4
24220,NaN,17877_Viterbo,NaN,75 a 79,322.0,207,43,0,0,0,...,2,10,14,0,3,0,3,6,0,7
24221,NaN,17877_Viterbo,NaN,80 a 84,196.0,115,19,0,0,0,...,0,12,13,1,0,0,2,4,0,6
24222,NaN,17877_Viterbo,NaN,85 y más,160.0,90,10,0,0,0,...,0,7,5,0,3,0,3,7,0,5
24223,NaN,17877_Viterbo,Rural disperso,Total,1761.0,525,373,527,67,18,...,6,12,26,3,19,75,0,49,3,37
24224,NaN,17877_Viterbo,NaN,0 a 4,97.0,0,0,65,3,0,...,0,0,0,0,0,21,0,3,0,5
24225,NaN,17877_Viterbo,NaN,5 a 9,122.0,0,0,75,14,0,...,0,0,0,0,0,21,0,9,0,3
24226,NaN,17877_Viterbo,NaN,10 a 14,162.0,0,1,110,17,0,...,2,0,0,0,0,16,0,9,0,7
24227,NaN,17877_Viterbo,NaN,15 a 19,187.0,7,7,124,19,6,...,3,0,1,1,0,12,0,4,0,3
24228,NaN,17877_Viterbo,NaN,20 a 24,123.0,11,26,61,10,2,...,0,0,2,1,0,5,0,2,0,3
24229,NaN,17877_Viterbo,NaN,25 a 29,107.0,33,29,29,4,4,...,0,0,1,0,2,0,0,2,0,3
24230,NaN,17877_Viterbo,NaN,30 a 34,105.0,27,44,20,0,1,...,1,0,3,0,2,0,0,4,2,1
24231,NaN,17877_Viterbo,NaN,35 a 39,117.0,51,41,14,0,1,...,0,0,1,0,2,0,0,5,0,1
24232,NaN,17877_Viterbo,NaN,40 a 44,113.0,48,44,11,0,2,...,0,0,0,0,2,0,0,2,0,4
24233,NaN,17877_Viterbo,NaN,45 a 49,116.0,61,40,8,0,0,...,0,1,1,1,2,0,0,1,1,0
24234,NaN,17877_Viterbo,NaN,50 a 54,116.0,62,43,4,0,1,...,0,0,0,0,2,0,0,1,0,3
24235,NaN,17877_Viterbo,NaN,55 a 59,99.0,58,28,5,0,0,...,0,2,2,0,0,0,0,0,0,2
24236,NaN,17877_Viterbo,NaN,60 a 64,101.0,47,37,1,0,0,...,0,3,7,0,4,0,0,0,0,0
24237,NaN,17877_Viterbo,NaN,65 a 69,77.0,47,17,0,0,0,...,0,2,2,0,0,0,0,3,0,0
24238,NaN,17877_Viterbo,NaN,70 a 74,60.0,39,8,0,0,0,...,0,2,4,0,2,0,0,2,0,1
24239,NaN,17877_Viterbo,NaN,75 a 79,30.0,16,5,0,0,1,...,0,1,2,0,1,0,0,1,0,0
24240,NaN,17877_Viterbo,NaN,80 a 84,16.0,12,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
24241,NaN,17877_Viterbo,NaN,85 y más,13.0,6,2,0,0,0,...,0,0,0,0,0,0,0,1,0,1

Se eliminan columnas que no contienen datos relevantes para el dataset y aquellas que contienen resumenes de datos.

In [7]:
list(df_5_1pm.columns.values)

['Grupos de edad y áreas (Total, Cabecera y Centros poblados y Rural disperso) y ',
 'Municipio',
 'Area',
 'Grupo de edad',
 'Total',
 'Jefe(a) del hogar',
 'Pareja (Conyuge, compañero(a), esposo(a))',
 'Hijo(a)',
 'Hijastro(a)',
 'Yerno/nuera',
 'Padre/madre',
 'Padrastro, madrastra',
 'Suegro(a)',
 'Hermano(a)',
 'Hermanastro(a)',
 'Cuñado(a)',
 'Nieto(a)',
 'Abuelo(a)',
 'Otro pariente',
 'Empleado(a) del servicio doméstico',
 'No pariente']

In [8]:
df_5_1pm = df_5_1pm.drop(['Grupos de edad y áreas (Total, Cabecera y Centros poblados y Rural disperso) y ', 'Municipio'], axis=1)
df_5_1pm

,Area,Grupo de edad,Total,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
24185,Total,Total,12425.0,4069,2102,3703,347,133,211,11,77,315,7,95,785,10,325,6,229
24186,NaN,0 a 4,616.0,0,0,366,13,0,0,0,0,0,0,0,178,0,32,0,27
24187,NaN,5 a 9,742.0,0,0,448,49,0,0,0,0,0,0,0,195,0,33,0,17
24188,NaN,10 a 14,941.0,1,1,603,92,0,0,2,0,2,0,1,177,0,42,0,20
24189,NaN,15 a 19,1070.0,21,31,692,91,18,0,4,0,6,2,6,122,0,51,0,26
24190,NaN,20 a 24,958.0,125,118,488,56,20,0,0,0,16,1,12,78,0,23,0,21
24191,NaN,25 a 29,855.0,225,175,340,21,22,0,0,0,12,0,4,20,0,25,0,11
24192,NaN,30 a 34,779.0,278,215,192,13,19,0,2,0,15,0,7,6,0,16,2,14
24193,NaN,35 a 39,840.0,370,212,178,5,12,1,0,1,11,0,13,8,0,17,0,12
24194,NaN,40 a 44,747.0,332,231,121,4,14,3,0,0,14,0,7,1,0,11,0,9
24195,NaN,45 a 49,852.0,437,229,116,0,8,8,0,4,24,1,6,0,0,11,2,6
24196,NaN,50 a 54,846.0,451,254,71,2,7,11,0,3,22,2,5,0,1,8,1,8
24197,NaN,55 a 59,785.0,437,199,55,1,5,13,0,13,40,0,3,0,0,8,0,11
24198,NaN,60 a 64,650.0,347,166,20,0,3,17,0,5,52,0,15,0,1,7,1,16
24199,NaN,65 a 69,573.0,332,122,12,0,4,36,0,9,33,0,5,0,0,13,0,7
24200,NaN,70 a 74,434.0,267,69,1,0,0,33,1,11,34,0,4,0,0,9,0,5
24201,NaN,75 a 79,352.0,223,48,0,0,1,30,2,11,16,0,4,0,3,7,0,7
24202,NaN,80 a 84,212.0,127,20,0,0,0,26,0,13,13,1,0,0,2,4,0,6
24203,NaN,85 y más,173.0,96,12,0,0,0,33,0,7,5,0,3,0,3,8,0,6
24204,Cabecera,Total,10664.0,3544,1729,3176,280,115,190,5,65,289,4,76,710,10,276,3,192
24205,NaN,0 a 4,519.0,0,0,301,10,0,0,0,0,0,0,0,157,0,29,0,22
24206,NaN,5 a 9,620.0,0,0,373,35,0,0,0,0,0,0,0,174,0,24,0,14
24207,NaN,10 a 14,779.0,1,0,493,75,0,0,0,0,2,0,1,161,0,33,0,13
24208,NaN,15 a 19,883.0,14,24,568,72,12,0,1,0,5,1,6,110,0,47,0,23
24209,NaN,20 a 24,835.0,114,92,427,46,18,0,0,0,14,0,12,73,0,21,0,18
24210,NaN,25 a 29,748.0,192,146,311,17,18,0,0,0,11,0,2,20,0,23,0,8
24211,NaN,30 a 34,674.0,251,171,172,13,18,0,1,0,12,0,5,6,0,12,0,13
24212,NaN,35 a 39,723.0,319,171,164,5,11,0,0,1,10,0,11,8,0,12,0,11
24213,NaN,40 a 44,634.0,284,187,110,4,12,3,0,0,14,0,5,1,0,9,0,5
24214,NaN,45 a 49,736.0,376,189,108,0,8,8,0,3,23,0,4,0,0,10,1,6
24215,NaN,50 a 54,730.0,389,211,67,2,6,11,0,3,22,2,3,0,1,7,1,5
24216,NaN,55 a 59,686.0,379,171,50,1,5,11,0,11,38,0,3,0,0,8,0,9
24217,NaN,60 a 64,549.0,300,129,19,0,3,15,0,2,45,0,11,0,1,7,1,16
24218,NaN,65 a 69,496.0,285,105,12,0,4,30,0,7,31,0,5,0,0,10,0,7
24219,NaN,70 a 74,374.0,228,61,1,0,0,31,1,9,30,0,2,0,0,7,0,4
24220,NaN,75 a 79,322.0,207,43,0,0,0,27,2,10,14,0,3,0,3,6,0,7
24221,NaN,80 a 84,196.0,115,19,0,0,0,24,0,12,13,1,0,0,2,4,0,6
24222,NaN,85 y más,160.0,90,10,0,0,0,30,0,7,5,0,3,0,3,7,0,5
24223,Rural disperso,Total,1761.0,525,373,527,67,18,21,6,12,26,3,19,75,0,49,3,37
24224,NaN,0 a 4,97.0,0,0,65,3,0,0,0,0,0,0,0,21,0,3,0,5
24225,NaN,5 a 9,122.0,0,0,75,14,0,0,0,0,0,0,0,21,0,9,0,3
24226,NaN,10 a 14,162.0,0,1,110,17,0,0,2,0,0,0,0,16,0,9,0,7
24227,NaN,15 a 19,187.0,7,7,124,19,6,0,3,0,1,1,0,12,0,4,0,3
24228,NaN,20 a 24,123.0,11,26,61,10,2,0,0,0,2,1,0,5,0,2,0,3
24229,NaN,25 a 29,107.0,33,29,29,4,4,0,0,0,1,0,2,0,0,2,0,3
24230,NaN,30 a 34,105.0,27,44,20,0,1,0,1,0,3,0,2,0,0,4,2,1
24231,NaN,35 a 39,117.0,51,41,14,0,1,1,0,0,1,0,2,0,0,5,0,1
24232,NaN,40 a 44,113.0,48,44,11,0,2,0,0,0,0,0,2,0,0,2,0,4
24233,NaN,45 a 49,116.0,61,40,8,0,0,0,0,1,1,1,2,0,0,1,1,0
24234,NaN,50 a 54,116.0,62,43,4,0,1,0,0,0,0,0,2,0,0,1,0,3
24235,NaN,55 a 59,99.0,58,28,5,0,0,2,0,2,2,0,0,0,0,0,0,2
24236,NaN,60 a 64,101.0,47,37,1,0,0,2,0,3,7,0,4,0,0,0,0,0
24237,NaN,65 a 69,77.0,47,17,0,0,0,6,0,2,2,0,0,0,0,3,0,0
24238,NaN,70 a 74,60.0,39,8,0,0,0,2,0,2,4,0,2,0,0,2,0,1
24239,NaN,75 a 79,30.0,16,5,0,0,1,3,0,1,2,0,1,0,0,1,0,0
24240,NaN,80 a 84,16.0,12,1,0,0,0,2,0,1,0,0,0,0,0,0,0,0
24241,NaN,85 y más,13.0,6,2,0,0,0,3,0,0,0,0,0,0,0,1,0,1

Se renombran los headers que tienen tildes y ñ.

In [9]:
df_5_1pm = df_5_1pm.rename(columns={'Pareja (Conyuge, compañero(a), esposo(a))':'Pareja (Conyuge, companero(a), esposo(a))',
                       'Cuñado(a)':'Cunado(a)',
                       'Empleado(a) del servicio doméstico':'Empleado(a) del servicio domestico'})
df_5_1pm

,Area,Grupo de edad,Total,Jefe(a) del hogar,"Pareja (Conyuge, companero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cunado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio domestico,No pariente
24185,Total,Total,12425.0,4069,2102,3703,347,133,211,11,77,315,7,95,785,10,325,6,229
24186,NaN,0 a 4,616.0,0,0,366,13,0,0,0,0,0,0,0,178,0,32,0,27
24187,NaN,5 a 9,742.0,0,0,448,49,0,0,0,0,0,0,0,195,0,33,0,17
24188,NaN,10 a 14,941.0,1,1,603,92,0,0,2,0,2,0,1,177,0,42,0,20
24189,NaN,15 a 19,1070.0,21,31,692,91,18,0,4,0,6,2,6,122,0,51,0,26
24190,NaN,20 a 24,958.0,125,118,488,56,20,0,0,0,16,1,12,78,0,23,0,21
24191,NaN,25 a 29,855.0,225,175,340,21,22,0,0,0,12,0,4,20,0,25,0,11
24192,NaN,30 a 34,779.0,278,215,192,13,19,0,2,0,15,0,7,6,0,16,2,14
24193,NaN,35 a 39,840.0,370,212,178,5,12,1,0,1,11,0,13,8,0,17,0,12
24194,NaN,40 a 44,747.0,332,231,121,4,14,3,0,0,14,0,7,1,0,11,0,9
24195,NaN,45 a 49,852.0,437,229,116,0,8,8,0,4,24,1,6,0,0,11,2,6
24196,NaN,50 a 54,846.0,451,254,71,2,7,11,0,3,22,2,5,0,1,8,1,8
24197,NaN,55 a 59,785.0,437,199,55,1,5,13,0,13,40,0,3,0,0,8,0,11
24198,NaN,60 a 64,650.0,347,166,20,0,3,17,0,5,52,0,15,0,1,7,1,16
24199,NaN,65 a 69,573.0,332,122,12,0,4,36,0,9,33,0,5,0,0,13,0,7
24200,NaN,70 a 74,434.0,267,69,1,0,0,33,1,11,34,0,4,0,0,9,0,5
24201,NaN,75 a 79,352.0,223,48,0,0,1,30,2,11,16,0,4,0,3,7,0,7
24202,NaN,80 a 84,212.0,127,20,0,0,0,26,0,13,13,1,0,0,2,4,0,6
24203,NaN,85 y más,173.0,96,12,0,0,0,33,0,7,5,0,3,0,3,8,0,6
24204,Cabecera,Total,10664.0,3544,1729,3176,280,115,190,5,65,289,4,76,710,10,276,3,192
24205,NaN,0 a 4,519.0,0,0,301,10,0,0,0,0,0,0,0,157,0,29,0,22
24206,NaN,5 a 9,620.0,0,0,373,35,0,0,0,0,0,0,0,174,0,24,0,14
24207,NaN,10 a 14,779.0,1,0,493,75,0,0,0,0,2,0,1,161,0,33,0,13
24208,NaN,15 a 19,883.0,14,24,568,72,12,0,1,0,5,1,6,110,0,47,0,23
24209,NaN,20 a 24,835.0,114,92,427,46,18,0,0,0,14,0,12,73,0,21,0,18
24210,NaN,25 a 29,748.0,192,146,311,17,18,0,0,0,11,0,2,20,0,23,0,8
24211,NaN,30 a 34,674.0,251,171,172,13,18,0,1,0,12,0,5,6,0,12,0,13
24212,NaN,35 a 39,723.0,319,171,164,5,11,0,0,1,10,0,11,8,0,12,0,11
24213,NaN,40 a 44,634.0,284,187,110,4,12,3,0,0,14,0,5,1,0,9,0,5
24214,NaN,45 a 49,736.0,376,189,108,0,8,8,0,3,23,0,4,0,0,10,1,6
24215,NaN,50 a 54,730.0,389,211,67,2,6,11,0,3,22,2,3,0,1,7,1,5
24216,NaN,55 a 59,686.0,379,171,50,1,5,11,0,11,38,0,3,0,0,8,0,9
24217,NaN,60 a 64,549.0,300,129,19,0,3,15,0,2,45,0,11,0,1,7,1,16
24218,NaN,65 a 69,496.0,285,105,12,0,4,30,0,7,31,0,5,0,0,10,0,7
24219,NaN,70 a 74,374.0,228,61,1,0,0,31,1,9,30,0,2,0,0,7,0,4
24220,NaN,75 a 79,322.0,207,43,0,0,0,27,2,10,14,0,3,0,3,6,0,7
24221,NaN,80 a 84,196.0,115,19,0,0,0,24,0,12,13,1,0,0,2,4,0,6
24222,NaN,85 y más,160.0,90,10,0,0,0,30,0,7,5,0,3,0,3,7,0,5
24223,Rural disperso,Total,1761.0,525,373,527,67,18,21,6,12,26,3,19,75,0,49,3,37
24224,NaN,0 a 4,97.0,0,0,65,3,0,0,0,0,0,0,0,21,0,3,0,5
24225,NaN,5 a 9,122.0,0,0,75,14,0,0,0,0,0,0,0,21,0,9,0,3
24226,NaN,10 a 14,162.0,0,1,110,17,0,0,2,0,0,0,0,16,0,9,0,7
24227,NaN,15 a 19,187.0,7,7,124,19,6,0,3,0,1,1,0,12,0,4,0,3
24228,NaN,20 a 24,123.0,11,26,61,10,2,0,0,0,2,1,0,5,0,2,0,3
24229,NaN,25 a 29,107.0,33,29,29,4,4,0,0,0,1,0,2,0,0,2,0,3
24230,NaN,30 a 34,105.0,27,44,20,0,1,0,1,0,3,0,2,0,0,4,2,1
24231,NaN,35 a 39,117.0,51,41,14,0,1,1,0,0,1,0,2,0,0,5,0,1
24232,NaN,40 a 44,113.0,48,44,11,0,2,0,0,0,0,0,2,0,0,2,0,4
24233,NaN,45 a 49,116.0,61,40,8,0,0,0,0,1,1,1,2,0,0,1,1,0
24234,NaN,50 a 54,116.0,62,43,4,0,1,0,0,0,0,0,2,0,0,1,0,3
24235,NaN,55 a 59,99.0,58,28,5,0,0,2,0,2,2,0,0,0,0,0,0,2
24236,NaN,60 a 64,101.0,47,37,1,0,0,2,0,3,7,0,4,0,0,0,0,0
24237,NaN,65 a 69,77.0,47,17,0,0,0,6,0,2,2,0,0,0,0,3,0,0
24238,NaN,70 a 74,60.0,39,8,0,0,0,2,0,2,4,0,2,0,0,2,0,1
24239,NaN,75 a 79,30.0,16,5,0,0,1,3,0,1,2,0,1,0,0,1,0,0
24240,NaN,80 a 84,16.0,12,1,0,0,0,2,0,1,0,0,0,0,0,0,0,0
24241,NaN,85 y más,13.0,6,2,0,0,0,3,0,0,0,0,0,0,0,1,0,1

Se propaga el area para reemplazar valores NaN.

In [10]:
df_5_1pm['Area'] = df_5_1pm['Area'].ffill()
df_5_1pm

,Area,Grupo de edad,Total,Jefe(a) del hogar,"Pareja (Conyuge, companero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cunado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio domestico,No pariente
24185,Total,Total,12425.0,4069,2102,3703,347,133,211,11,77,315,7,95,785,10,325,6,229
24186,Total,0 a 4,616.0,0,0,366,13,0,0,0,0,0,0,0,178,0,32,0,27
24187,Total,5 a 9,742.0,0,0,448,49,0,0,0,0,0,0,0,195,0,33,0,17
24188,Total,10 a 14,941.0,1,1,603,92,0,0,2,0,2,0,1,177,0,42,0,20
24189,Total,15 a 19,1070.0,21,31,692,91,18,0,4,0,6,2,6,122,0,51,0,26
24190,Total,20 a 24,958.0,125,118,488,56,20,0,0,0,16,1,12,78,0,23,0,21
24191,Total,25 a 29,855.0,225,175,340,21,22,0,0,0,12,0,4,20,0,25,0,11
24192,Total,30 a 34,779.0,278,215,192,13,19,0,2,0,15,0,7,6,0,16,2,14
24193,Total,35 a 39,840.0,370,212,178,5,12,1,0,1,11,0,13,8,0,17,0,12
24194,Total,40 a 44,747.0,332,231,121,4,14,3,0,0,14,0,7,1,0,11,0,9
24195,Total,45 a 49,852.0,437,229,116,0,8,8,0,4,24,1,6,0,0,11,2,6
24196,Total,50 a 54,846.0,451,254,71,2,7,11,0,3,22,2,5,0,1,8,1,8
24197,Total,55 a 59,785.0,437,199,55,1,5,13,0,13,40,0,3,0,0,8,0,11
24198,Total,60 a 64,650.0,347,166,20,0,3,17,0,5,52,0,15,0,1,7,1,16
24199,Total,65 a 69,573.0,332,122,12,0,4,36,0,9,33,0,5,0,0,13,0,7
24200,Total,70 a 74,434.0,267,69,1,0,0,33,1,11,34,0,4,0,0,9,0,5
24201,Total,75 a 79,352.0,223,48,0,0,1,30,2,11,16,0,4,0,3,7,0,7
24202,Total,80 a 84,212.0,127,20,0,0,0,26,0,13,13,1,0,0,2,4,0,6
24203,Total,85 y más,173.0,96,12,0,0,0,33,0,7,5,0,3,0,3,8,0,6
24204,Cabecera,Total,10664.0,3544,1729,3176,280,115,190,5,65,289,4,76,710,10,276,3,192
24205,Cabecera,0 a 4,519.0,0,0,301,10,0,0,0,0,0,0,0,157,0,29,0,22
24206,Cabecera,5 a 9,620.0,0,0,373,35,0,0,0,0,0,0,0,174,0,24,0,14
24207,Cabecera,10 a 14,779.0,1,0,493,75,0,0,0,0,2,0,1,161,0,33,0,13
24208,Cabecera,15 a 19,883.0,14,24,568,72,12,0,1,0,5,1,6,110,0,47,0,23
24209,Cabecera,20 a 24,835.0,114,92,427,46,18,0,0,0,14,0,12,73,0,21,0,18
24210,Cabecera,25 a 29,748.0,192,146,311,17,18,0,0,0,11,0,2,20,0,23,0,8
24211,Cabecera,30 a 34,674.0,251,171,172,13,18,0,1,0,12,0,5,6,0,12,0,13
24212,Cabecera,35 a 39,723.0,319,171,164,5,11,0,0,1,10,0,11,8,0,12,0,11
24213,Cabecera,40 a 44,634.0,284,187,110,4,12,3,0,0,14,0,5,1,0,9,0,5
24214,Cabecera,45 a 49,736.0,376,189,108,0,8,8,0,3,23,0,4,0,0,10,1,6
24215,Cabecera,50 a 54,730.0,389,211,67,2,6,11,0,3,22,2,3,0,1,7,1,5
24216,Cabecera,55 a 59,686.0,379,171,50,1,5,11,0,11,38,0,3,0,0,8,0,9
24217,Cabecera,60 a 64,549.0,300,129,19,0,3,15,0,2,45,0,11,0,1,7,1,16
24218,Cabecera,65 a 69,496.0,285,105,12,0,4,30,0,7,31,0,5,0,0,10,0,7
24219,Cabecera,70 a 74,374.0,228,61,1,0,0,31,1,9,30,0,2,0,0,7,0,4
24220,Cabecera,75 a 79,322.0,207,43,0,0,0,27,2,10,14,0,3,0,3,6,0,7
24221,Cabecera,80 a 84,196.0,115,19,0,0,0,24,0,12,13,1,0,0,2,4,0,6
24222,Cabecera,85 y más,160.0,90,10,0,0,0,30,0,7,5,0,3,0,3,7,0,5
24223,Rural disperso,Total,1761.0,525,373,527,67,18,21,6,12,26,3,19,75,0,49,3,37
24224,Rural disperso,0 a 4,97.0,0,0,65,3,0,0,0,0,0,0,0,21,0,3,0,5
24225,Rural disperso,5 a 9,122.0,0,0,75,14,0,0,0,0,0,0,0,21,0,9,0,3
24226,Rural disperso,10 a 14,162.0,0,1,110,17,0,0,2,0,0,0,0,16,0,9,0,7
24227,Rural disperso,15 a 19,187.0,7,7,124,19,6,0,3,0,1,1,0,12,0,4,0,3
24228,Rural disperso,20 a 24,123.0,11,26,61,10,2,0,0,0,2,1,0,5,0,2,0,3
24229,Rural disperso,25 a 29,107.0,33,29,29,4,4,0,0,0,1,0,2,0,0,2,0,3
24230,Rural disperso,30 a 34,105.0,27,44,20,0,1,0,1,0,3,0,2,0,0,4,2,1
24231,Rural disperso,35 a 39,117.0,51,41,14,0,1,1,0,0,1,0,2,0,0,5,0,1
24232,Rural disperso,40 a 44,113.0,48,44,11,0,2,0,0,0,0,0,2,0,0,2,0,4
24233,Rural disperso,45 a 49,116.0,61,40,8,0,0,0,0,1,1,1,2,0,0,1,1,0
24234,Rural disperso,50 a 54,116.0,62,43,4,0,1,0,0,0,0,0,2,0,0,1,0,3
24235,Rural disperso,55 a 59,99.0,58,28,5,0,0,2,0,2,2,0,0,0,0,0,0,2
24236,Rural disperso,60 a 64,101.0,47,37,1,0,0,2,0,3,7,0,4,0,0,0,0,0
24237,Rural disperso,65 a 69,77.0,47,17,0,0,0,6,0,2,2,0,0,0,0,3,0,0
24238,Rural disperso,70 a 74,60.0,39,8,0,0,0,2,0,2,4,0,2,0,0,2,0,1
24239,Rural disperso,75 a 79,30.0,16,5,0,0,1,3,0,1,2,0,1,0,0,1,0,0
24240,Rural disperso,80 a 84,16.0,12,1,0,0,0,2,0,1,0,0,0,0,0,0,0,0
24241,Rural disperso,85 y más,13.0,6,2,0,0,0,3,0,0,0,0,0,0,0,1,0,1

Se reemplazan las tildes dentro de los datos.

In [11]:
df_5_1pm['Grupo de edad'] = df_5_1pm['Grupo de edad'].str.replace('á', 'a')
df_5_1pm

,Area,Grupo de edad,Total,Jefe(a) del hogar,"Pareja (Conyuge, companero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cunado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio domestico,No pariente
24185,Total,Total,12425.0,4069,2102,3703,347,133,211,11,77,315,7,95,785,10,325,6,229
24186,Total,0 a 4,616.0,0,0,366,13,0,0,0,0,0,0,0,178,0,32,0,27
24187,Total,5 a 9,742.0,0,0,448,49,0,0,0,0,0,0,0,195,0,33,0,17
24188,Total,10 a 14,941.0,1,1,603,92,0,0,2,0,2,0,1,177,0,42,0,20
24189,Total,15 a 19,1070.0,21,31,692,91,18,0,4,0,6,2,6,122,0,51,0,26
24190,Total,20 a 24,958.0,125,118,488,56,20,0,0,0,16,1,12,78,0,23,0,21
24191,Total,25 a 29,855.0,225,175,340,21,22,0,0,0,12,0,4,20,0,25,0,11
24192,Total,30 a 34,779.0,278,215,192,13,19,0,2,0,15,0,7,6,0,16,2,14
24193,Total,35 a 39,840.0,370,212,178,5,12,1,0,1,11,0,13,8,0,17,0,12
24194,Total,40 a 44,747.0,332,231,121,4,14,3,0,0,14,0,7,1,0,11,0,9
24195,Total,45 a 49,852.0,437,229,116,0,8,8,0,4,24,1,6,0,0,11,2,6
24196,Total,50 a 54,846.0,451,254,71,2,7,11,0,3,22,2,5,0,1,8,1,8
24197,Total,55 a 59,785.0,437,199,55,1,5,13,0,13,40,0,3,0,0,8,0,11
24198,Total,60 a 64,650.0,347,166,20,0,3,17,0,5,52,0,15,0,1,7,1,16
24199,Total,65 a 69,573.0,332,122,12,0,4,36,0,9,33,0,5,0,0,13,0,7
24200,Total,70 a 74,434.0,267,69,1,0,0,33,1,11,34,0,4,0,0,9,0,5
24201,Total,75 a 79,352.0,223,48,0,0,1,30,2,11,16,0,4,0,3,7,0,7
24202,Total,80 a 84,212.0,127,20,0,0,0,26,0,13,13,1,0,0,2,4,0,6
24203,Total,85 y mas,173.0,96,12,0,0,0,33,0,7,5,0,3,0,3,8,0,6
24204,Cabecera,Total,10664.0,3544,1729,3176,280,115,190,5,65,289,4,76,710,10,276,3,192
24205,Cabecera,0 a 4,519.0,0,0,301,10,0,0,0,0,0,0,0,157,0,29,0,22
24206,Cabecera,5 a 9,620.0,0,0,373,35,0,0,0,0,0,0,0,174,0,24,0,14
24207,Cabecera,10 a 14,779.0,1,0,493,75,0,0,0,0,2,0,1,161,0,33,0,13
24208,Cabecera,15 a 19,883.0,14,24,568,72,12,0,1,0,5,1,6,110,0,47,0,23
24209,Cabecera,20 a 24,835.0,114,92,427,46,18,0,0,0,14,0,12,73,0,21,0,18
24210,Cabecera,25 a 29,748.0,192,146,311,17,18,0,0,0,11,0,2,20,0,23,0,8
24211,Cabecera,30 a 34,674.0,251,171,172,13,18,0,1,0,12,0,5,6,0,12,0,13
24212,Cabecera,35 a 39,723.0,319,171,164,5,11,0,0,1,10,0,11,8,0,12,0,11
24213,Cabecera,40 a 44,634.0,284,187,110,4,12,3,0,0,14,0,5,1,0,9,0,5
24214,Cabecera,45 a 49,736.0,376,189,108,0,8,8,0,3,23,0,4,0,0,10,1,6
24215,Cabecera,50 a 54,730.0,389,211,67,2,6,11,0,3,22,2,3,0,1,7,1,5
24216,Cabecera,55 a 59,686.0,379,171,50,1,5,11,0,11,38,0,3,0,0,8,0,9
24217,Cabecera,60 a 64,549.0,300,129,19,0,3,15,0,2,45,0,11,0,1,7,1,16
24218,Cabecera,65 a 69,496.0,285,105,12,0,4,30,0,7,31,0,5,0,0,10,0,7
24219,Cabecera,70 a 74,374.0,228,61,1,0,0,31,1,9,30,0,2,0,0,7,0,4
24220,Cabecera,75 a 79,322.0,207,43,0,0,0,27,2,10,14,0,3,0,3,6,0,7
24221,Cabecera,80 a 84,196.0,115,19,0,0,0,24,0,12,13,1,0,0,2,4,0,6
24222,Cabecera,85 y mas,160.0,90,10,0,0,0,30,0,7,5,0,3,0,3,7,0,5
24223,Rural disperso,Total,1761.0,525,373,527,67,18,21,6,12,26,3,19,75,0,49,3,37
24224,Rural disperso,0 a 4,97.0,0,0,65,3,0,0,0,0,0,0,0,21,0,3,0,5
24225,Rural disperso,5 a 9,122.0,0,0,75,14,0,0,0,0,0,0,0,21,0,9,0,3
24226,Rural disperso,10 a 14,162.0,0,1,110,17,0,0,2,0,0,0,0,16,0,9,0,7
24227,Rural disperso,15 a 19,187.0,7,7,124,19,6,0,3,0,1,1,0,12,0,4,0,3
24228,Rural disperso,20 a 24,123.0,11,26,61,10,2,0,0,0,2,1,0,5,0,2,0,3
24229,Rural disperso,25 a 29,107.0,33,29,29,4,4,0,0,0,1,0,2,0,0,2,0,3
24230,Rural disperso,30 a 34,105.0,27,44,20,0,1,0,1,0,3,0,2,0,0,4,2,1
24231,Rural disperso,35 a 39,117.0,51,41,14,0,1,1,0,0,1,0,2,0,0,5,0,1
24232,Rural disperso,40 a 44,113.0,48,44,11,0,2,0,0,0,0,0,2,0,0,2,0,4
24233,Rural disperso,45 a 49,116.0,61,40,8,0,0,0,0,1,1,1,2,0,0,1,1,0
24234,Rural disperso,50 a 54,116.0,62,43,4,0,1,0,0,0,0,0,2,0,0,1,0,3
24235,Rural disperso,55 a 59,99.0,58,28,5,0,0,2,0,2,2,0,0,0,0,0,0,2
24236,Rural disperso,60 a 64,101.0,47,37,1,0,0,2,0,3,7,0,4,0,0,0,0,0
24237,Rural disperso,65 a 69,77.0,47,17,0,0,0,6,0,2,2,0,0,0,0,3,0,0
24238,Rural disperso,70 a 74,60.0,39,8,0,0,0,2,0,2,4,0,2,0,0,2,0,1
24239,Rural disperso,75 a 79,30.0,16,5,0,0,1,3,0,1,2,0,1,0,0,1,0,0
24240,Rural disperso,80 a 84,16.0,12,1,0,0,0,2,0,1,0,0,0,0,0,0,0,0
24241,Rural disperso,85 y mas,13.0,6,2,0,0,0,3,0,0,0,0,0,0,0,1,0,1

Se creará una copia del dataframe y se removerán las filas y columnas con resumenes de datos para el csv que no contiene resúmenes.

In [12]:
df_5_1_pm_cleaned = df_5_1pm.copy()
df_5_1_pm_cleaned.drop(['Total'], axis=1, inplace=True)
df_5_1_pm_cleaned

,Area,Grupo de edad,Jefe(a) del hogar,"Pareja (Conyuge, companero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cunado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio domestico,No pariente
24185,Total,Total,4069,2102,3703,347,133,211,11,77,315,7,95,785,10,325,6,229
24186,Total,0 a 4,0,0,366,13,0,0,0,0,0,0,0,178,0,32,0,27
24187,Total,5 a 9,0,0,448,49,0,0,0,0,0,0,0,195,0,33,0,17
24188,Total,10 a 14,1,1,603,92,0,0,2,0,2,0,1,177,0,42,0,20
24189,Total,15 a 19,21,31,692,91,18,0,4,0,6,2,6,122,0,51,0,26
24190,Total,20 a 24,125,118,488,56,20,0,0,0,16,1,12,78,0,23,0,21
24191,Total,25 a 29,225,175,340,21,22,0,0,0,12,0,4,20,0,25,0,11
24192,Total,30 a 34,278,215,192,13,19,0,2,0,15,0,7,6,0,16,2,14
24193,Total,35 a 39,370,212,178,5,12,1,0,1,11,0,13,8,0,17,0,12
24194,Total,40 a 44,332,231,121,4,14,3,0,0,14,0,7,1,0,11,0,9
24195,Total,45 a 49,437,229,116,0,8,8,0,4,24,1,6,0,0,11,2,6
24196,Total,50 a 54,451,254,71,2,7,11,0,3,22,2,5,0,1,8,1,8
24197,Total,55 a 59,437,199,55,1,5,13,0,13,40,0,3,0,0,8,0,11
24198,Total,60 a 64,347,166,20,0,3,17,0,5,52,0,15,0,1,7,1,16
24199,Total,65 a 69,332,122,12,0,4,36,0,9,33,0,5,0,0,13,0,7
24200,Total,70 a 74,267,69,1,0,0,33,1,11,34,0,4,0,0,9,0,5
24201,Total,75 a 79,223,48,0,0,1,30,2,11,16,0,4,0,3,7,0,7
24202,Total,80 a 84,127,20,0,0,0,26,0,13,13,1,0,0,2,4,0,6
24203,Total,85 y mas,96,12,0,0,0,33,0,7,5,0,3,0,3,8,0,6
24204,Cabecera,Total,3544,1729,3176,280,115,190,5,65,289,4,76,710,10,276,3,192
24205,Cabecera,0 a 4,0,0,301,10,0,0,0,0,0,0,0,157,0,29,0,22
24206,Cabecera,5 a 9,0,0,373,35,0,0,0,0,0,0,0,174,0,24,0,14
24207,Cabecera,10 a 14,1,0,493,75,0,0,0,0,2,0,1,161,0,33,0,13
24208,Cabecera,15 a 19,14,24,568,72,12,0,1,0,5,1,6,110,0,47,0,23
24209,Cabecera,20 a 24,114,92,427,46,18,0,0,0,14,0,12,73,0,21,0,18
24210,Cabecera,25 a 29,192,146,311,17,18,0,0,0,11,0,2,20,0,23,0,8
24211,Cabecera,30 a 34,251,171,172,13,18,0,1,0,12,0,5,6,0,12,0,13
24212,Cabecera,35 a 39,319,171,164,5,11,0,0,1,10,0,11,8,0,12,0,11
24213,Cabecera,40 a 44,284,187,110,4,12,3,0,0,14,0,5,1,0,9,0,5
24214,Cabecera,45 a 49,376,189,108,0,8,8,0,3,23,0,4,0,0,10,1,6
24215,Cabecera,50 a 54,389,211,67,2,6,11,0,3,22,2,3,0,1,7,1,5
24216,Cabecera,55 a 59,379,171,50,1,5,11,0,11,38,0,3,0,0,8,0,9
24217,Cabecera,60 a 64,300,129,19,0,3,15,0,2,45,0,11,0,1,7,1,16
24218,Cabecera,65 a 69,285,105,12,0,4,30,0,7,31,0,5,0,0,10,0,7
24219,Cabecera,70 a 74,228,61,1,0,0,31,1,9,30,0,2,0,0,7,0,4
24220,Cabecera,75 a 79,207,43,0,0,0,27,2,10,14,0,3,0,3,6,0,7
24221,Cabecera,80 a 84,115,19,0,0,0,24,0,12,13,1,0,0,2,4,0,6
24222,Cabecera,85 y mas,90,10,0,0,0,30,0,7,5,0,3,0,3,7,0,5
24223,Rural disperso,Total,525,373,527,67,18,21,6,12,26,3,19,75,0,49,3,37
24224,Rural disperso,0 a 4,0,0,65,3,0,0,0,0,0,0,0,21,0,3,0,5
24225,Rural disperso,5 a 9,0,0,75,14,0,0,0,0,0,0,0,21,0,9,0,3
24226,Rural disperso,10 a 14,0,1,110,17,0,0,2,0,0,0,0,16,0,9,0,7
24227,Rural disperso,15 a 19,7,7,124,19,6,0,3,0,1,1,0,12,0,4,0,3
24228,Rural disperso,20 a 24,11,26,61,10,2,0,0,0,2,1,0,5,0,2,0,3
24229,Rural disperso,25 a 29,33,29,29,4,4,0,0,0,1,0,2,0,0,2,0,3
24230,Rural disperso,30 a 34,27,44,20,0,1,0,1,0,3,0,2,0,0,4,2,1
24231,Rural disperso,35 a 39,51,41,14,0,1,1,0,0,1,0,2,0,0,5,0,1
24232,Rural disperso,40 a 44,48,44,11,0,2,0,0,0,0,0,2,0,0,2,0,4
24233,Rural disperso,45 a 49,61,40,8,0,0,0,0,1,1,1,2,0,0,1,1,0
24234,Rural disperso,50 a 54,62,43,4,0,1,0,0,0,0,0,2,0,0,1,0,3
24235,Rural disperso,55 a 59,58,28,5,0,0,2,0,2,2,0,0,0,0,0,0,2
24236,Rural disperso,60 a 64,47,37,1,0,0,2,0,3,7,0,4,0,0,0,0,0
24237,Rural disperso,65 a 69,47,17,0,0,0,6,0,2,2,0,0,0,0,3,0,0
24238,Rural disperso,70 a 74,39,8,0,0,0,2,0,2,4,0,2,0,0,2,0,1
24239,Rural disperso,75 a 79,16,5,0,0,1,3,0,1,2,0,1,0,0,1,0,0
24240,Rural disperso,80 a 84,12,1,0,0,0,2,0,1,0,0,0,0,0,0,0,0
24241,Rural disperso,85 y mas,6,2,0,0,0,3,0,0,0,0,0,0,0,1,0,1

In [13]:
df_5_1_pm_cleaned = df_5_1_pm_cleaned.loc[(df_5_1_pm_cleaned['Area'] != 'Total') & (df_5_1_pm_cleaned['Grupo de edad'] != 'Total')]
df_5_1_pm_cleaned

,Area,Grupo de edad,Jefe(a) del hogar,"Pareja (Conyuge, companero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cunado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio domestico,No pariente
24205,Cabecera,0 a 4,0,0,301,10,0,0,0,0,0,0,0,157,0,29,0,22
24206,Cabecera,5 a 9,0,0,373,35,0,0,0,0,0,0,0,174,0,24,0,14
24207,Cabecera,10 a 14,1,0,493,75,0,0,0,0,2,0,1,161,0,33,0,13
24208,Cabecera,15 a 19,14,24,568,72,12,0,1,0,5,1,6,110,0,47,0,23
24209,Cabecera,20 a 24,114,92,427,46,18,0,0,0,14,0,12,73,0,21,0,18
24210,Cabecera,25 a 29,192,146,311,17,18,0,0,0,11,0,2,20,0,23,0,8
24211,Cabecera,30 a 34,251,171,172,13,18,0,1,0,12,0,5,6,0,12,0,13
24212,Cabecera,35 a 39,319,171,164,5,11,0,0,1,10,0,11,8,0,12,0,11
24213,Cabecera,40 a 44,284,187,110,4,12,3,0,0,14,0,5,1,0,9,0,5
24214,Cabecera,45 a 49,376,189,108,0,8,8,0,3,23,0,4,0,0,10,1,6
24215,Cabecera,50 a 54,389,211,67,2,6,11,0,3,22,2,3,0,1,7,1,5
24216,Cabecera,55 a 59,379,171,50,1,5,11,0,11,38,0,3,0,0,8,0,9
24217,Cabecera,60 a 64,300,129,19,0,3,15,0,2,45,0,11,0,1,7,1,16
24218,Cabecera,65 a 69,285,105,12,0,4,30,0,7,31,0,5,0,0,10,0,7
24219,Cabecera,70 a 74,228,61,1,0,0,31,1,9,30,0,2,0,0,7,0,4
24220,Cabecera,75 a 79,207,43,0,0,0,27,2,10,14,0,3,0,3,6,0,7
24221,Cabecera,80 a 84,115,19,0,0,0,24,0,12,13,1,0,0,2,4,0,6
24222,Cabecera,85 y mas,90,10,0,0,0,30,0,7,5,0,3,0,3,7,0,5
24224,Rural disperso,0 a 4,0,0,65,3,0,0,0,0,0,0,0,21,0,3,0,5
24225,Rural disperso,5 a 9,0,0,75,14,0,0,0,0,0,0,0,21,0,9,0,3
24226,Rural disperso,10 a 14,0,1,110,17,0,0,2,0,0,0,0,16,0,9,0,7
24227,Rural disperso,15 a 19,7,7,124,19,6,0,3,0,1,1,0,12,0,4,0,3
24228,Rural disperso,20 a 24,11,26,61,10,2,0,0,0,2,1,0,5,0,2,0,3
24229,Rural disperso,25 a 29,33,29,29,4,4,0,0,0,1,0,2,0,0,2,0,3
24230,Rural disperso,30 a 34,27,44,20,0,1,0,1,0,3,0,2,0,0,4,2,1
24231,Rural disperso,35 a 39,51,41,14,0,1,1,0,0,1,0,2,0,0,5,0,1
24232,Rural disperso,40 a 44,48,44,11,0,2,0,0,0,0,0,2,0,0,2,0,4
24233,Rural disperso,45 a 49,61,40,8,0,0,0,0,1,1,1,2,0,0,1,1,0
24234,Rural disperso,50 a 54,62,43,4,0,1,0,0,0,0,0,2,0,0,1,0,3
24235,Rural disperso,55 a 59,58,28,5,0,0,2,0,2,2,0,0,0,0,0,0,2
24236,Rural disperso,60 a 64,47,37,1,0,0,2,0,3,7,0,4,0,0,0,0,0
24237,Rural disperso,65 a 69,47,17,0,0,0,6,0,2,2,0,0,0,0,3,0,0
24238,Rural disperso,70 a 74,39,8,0,0,0,2,0,2,4,0,2,0,0,2,0,1
24239,Rural disperso,75 a 79,16,5,0,0,1,3,0,1,2,0,1,0,0,1,0,0
24240,Rural disperso,80 a 84,12,1,0,0,0,2,0,1,0,0,0,0,0,0,0,0
24241,Rural disperso,85 y mas,6,2,0,0,0,3,0,0,0,0,0,0,0,1,0,1

Los dataframes están listos para ser exportados a CSV.

In [15]:
df_5_1pm.to_csv(csv_total_path, index=False)
df_5_1_pm_cleaned.to_csv(csv_path, index=False)