In [1]:
# imports
import pandas as pd

In [2]:
# Ruta relativa del xslx que contiene los datos
original_data_path = 'Data\\Original\\PERSONAS_DEMOGRAFICO_Cuadros_CNPV_2018.xlsx'

# Nombre del csv objetivo
csv_total_filename = 'caldas_viterbo_total_5_2PM.csv'
csv_filename = 'caldas_viterbo_5_2PM.csv'

# Ruta relativa del csv objetivo
csv_total_path = 'Data\\Datasets\\' + csv_total_filename
csv_path = 'Data\\Datasets\\' + csv_filename

In [3]:
# Lee archivo xlsx
df_5_2pm = pd.read_excel(original_data_path, sheet_name='5.2PM', skiprows=9)
df_5_2pm.head()

,"sexo, grupos de edad y áreas (Total, Cabecera y Centros poblados y Rural disperso), sexo y grupos de edad",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Total,Relación o parentesco con el Jefe(a) del hogar,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,NaN,NaN,NaN,NaN,NaN,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
1,Total Nacional,NaN,Hombre,Total,Total,21317034.0,8440991,1494377,8046302,424474,...,15647,47777,417472,9943,103275,1134220,7681,534876,5343,293655
2,NaN,NaN,NaN,NaN,0 a 4,1553300.0,0,0,1150311,22290,...,0,0,1501,122,292,307547,0,53842,0,17395
3,NaN,NaN,NaN,NaN,5 a 9,1697824.0,0,0,1283351,77372,...,0,0,4589,276,897,264816,0,50913,0,15610
4,NaN,NaN,NaN,NaN,10 a 14,1832805.0,6585,1931,1406555,112308,...,1142,0,11511,522,2696,218430,0,54822,40,16099

Se observa que los headers se encuentran en la primera fila, para ellos se creará un diccionario con el nombre actual de la columna como llave y el nombre correspondiente de la primera fila como valor, para luego reemplazarlos.

In [4]:
df_new_headers = {}
current_headers = list(df_5_2pm.columns.values)[6:]
actual_headers = list(df_5_2pm.iloc[0])[6:]

for key, value in zip(current_headers, actual_headers):
    df_new_headers[key] = value

df_5_2pm = df_5_2pm.rename(columns=df_new_headers)
df_5_2pm

,"sexo, grupos de edad y áreas (Total, Cabecera y Centros poblados y Rural disperso), sexo y grupos de edad",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Total,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
0,NaN,NaN,NaN,NaN,NaN,NaN,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
1,Total Nacional,NaN,Hombre,Total,Total,21317034.0,8440991,1494377,8046302,424474,...,15647,47777,417472,9943,103275,1134220,7681,534876,5343,293655
2,NaN,NaN,NaN,NaN,0 a 4,1553300.0,0,0,1150311,22290,...,0,0,1501,122,292,307547,0,53842,0,17395
3,NaN,NaN,NaN,NaN,5 a 9,1697824.0,0,0,1283351,77372,...,0,0,4589,276,897,264816,0,50913,0,15610
4,NaN,NaN,NaN,NaN,10 a 14,1832805.0,6585,1931,1406555,112308,...,1142,0,11511,522,2696,218430,0,54822,40,16099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161266,NaN,NaN,NaN,NaN,75 a 79,77.0,25,23,0,0,...,0,7,1,0,0,0,2,2,0,0
161267,NaN,NaN,NaN,NaN,80 a 84,50.0,21,12,0,0,...,0,5,0,0,0,0,8,0,0,0
161268,NaN,NaN,NaN,NaN,85 y más,31.0,6,10,0,0,...,0,3,1,0,0,0,6,1,0,0
161269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161270,Fuente: DANE - Censo Nacional de Población y V...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Se cambian los nombres de las columnas restantes por nombres más descriptivos.

In [5]:
df_5_2pm = df_5_2pm.rename(columns={'Unnamed: 1':'Municipio', 'Unnamed: 2':'Sexo', 'Unnamed: 3':'Area', 'Unnamed: 4':'Grupo de edad'})
df_5_2pm

,"sexo, grupos de edad y áreas (Total, Cabecera y Centros poblados y Rural disperso), sexo y grupos de edad",Municipio,Sexo,Area,Grupo de edad,Total,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
0,NaN,NaN,NaN,NaN,NaN,NaN,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
1,Total Nacional,NaN,Hombre,Total,Total,21317034.0,8440991,1494377,8046302,424474,...,15647,47777,417472,9943,103275,1134220,7681,534876,5343,293655
2,NaN,NaN,NaN,NaN,0 a 4,1553300.0,0,0,1150311,22290,...,0,0,1501,122,292,307547,0,53842,0,17395
3,NaN,NaN,NaN,NaN,5 a 9,1697824.0,0,0,1283351,77372,...,0,0,4589,276,897,264816,0,50913,0,15610
4,NaN,NaN,NaN,NaN,10 a 14,1832805.0,6585,1931,1406555,112308,...,1142,0,11511,522,2696,218430,0,54822,40,16099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161266,NaN,NaN,NaN,NaN,75 a 79,77.0,25,23,0,0,...,0,7,1,0,0,0,2,2,0,0
161267,NaN,NaN,NaN,NaN,80 a 84,50.0,21,12,0,0,...,0,5,0,0,0,0,8,0,0,0
161268,NaN,NaN,NaN,NaN,85 y más,31.0,6,10,0,0,...,0,3,1,0,0,0,6,1,0,0
161269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161270,Fuente: DANE - Censo Nacional de Población y V...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Se propagan los identificadores de municipio para filtrar los datos que no corresponden a Viterbo, Caldas.

In [6]:
df_5_2pm['Municipio'] = df_5_2pm['Municipio'].ffill()
df_5_2pm = df_5_2pm.loc[df_5_2pm['Municipio'] == '17877_Viterbo']
df_5_2pm

,"sexo, grupos de edad y áreas (Total, Cabecera y Centros poblados y Rural disperso), sexo y grupos de edad",Municipio,Sexo,Area,Grupo de edad,Total,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
48159,NaN,17877_Viterbo,Hombre,Total,Total,5887.0,2583,149,1895,169,...,6,24,150,6,59,407,6,176,0,127
48160,NaN,17877_Viterbo,NaN,NaN,0 a 4,328.0,0,0,190,3,...,0,0,0,0,0,104,0,19,0,12
48161,NaN,17877_Viterbo,NaN,NaN,5 a 9,372.0,0,0,237,22,...,0,0,0,0,0,85,0,20,0,8
48162,NaN,17877_Viterbo,NaN,NaN,10 a 14,461.0,0,0,290,49,...,2,0,1,0,0,88,0,20,0,11
48163,NaN,17877_Viterbo,NaN,NaN,15 a 19,534.0,15,0,355,38,...,1,0,3,2,4,72,0,27,0,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48268,NaN,17877_Viterbo,NaN,NaN,65 a 69,34.0,10,17,0,0,...,0,2,1,0,0,0,0,1,0,0
48269,NaN,17877_Viterbo,NaN,NaN,70 a 74,25.0,12,7,0,0,...,0,1,3,0,0,0,0,1,0,0
48270,NaN,17877_Viterbo,NaN,NaN,75 a 79,11.0,3,5,0,0,...,0,0,0,0,0,0,0,0,0,0
48271,NaN,17877_Viterbo,NaN,NaN,80 a 84,3.0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
48272,NaN,17877_Viterbo,NaN,NaN,85 y más,4.0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0

Se eliminan columnas que no contienen datos relevantes para el dataset y aquellas que contienen resumenes de datos.

In [7]:
list(df_5_2pm.columns.values)

['sexo, grupos de edad y áreas (Total, Cabecera y Centros poblados y Rural disperso), sexo y grupos de edad',
 'Municipio',
 'Sexo',
 'Area',
 'Grupo de edad',
 'Total',
 'Jefe(a) del hogar',
 'Pareja (Conyuge, compañero(a), esposo(a))',
 'Hijo(a)',
 'Hijastro(a)',
 'Yerno/nuera',
 'Padre/madre',
 'Padrastro, madrastra',
 'Suegro(a)',
 'Hermano(a)',
 'Hermanastro(a)',
 'Cuñado(a)',
 'Nieto(a)',
 'Abuelo(a)',
 'Otro pariente',
 'Empleado(a) del servicio doméstico',
 'No pariente']

In [8]:
df_5_2pm = df_5_2pm.drop(['sexo, grupos de edad y áreas (Total, Cabecera y Centros poblados y Rural disperso), sexo y grupos de edad',
               'Municipio'], axis=1)
df_5_2pm

,Sexo,Area,Grupo de edad,Total,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
48159,Hombre,Total,Total,5887.0,2583,149,1895,169,78,52,6,24,150,6,59,407,6,176,0,127
48160,NaN,NaN,0 a 4,328.0,0,0,190,3,0,0,0,0,0,0,0,104,0,19,0,12
48161,NaN,NaN,5 a 9,372.0,0,0,237,22,0,0,0,0,0,0,0,85,0,20,0,8
48162,NaN,NaN,10 a 14,461.0,0,0,290,49,0,0,2,0,1,0,0,88,0,20,0,11
48163,NaN,NaN,15 a 19,534.0,15,0,355,38,4,0,1,0,3,2,4,72,0,27,0,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48268,NaN,NaN,65 a 69,34.0,10,17,0,0,0,3,0,2,1,0,0,0,0,1,0,0
48269,NaN,NaN,70 a 74,25.0,12,7,0,0,0,1,0,1,3,0,0,0,0,1,0,0
48270,NaN,NaN,75 a 79,11.0,3,5,0,0,1,2,0,0,0,0,0,0,0,0,0,0
48271,NaN,NaN,80 a 84,3.0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
48272,NaN,NaN,85 y más,4.0,1,1,0,0,0,2,0,0,0,0,0,0,0,0,0,0

Se renombran los headers que tienen tildes y ñ.

In [9]:
df_5_2pm = df_5_2pm.rename(columns={'Pareja (Conyuge, compañero(a), esposo(a))':'Pareja (Conyuge, companero(a), esposo(a))',
                         'Cuñado(a)':'Cunado(a)',
                         'Empleado(a) del servicio doméstico':'Empleado(a) del servicio domestico'})
df_5_2pm

,Sexo,Area,Grupo de edad,Total,Jefe(a) del hogar,"Pareja (Conyuge, companero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cunado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio domestico,No pariente
48159,Hombre,Total,Total,5887.0,2583,149,1895,169,78,52,6,24,150,6,59,407,6,176,0,127
48160,NaN,NaN,0 a 4,328.0,0,0,190,3,0,0,0,0,0,0,0,104,0,19,0,12
48161,NaN,NaN,5 a 9,372.0,0,0,237,22,0,0,0,0,0,0,0,85,0,20,0,8
48162,NaN,NaN,10 a 14,461.0,0,0,290,49,0,0,2,0,1,0,0,88,0,20,0,11
48163,NaN,NaN,15 a 19,534.0,15,0,355,38,4,0,1,0,3,2,4,72,0,27,0,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48268,NaN,NaN,65 a 69,34.0,10,17,0,0,0,3,0,2,1,0,0,0,0,1,0,0
48269,NaN,NaN,70 a 74,25.0,12,7,0,0,0,1,0,1,3,0,0,0,0,1,0,0
48270,NaN,NaN,75 a 79,11.0,3,5,0,0,1,2,0,0,0,0,0,0,0,0,0,0
48271,NaN,NaN,80 a 84,3.0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
48272,NaN,NaN,85 y más,4.0,1,1,0,0,0,2,0,0,0,0,0,0,0,0,0,0

Se propagan los valores del area y sexo para reemplazar valores NaN.

In [10]:
df_5_2pm[['Sexo', 'Area']] = df_5_2pm[['Sexo', 'Area']].ffill()
df_5_2pm

,Sexo,Area,Grupo de edad,Total,Jefe(a) del hogar,"Pareja (Conyuge, companero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cunado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio domestico,No pariente
48159,Hombre,Total,Total,5887.0,2583,149,1895,169,78,52,6,24,150,6,59,407,6,176,0,127
48160,Hombre,Total,0 a 4,328.0,0,0,190,3,0,0,0,0,0,0,0,104,0,19,0,12
48161,Hombre,Total,5 a 9,372.0,0,0,237,22,0,0,0,0,0,0,0,85,0,20,0,8
48162,Hombre,Total,10 a 14,461.0,0,0,290,49,0,0,2,0,1,0,0,88,0,20,0,11
48163,Hombre,Total,15 a 19,534.0,15,0,355,38,4,0,1,0,3,2,4,72,0,27,0,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48268,Mujer,Rural disperso,65 a 69,34.0,10,17,0,0,0,3,0,2,1,0,0,0,0,1,0,0
48269,Mujer,Rural disperso,70 a 74,25.0,12,7,0,0,0,1,0,1,3,0,0,0,0,1,0,0
48270,Mujer,Rural disperso,75 a 79,11.0,3,5,0,0,1,2,0,0,0,0,0,0,0,0,0,0
48271,Mujer,Rural disperso,80 a 84,3.0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
48272,Mujer,Rural disperso,85 y más,4.0,1,1,0,0,0,2,0,0,0,0,0,0,0,0,0,0

Se reemplazan las tildes dentro de los datos.

In [11]:
df_5_2pm['Grupo de edad'] = df_5_2pm['Grupo de edad'].str.replace('á', 'a')
df_5_2pm

,Sexo,Area,Grupo de edad,Total,Jefe(a) del hogar,"Pareja (Conyuge, companero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cunado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio domestico,No pariente
48159,Hombre,Total,Total,5887.0,2583,149,1895,169,78,52,6,24,150,6,59,407,6,176,0,127
48160,Hombre,Total,0 a 4,328.0,0,0,190,3,0,0,0,0,0,0,0,104,0,19,0,12
48161,Hombre,Total,5 a 9,372.0,0,0,237,22,0,0,0,0,0,0,0,85,0,20,0,8
48162,Hombre,Total,10 a 14,461.0,0,0,290,49,0,0,2,0,1,0,0,88,0,20,0,11
48163,Hombre,Total,15 a 19,534.0,15,0,355,38,4,0,1,0,3,2,4,72,0,27,0,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48268,Mujer,Rural disperso,65 a 69,34.0,10,17,0,0,0,3,0,2,1,0,0,0,0,1,0,0
48269,Mujer,Rural disperso,70 a 74,25.0,12,7,0,0,0,1,0,1,3,0,0,0,0,1,0,0
48270,Mujer,Rural disperso,75 a 79,11.0,3,5,0,0,1,2,0,0,0,0,0,0,0,0,0,0
48271,Mujer,Rural disperso,80 a 84,3.0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
48272,Mujer,Rural disperso,85 y mas,4.0,1,1,0,0,0,2,0,0,0,0,0,0,0,0,0,0

Se creará una copia del dataframe y se removerán las filas y columnas con resumenes de datos para el csv que no contiene resúmenes.

In [12]:
df_5_2pm_cleaned = df_5_2pm.copy()
df_5_2pm_cleaned.drop(['Total'], axis=1)
df_5_2pm_cleaned

,Sexo,Area,Grupo de edad,Total,Jefe(a) del hogar,"Pareja (Conyuge, companero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cunado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio domestico,No pariente
48159,Hombre,Total,Total,5887.0,2583,149,1895,169,78,52,6,24,150,6,59,407,6,176,0,127
48160,Hombre,Total,0 a 4,328.0,0,0,190,3,0,0,0,0,0,0,0,104,0,19,0,12
48161,Hombre,Total,5 a 9,372.0,0,0,237,22,0,0,0,0,0,0,0,85,0,20,0,8
48162,Hombre,Total,10 a 14,461.0,0,0,290,49,0,0,2,0,1,0,0,88,0,20,0,11
48163,Hombre,Total,15 a 19,534.0,15,0,355,38,4,0,1,0,3,2,4,72,0,27,0,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48268,Mujer,Rural disperso,65 a 69,34.0,10,17,0,0,0,3,0,2,1,0,0,0,0,1,0,0
48269,Mujer,Rural disperso,70 a 74,25.0,12,7,0,0,0,1,0,1,3,0,0,0,0,1,0,0
48270,Mujer,Rural disperso,75 a 79,11.0,3,5,0,0,1,2,0,0,0,0,0,0,0,0,0,0
48271,Mujer,Rural disperso,80 a 84,3.0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
48272,Mujer,Rural disperso,85 y mas,4.0,1,1,0,0,0,2,0,0,0,0,0,0,0,0,0,0

In [13]:
df_5_2pm_cleaned = df_5_2pm_cleaned.loc[(df_5_2pm_cleaned['Area'] != 'Total') & (df_5_2pm_cleaned['Grupo de edad'] != 'Ttoal')]
df_5_2pm_cleaned

,Sexo,Area,Grupo de edad,Total,Jefe(a) del hogar,"Pareja (Conyuge, companero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cunado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio domestico,No pariente
48178,Hombre,Cabecera,Total,4958.0,2137,142,1617,131,69,44,4,18,135,4,43,363,6,141,0,104
48179,Hombre,Cabecera,0 a 4,284.0,0,0,163,2,0,0,0,0,0,0,0,92,0,16,0,11
48180,Hombre,Cabecera,5 a 9,307.0,0,0,197,18,0,0,0,0,0,0,0,73,0,13,0,6
48181,Hombre,Cabecera,10 a 14,373.0,0,0,234,36,0,0,0,0,1,0,0,81,0,14,0,7
48182,Hombre,Cabecera,15 a 19,429.0,8,0,288,26,2,0,1,0,2,1,4,61,0,25,0,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48268,Mujer,Rural disperso,65 a 69,34.0,10,17,0,0,0,3,0,2,1,0,0,0,0,1,0,0
48269,Mujer,Rural disperso,70 a 74,25.0,12,7,0,0,0,1,0,1,3,0,0,0,0,1,0,0
48270,Mujer,Rural disperso,75 a 79,11.0,3,5,0,0,1,2,0,0,0,0,0,0,0,0,0,0
48271,Mujer,Rural disperso,80 a 84,3.0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
48272,Mujer,Rural disperso,85 y mas,4.0,1,1,0,0,0,2,0,0,0,0,0,0,0,0,0,0

Los dataframes están listos para ser exportados a CSV.

In [14]:
df_5_2pm.to_csv(csv_total_path, index=False)
df_5_2pm_cleaned.to_csv(csv_path, index=False)