In [1]:
# imports
import pandas as pd

In [2]:
# Ruta relativa del xslx que contiene los datos
original_data_path = 'Data\\Original\\PERSONAS_DEMOGRAFICO_Cuadros_CNPV_2018.xlsx'

# Nombre del csv objetivo
csv_total_filename = 'caldas_viterbo_total_17PM.csv'
csv_filename = 'caldas_viterbo_17PM.csv'

# Ruta relativa del csv objetivo
csv_total_path = 'Data\\Datasets\\' + csv_total_filename
csv_path = 'Data\\Datasets\\' + csv_filename

In [3]:
# Lee archivo xlsx
df_17pm = pd.read_excel(original_data_path, sheet_name='17PM', skiprows=10)
df_17pm.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Total,Ninguno,Preescolar,Primaria Completa,Primaria Incompleta,Secundaria Completa,Secundaria Incompleta,Media Completa,Media Incompleta,Normal Completa,Normal Incompleta,Tecnico,Tecnologico,Universitario,"Especialización, Maestria, Doctorado",Sin Información
0,Total Nacional,NaN,Total,Hombre,20014888.0,901690.0,480742.0,2430709.0,3640961.0,772887.0,2622111.0,4360995.0,543770.0,11914.0,52938.0,910481.0,480712.0,1910561.0,515152.0,379265.0
1,NaN,NaN,NaN,Mujer,21111748.0,904675.0,444791.0,2462382.0,3479010.0,842107.0,2531297.0,4577752.0,586162.0,33335.0,71657.0,1409025.0,547772.0,2280688.0,622625.0,318470.0
2,NaN,NaN,NaN,Total,41126636.0,1806365.0,925533.0,4893091.0,7119971.0,1614994.0,5153408.0,8938747.0,1129932.0,45249.0,124595.0,2319506.0,1028484.0,4191249.0,1137777.0,697735.0
3,NaN,NaN,Cabecera,Hombre,15188210.0,453775.0,356206.0,1641349.0,2178418.0,599935.0,1941437.0,3676988.0,423818.0,9095.0,44116.0,835206.0,446674.0,1800224.0,491557.0,289412.0
4,NaN,NaN,NaN,Mujer,16699253.0,516839.0,331437.0,1805897.0,2257901.0,660926.0,1918625.0,3859676.0,455804.0,28276.0,61477.0,1284930.0,509705.0,2152782.0,595944.0,259034.0

Se filtrarán los datos que no corresponden al municipio de Viterbo Caldas, para ello se propagará el municipio, el cual se encuentra en la columna "Unnamed: 1" y se seleccionarán solo los registros que contengan el identificador de Viterbo dentro del dataframe, para este caso es "17877_Viterbo".

In [4]:
df_17pm['Unnamed: 1'] = df_17pm['Unnamed: 1'].ffill()
df_17pm = df_17pm.loc[df_17pm['Unnamed: 1'] == '17877_Viterbo']
df_17pm

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Total,Ninguno,Preescolar,Primaria Completa,Primaria Incompleta,Secundaria Completa,Secundaria Incompleta,Media Completa,Media Incompleta,Normal Completa,Normal Incompleta,Tecnico,Tecnologico,Universitario,"Especialización, Maestria, Doctorado",Sin Información
3834,NaN,17877_Viterbo,Total,Hombre,5559.0,304.0,123.0,831.0,1321.0,194.0,857.0,1238.0,139.0,0.0,9.0,122.0,57.0,256.0,57.0,51.0
3835,NaN,17877_Viterbo,NaN,Mujer,6253.0,272.0,130.0,873.0,1293.0,258.0,920.0,1606.0,160.0,6.0,4.0,238.0,60.0,328.0,64.0,41.0
3836,NaN,17877_Viterbo,NaN,Total,11812.0,576.0,253.0,1704.0,2614.0,452.0,1777.0,2844.0,299.0,6.0,13.0,360.0,117.0,584.0,121.0,92.0
3837,NaN,17877_Viterbo,Cabecera,Hombre,4674.0,258.0,97.0,699.0,993.0,168.0,716.0,1116.0,117.0,0.0,9.0,119.0,57.0,232.0,47.0,46.0
3838,NaN,17877_Viterbo,NaN,Mujer,5474.0,251.0,113.0,753.0,1051.0,216.0,790.0,1464.0,138.0,5.0,3.0,229.0,55.0,310.0,57.0,39.0
3839,NaN,17877_Viterbo,NaN,Total,10148.0,509.0,210.0,1452.0,2044.0,384.0,1506.0,2580.0,255.0,5.0,12.0,348.0,112.0,542.0,104.0,85.0
3840,NaN,17877_Viterbo,Rural disperso,Hombre,885.0,46.0,26.0,132.0,328.0,26.0,141.0,122.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,5.0
3841,NaN,17877_Viterbo,NaN,Mujer,779.0,21.0,17.0,120.0,242.0,42.0,130.0,142.0,22.0,1.0,1.0,9.0,5.0,18.0,7.0,2.0
3842,NaN,17877_Viterbo,NaN,Total,1664.0,67.0,43.0,252.0,570.0,68.0,271.0,264.0,44.0,1.0,1.0,12.0,5.0,42.0,17.0,7.0

Se eliminan las columnas con datos irrelevantes.

In [5]:
df_17pm.drop(columns=['Unnamed: 0', 'Unnamed: 1'], inplace=True)
df_17pm

,Unnamed: 2,Unnamed: 3,Total,Ninguno,Preescolar,Primaria Completa,Primaria Incompleta,Secundaria Completa,Secundaria Incompleta,Media Completa,Media Incompleta,Normal Completa,Normal Incompleta,Tecnico,Tecnologico,Universitario,"Especialización, Maestria, Doctorado",Sin Información
3834,Total,Hombre,5559.0,304.0,123.0,831.0,1321.0,194.0,857.0,1238.0,139.0,0.0,9.0,122.0,57.0,256.0,57.0,51.0
3835,NaN,Mujer,6253.0,272.0,130.0,873.0,1293.0,258.0,920.0,1606.0,160.0,6.0,4.0,238.0,60.0,328.0,64.0,41.0
3836,NaN,Total,11812.0,576.0,253.0,1704.0,2614.0,452.0,1777.0,2844.0,299.0,6.0,13.0,360.0,117.0,584.0,121.0,92.0
3837,Cabecera,Hombre,4674.0,258.0,97.0,699.0,993.0,168.0,716.0,1116.0,117.0,0.0,9.0,119.0,57.0,232.0,47.0,46.0
3838,NaN,Mujer,5474.0,251.0,113.0,753.0,1051.0,216.0,790.0,1464.0,138.0,5.0,3.0,229.0,55.0,310.0,57.0,39.0
3839,NaN,Total,10148.0,509.0,210.0,1452.0,2044.0,384.0,1506.0,2580.0,255.0,5.0,12.0,348.0,112.0,542.0,104.0,85.0
3840,Rural disperso,Hombre,885.0,46.0,26.0,132.0,328.0,26.0,141.0,122.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,5.0
3841,NaN,Mujer,779.0,21.0,17.0,120.0,242.0,42.0,130.0,142.0,22.0,1.0,1.0,9.0,5.0,18.0,7.0,2.0
3842,NaN,Total,1664.0,67.0,43.0,252.0,570.0,68.0,271.0,264.0,44.0,1.0,1.0,12.0,5.0,42.0,17.0,7.0

Se renombran los headers sin nombre.

In [6]:
df_17pm.rename(columns={'Unnamed: 2': 'Area', 'Unnamed: 3': 'Sexo'}, inplace=True)
df_17pm

,Area,Sexo,Total,Ninguno,Preescolar,Primaria Completa,Primaria Incompleta,Secundaria Completa,Secundaria Incompleta,Media Completa,Media Incompleta,Normal Completa,Normal Incompleta,Tecnico,Tecnologico,Universitario,"Especialización, Maestria, Doctorado",Sin Información
3834,Total,Hombre,5559.0,304.0,123.0,831.0,1321.0,194.0,857.0,1238.0,139.0,0.0,9.0,122.0,57.0,256.0,57.0,51.0
3835,NaN,Mujer,6253.0,272.0,130.0,873.0,1293.0,258.0,920.0,1606.0,160.0,6.0,4.0,238.0,60.0,328.0,64.0,41.0
3836,NaN,Total,11812.0,576.0,253.0,1704.0,2614.0,452.0,1777.0,2844.0,299.0,6.0,13.0,360.0,117.0,584.0,121.0,92.0
3837,Cabecera,Hombre,4674.0,258.0,97.0,699.0,993.0,168.0,716.0,1116.0,117.0,0.0,9.0,119.0,57.0,232.0,47.0,46.0
3838,NaN,Mujer,5474.0,251.0,113.0,753.0,1051.0,216.0,790.0,1464.0,138.0,5.0,3.0,229.0,55.0,310.0,57.0,39.0
3839,NaN,Total,10148.0,509.0,210.0,1452.0,2044.0,384.0,1506.0,2580.0,255.0,5.0,12.0,348.0,112.0,542.0,104.0,85.0
3840,Rural disperso,Hombre,885.0,46.0,26.0,132.0,328.0,26.0,141.0,122.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,5.0
3841,NaN,Mujer,779.0,21.0,17.0,120.0,242.0,42.0,130.0,142.0,22.0,1.0,1.0,9.0,5.0,18.0,7.0,2.0
3842,NaN,Total,1664.0,67.0,43.0,252.0,570.0,68.0,271.0,264.0,44.0,1.0,1.0,12.0,5.0,42.0,17.0,7.0

Se propagan los valores de las columnas con valores faltantes.

In [7]:
df_17pm['Area'] = df_17pm['Area'].ffill()
df_17pm

,Area,Sexo,Total,Ninguno,Preescolar,Primaria Completa,Primaria Incompleta,Secundaria Completa,Secundaria Incompleta,Media Completa,Media Incompleta,Normal Completa,Normal Incompleta,Tecnico,Tecnologico,Universitario,"Especialización, Maestria, Doctorado",Sin Información
3834,Total,Hombre,5559.0,304.0,123.0,831.0,1321.0,194.0,857.0,1238.0,139.0,0.0,9.0,122.0,57.0,256.0,57.0,51.0
3835,Total,Mujer,6253.0,272.0,130.0,873.0,1293.0,258.0,920.0,1606.0,160.0,6.0,4.0,238.0,60.0,328.0,64.0,41.0
3836,Total,Total,11812.0,576.0,253.0,1704.0,2614.0,452.0,1777.0,2844.0,299.0,6.0,13.0,360.0,117.0,584.0,121.0,92.0
3837,Cabecera,Hombre,4674.0,258.0,97.0,699.0,993.0,168.0,716.0,1116.0,117.0,0.0,9.0,119.0,57.0,232.0,47.0,46.0
3838,Cabecera,Mujer,5474.0,251.0,113.0,753.0,1051.0,216.0,790.0,1464.0,138.0,5.0,3.0,229.0,55.0,310.0,57.0,39.0
3839,Cabecera,Total,10148.0,509.0,210.0,1452.0,2044.0,384.0,1506.0,2580.0,255.0,5.0,12.0,348.0,112.0,542.0,104.0,85.0
3840,Rural disperso,Hombre,885.0,46.0,26.0,132.0,328.0,26.0,141.0,122.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,5.0
3841,Rural disperso,Mujer,779.0,21.0,17.0,120.0,242.0,42.0,130.0,142.0,22.0,1.0,1.0,9.0,5.0,18.0,7.0,2.0
3842,Rural disperso,Total,1664.0,67.0,43.0,252.0,570.0,68.0,271.0,264.0,44.0,1.0,1.0,12.0,5.0,42.0,17.0,7.0

Se modifican los headers que tienen tildes.

In [8]:
df_17pm.columns.values

array(['Area', 'Sexo', 'Total', 'Ninguno', 'Preescolar',
       'Primaria Completa', 'Primaria Incompleta', 'Secundaria Completa',
       'Secundaria Incompleta', 'Media Completa', 'Media Incompleta',
       'Normal Completa', 'Normal Incompleta', 'Tecnico', 'Tecnologico',
       'Universitario', 'Especialización, Maestria, Doctorado',
       'Sin Información '], dtype=object)

In [9]:
df_17pm.rename(columns={'Especialización, Maestria, Doctorado': 'Especializacion, Maestria, Doctorado', 'Sin Información ': 'Sin informacion' }, inplace=True)
df_17pm

,Area,Sexo,Total,Ninguno,Preescolar,Primaria Completa,Primaria Incompleta,Secundaria Completa,Secundaria Incompleta,Media Completa,Media Incompleta,Normal Completa,Normal Incompleta,Tecnico,Tecnologico,Universitario,"Especializacion, Maestria, Doctorado",Sin informacion
3834,Total,Hombre,5559.0,304.0,123.0,831.0,1321.0,194.0,857.0,1238.0,139.0,0.0,9.0,122.0,57.0,256.0,57.0,51.0
3835,Total,Mujer,6253.0,272.0,130.0,873.0,1293.0,258.0,920.0,1606.0,160.0,6.0,4.0,238.0,60.0,328.0,64.0,41.0
3836,Total,Total,11812.0,576.0,253.0,1704.0,2614.0,452.0,1777.0,2844.0,299.0,6.0,13.0,360.0,117.0,584.0,121.0,92.0
3837,Cabecera,Hombre,4674.0,258.0,97.0,699.0,993.0,168.0,716.0,1116.0,117.0,0.0,9.0,119.0,57.0,232.0,47.0,46.0
3838,Cabecera,Mujer,5474.0,251.0,113.0,753.0,1051.0,216.0,790.0,1464.0,138.0,5.0,3.0,229.0,55.0,310.0,57.0,39.0
3839,Cabecera,Total,10148.0,509.0,210.0,1452.0,2044.0,384.0,1506.0,2580.0,255.0,5.0,12.0,348.0,112.0,542.0,104.0,85.0
3840,Rural disperso,Hombre,885.0,46.0,26.0,132.0,328.0,26.0,141.0,122.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,5.0
3841,Rural disperso,Mujer,779.0,21.0,17.0,120.0,242.0,42.0,130.0,142.0,22.0,1.0,1.0,9.0,5.0,18.0,7.0,2.0
3842,Rural disperso,Total,1664.0,67.0,43.0,252.0,570.0,68.0,271.0,264.0,44.0,1.0,1.0,12.0,5.0,42.0,17.0,7.0

Se creará una copia del dataframe y se removerán las filas y columnas con resumenes de datos para el csv que no contiene resúmenes.

In [10]:
df_17pm_cleaned = df_17pm.copy()
df_17pm_cleaned.drop(['Total'], axis=1, inplace=True)
df_17pm_cleaned

,Area,Sexo,Ninguno,Preescolar,Primaria Completa,Primaria Incompleta,Secundaria Completa,Secundaria Incompleta,Media Completa,Media Incompleta,Normal Completa,Normal Incompleta,Tecnico,Tecnologico,Universitario,"Especializacion, Maestria, Doctorado",Sin informacion
3834,Total,Hombre,304.0,123.0,831.0,1321.0,194.0,857.0,1238.0,139.0,0.0,9.0,122.0,57.0,256.0,57.0,51.0
3835,Total,Mujer,272.0,130.0,873.0,1293.0,258.0,920.0,1606.0,160.0,6.0,4.0,238.0,60.0,328.0,64.0,41.0
3836,Total,Total,576.0,253.0,1704.0,2614.0,452.0,1777.0,2844.0,299.0,6.0,13.0,360.0,117.0,584.0,121.0,92.0
3837,Cabecera,Hombre,258.0,97.0,699.0,993.0,168.0,716.0,1116.0,117.0,0.0,9.0,119.0,57.0,232.0,47.0,46.0
3838,Cabecera,Mujer,251.0,113.0,753.0,1051.0,216.0,790.0,1464.0,138.0,5.0,3.0,229.0,55.0,310.0,57.0,39.0
3839,Cabecera,Total,509.0,210.0,1452.0,2044.0,384.0,1506.0,2580.0,255.0,5.0,12.0,348.0,112.0,542.0,104.0,85.0
3840,Rural disperso,Hombre,46.0,26.0,132.0,328.0,26.0,141.0,122.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,5.0
3841,Rural disperso,Mujer,21.0,17.0,120.0,242.0,42.0,130.0,142.0,22.0,1.0,1.0,9.0,5.0,18.0,7.0,2.0
3842,Rural disperso,Total,67.0,43.0,252.0,570.0,68.0,271.0,264.0,44.0,1.0,1.0,12.0,5.0,42.0,17.0,7.0

In [11]:
df_17pm_cleaned = df_17pm_cleaned.loc[(df_17pm_cleaned['Area'] != 'Total') & (df_17pm_cleaned['Sexo'] != 'Total')]
df_17pm_cleaned

,Area,Sexo,Ninguno,Preescolar,Primaria Completa,Primaria Incompleta,Secundaria Completa,Secundaria Incompleta,Media Completa,Media Incompleta,Normal Completa,Normal Incompleta,Tecnico,Tecnologico,Universitario,"Especializacion, Maestria, Doctorado",Sin informacion
3837,Cabecera,Hombre,258.0,97.0,699.0,993.0,168.0,716.0,1116.0,117.0,0.0,9.0,119.0,57.0,232.0,47.0,46.0
3838,Cabecera,Mujer,251.0,113.0,753.0,1051.0,216.0,790.0,1464.0,138.0,5.0,3.0,229.0,55.0,310.0,57.0,39.0
3840,Rural disperso,Hombre,46.0,26.0,132.0,328.0,26.0,141.0,122.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,5.0
3841,Rural disperso,Mujer,21.0,17.0,120.0,242.0,42.0,130.0,142.0,22.0,1.0,1.0,9.0,5.0,18.0,7.0,2.0

Los dataframes están listos para ser exportados a CSV.

In [12]:
df_17pm.to_csv(csv_total_path, index=False)
df_17pm_cleaned.to_csv(csv_path, index=False)