In [36]:
# imports
import pandas as pd

In [89]:
# Ruta relativa del xslx que contiene los datos
original_data_path = 'Data\\Original\\PERSONAS_DEMOGRAFICO_Cuadros_CNPV_2018.xlsx'

# Nombre del csv objetivo
csv_filename = 'caldas_viterbo_14PM.csv'

# Ruta relativa del csv objetivo
csv_path = 'Data\\Datasets\\' + csv_filename

In [80]:
# Lee archivo xlsx
df_14pm = pd.read_excel(original_data_path, sheet_name='14PM', skiprows=8)
df_14pm.head()

,2018,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70
0,"Departamento, áreas (Total, Cabecera y Centros...",NaN,NaN,NaN,Total,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,Total personas,Tuvo alguna enfermedad en los últimos 30 días,NaN,NaN,NaN,Servicio de salud donde acudieron,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,Sí,No,Sin información,NaN,Total personas que tuvieron alguna enfermedad,...,Sin información,A la entidad de seguridad social en salud a la...,A un médico particular,"A un boticario,farmacéuta, droguista",A terapias alternativas,Acudió a una autoridad indígena espiritual,Otro médico de un grupo étnico,Usó remedios caseros,Se autorrecetó,No hizo nada
3,Total Nacional,NaN,Total,Total,43835324,4528062,38844425,462837,NaN,4528062,...,4871,484428,46684,25065,1525,3662,3129,72704,28382,22822
4,NaN,NaN,NaN,0-4 años,3033307,334952,2666796,31559,NaN,334952,...,573,34658,3194,2179,55,524,310,6967,2318,1032

In [81]:
first_row = list(df_14pm.iloc[0])[:]
for (i, value) in enumerate(first_row):
    print(i, value)

0 Departamento, áreas (Total, Cabecera y Centros poblados y Rural disperso), sexo y grupos de edad
1 nan
2 nan
3 nan
4 Total
5 nan
6 nan
7 nan
8 nan
9 nan
10 nan
11 nan
12 nan
13 nan
14 nan
15 nan
16 nan
17 nan
18 nan
19 nan
20 nan
21 Cabecera
22 nan
23 nan
24 nan
25 nan
26 nan
27 nan
28 nan
29 nan
30 nan
31 nan
32 nan
33 nan
34 nan
35 nan
36 nan
37 nan
38 Centro poblado
39 nan
40 nan
41 nan
42 nan
43 nan
44 nan
45 nan
46 nan
47 nan
48 nan
49 nan
50 nan
51 nan
52 nan
53 nan
54 nan
55 Rural disperso
56 nan
57 nan
58 nan
59 nan
60 nan
61 nan
62 nan
63 nan
64 nan
65 nan
66 nan
67 nan
68 nan
69 nan
70 nan

In [82]:
second_row = list(df_14pm.iloc[1])[:]
for (i, value) in enumerate(second_row):
    print(i, value)

0 nan
1 nan
2 nan
3 nan
4 Total personas
5 Tuvo alguna enfermedad en los últimos 30 días
6 nan
7 nan
8 nan
9 Servicio de salud donde acudieron
10 nan
11 nan
12 nan
13 nan
14 nan
15 nan
16 nan
17 nan
18 nan
19 nan
20 nan
21 Total personas
22 Tuvo alguna enfermedad en los últimos 30 días
23 nan
24 nan
25 nan
26 Servicio de salud donde acudieron
27 nan
28 nan
29 nan
30 nan
31 nan
32 nan
33 nan
34 nan
35 nan
36 nan
37 nan
38 Total personas
39 Tuvo alguna enfermedad en los últimos 30 días
40 nan
41 nan
42 nan
43 Servicio de salud donde acudieron
44 nan
45 nan
46 nan
47 nan
48 nan
49 nan
50 nan
51 nan
52 nan
53 nan
54 nan
55 Total personas
56 Tuvo alguna enfermedad en los últimos 30 días
57 nan
58 nan
59 nan
60 Servicio de salud donde acudieron
61 nan
62 nan
63 nan
64 nan
65 nan
66 nan
67 nan
68 nan
69 nan
70 nan

In [83]:
third_row = list(df_14pm.iloc[2])[:]
for (i, value) in enumerate(third_row):
    print(i, value)

0 nan
1 nan
2 nan
3 nan
4 nan
5 Sí
6 No
7 Sin información
8 nan
9 Total personas que tuvieron alguna enfermedad
10 Sin información
11 A la entidad de seguridad social en salud a la cual está afliado(a)
12 A un médico particular
13 A un boticario,farmacéuta, droguista
14 A terapias alternativas
15 Acudió a una autoridad indígena espiritual
16 Otro médico de un grupo étnico
17 Usó remedios caseros
18 Se autorrecetó
19 No hizo nada
20 nan
21 nan
22 Sí
23 No
24 Sin información
25 nan
26 Total personas que tuvieron alguna enfermedad
27 Sin información
28 A la entidad de seguridad social en salud a la cual está afliado(a)
29 A un médico particular
30 A un boticario,farmacéuta, droguista
31 A terapias alternativas
32 Acudió a una autoridad indígena espiritual
33 Otro médico de un grupo étnico
34 Usó remedios caseros
35 Se autorrecetó
36 No hizo nada
37 nan
38 nan
39 Sí
40 No
41 Sin información
42 nan
43 Total personas que tuvieron alguna enfermedad
44 Sin información
45 A la entidad de seguridad social en salud a la cual está afliado(a)
46 A un médico particular
47 A un boticario,farmacéuta, droguista
48 A terapias alternativas
49 Acudió a una autoridad indígena espiritual
50 Otro médico de un grupo étnico
51 Usó remedios caseros
52 Se autorrecetó
53 No hizo nada
54 nan
55 nan
56 Sí
57 No
58 Sin información
59 nan
60 Total personas que tuvieron alguna enfermedad
61 Sin información
62 A la entidad de seguridad social en salud a la cual está afliado(a)
63 A un médico particular
64 A un boticario,farmacéuta, droguista
65 A terapias alternativas
66 Acudió a una autoridad indígena espiritual
67 Otro médico de un grupo étnico
68 Usó remedios caseros
69 Se autorrecetó
70 No hizo nada

Se observan secciones altamente agrupadas en columnas con subcolumnas, y estas subcolumnas tienen a su vez otras subcolumnas.
El primer subgrupo de columnas correspondientes a "Tuvo alguna enfermedad en los últimos 30 días" y "Servicio de salud donde acudieron" se puede eliminar al modificar algunos nombres de las subcolumnas con mayor granularidad y documentar. En este caso, si se utilizan las columnas con más granularidad, se tienen dos columnas con el mismo nombre "Sin información" y que no se pueden ignorar en el proceso de extracción de datos.

In [84]:
actual_headers = list(df_14pm.iloc[2][5:19])
del actual_headers[3]
actual_headers[2] = "Sin informacion enfermedad ultimos 30 dias"
actual_headers[4] = "Sin informacion servicio de salud donde acudieron"
actual_headers

['Sí',
 'No',
 'Sin informacion enfermedad ultimos 30 dias',
 'Total personas que tuvieron alguna enfermedad',
 'Sin informacion servicio de salud donde acudieron',
 'A la entidad de seguridad social en salud a la cual está afliado(a)',
 'A un médico particular',
 'A un boticario,farmacéuta, droguista',
 'A terapias alternativas',
 'Acudió a una autoridad indígena espiritual',
 'Otro médico de un grupo étnico',
 'Usó remedios caseros',
 'Se autorrecetó']

Se extraen las columnas con mayor granularidad.

Se filtrarán los datos que no corresponden al municipio de Viterbo Caldas, para ello se propagará el municipio, el cual se encuentra en la columna "Unnamed: 1" y se seleccionarán solo los registros que contengan el identificador de Viterbo dentro del dataframe, para este caso es "17877_Viterbo".

In [85]:
df_14pm['Unnamed: 1'] = df_14pm['Unnamed: 1'].ffill()
df_14pm = df_14pm.loc[df_14pm['Unnamed: 1'] == '17877_Viterbo']
df_14pm

,2018,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70
19668,NaN,17877_Viterbo,Total,Total,12425,1389,10976,60,NaN,1389,...,0,125,15,16,0,0,0,9,6,0
19669,NaN,17877_Viterbo,NaN,0-4 años,616,61,552,3,NaN,61,...,0,3,0,1,0,0,0,1,0,0
19670,NaN,17877_Viterbo,NaN,5-9 años,742,52,689,1,NaN,52,...,0,5,0,1,0,0,0,2,1,0
19671,NaN,17877_Viterbo,NaN,10-14 años,941,45,893,3,NaN,45,...,0,5,1,1,0,0,0,0,0,0
19672,NaN,17877_Viterbo,NaN,15-19 años,1070,66,999,5,NaN,66,...,0,7,1,0,0,0,0,1,0,0
19673,NaN,17877_Viterbo,NaN,20-24 años,958,50,898,10,NaN,50,...,0,4,0,1,0,0,0,0,1,0
19674,NaN,17877_Viterbo,NaN,25-29 años,855,78,771,6,NaN,78,...,0,6,7,2,0,0,0,2,0,0
19675,NaN,17877_Viterbo,NaN,30-34 años,779,71,703,5,NaN,71,...,0,0,2,0,0,0,0,0,0,0
19676,NaN,17877_Viterbo,NaN,35-39 años,840,70,767,3,NaN,70,...,0,5,0,0,0,0,0,1,0,0
19677,NaN,17877_Viterbo,NaN,40-44 años,747,85,655,7,NaN,85,...,0,10,1,1,0,0,0,0,3,0
19678,NaN,17877_Viterbo,NaN,45-49 años,852,101,748,3,NaN,101,...,0,18,0,1,0,0,0,0,0,0
19679,NaN,17877_Viterbo,NaN,50-54 años,846,102,737,7,NaN,102,...,0,10,0,1,0,0,0,0,0,0
19680,NaN,17877_Viterbo,NaN,55-59 años,785,123,662,0,NaN,123,...,0,11,0,1,0,0,0,2,1,0
19681,NaN,17877_Viterbo,NaN,60-64 años,650,118,528,4,NaN,118,...,0,11,0,1,0,0,0,0,0,0
19682,NaN,17877_Viterbo,NaN,65-69 años,573,102,469,2,NaN,102,...,0,10,1,3,0,0,0,0,0,0
19683,NaN,17877_Viterbo,NaN,70-74 años,434,79,355,0,NaN,79,...,0,7,0,1,0,0,0,0,0,0
19684,NaN,17877_Viterbo,NaN,75-79 años,352,86,266,0,NaN,86,...,0,7,0,1,0,0,0,0,0,0
19685,NaN,17877_Viterbo,NaN,80-84 años,212,54,158,0,NaN,54,...,0,1,1,0,0,0,0,0,0,0
19686,NaN,17877_Viterbo,NaN,85 años y más,173,46,126,1,NaN,46,...,0,5,1,0,0,0,0,0,0,0
19687,NaN,17877_Viterbo,Hombres,Total,5887,634,5222,31,NaN,634,...,0,77,9,6,0,0,0,3,2,0
19688,NaN,17877_Viterbo,NaN,0-4 años,328,37,289,2,NaN,37,...,0,3,0,0,0,0,0,0,0,0
19689,NaN,17877_Viterbo,NaN,5-9 años,372,28,343,1,NaN,28,...,0,3,0,1,0,0,0,0,0,0
19690,NaN,17877_Viterbo,NaN,10-14 años,461,20,440,1,NaN,20,...,0,1,0,0,0,0,0,0,0,0
19691,NaN,17877_Viterbo,NaN,15-19 años,534,31,500,3,NaN,31,...,0,3,1,0,0,0,0,1,0,0
19692,NaN,17877_Viterbo,NaN,20-24 años,448,23,419,6,NaN,23,...,0,3,0,0,0,0,0,0,1,0
19693,NaN,17877_Viterbo,NaN,25-29 años,423,39,382,2,NaN,39,...,0,5,4,1,0,0,0,2,0,0
19694,NaN,17877_Viterbo,NaN,30-34 años,360,31,325,4,NaN,31,...,0,0,1,0,0,0,0,0,0,0
19695,NaN,17877_Viterbo,NaN,35-39 años,392,27,364,1,NaN,27,...,0,3,0,0,0,0,0,0,0,0
19696,NaN,17877_Viterbo,NaN,40-44 años,338,37,298,3,NaN,37,...,0,6,1,0,0,0,0,0,0,0
19697,NaN,17877_Viterbo,NaN,45-49 años,388,38,349,1,NaN,38,...,0,12,0,0,0,0,0,0,0,0
19698,NaN,17877_Viterbo,NaN,50-54 años,383,39,341,3,NaN,39,...,0,5,0,0,0,0,0,0,0,0
19699,NaN,17877_Viterbo,NaN,55-59 años,345,51,294,0,NaN,51,...,0,5,0,1,0,0,0,0,1,0
19700,NaN,17877_Viterbo,NaN,60-64 años,322,57,262,3,NaN,57,...,0,8,0,0,0,0,0,0,0,0
19701,NaN,17877_Viterbo,NaN,65-69 años,266,45,220,1,NaN,45,...,0,6,0,1,0,0,0,0,0,0
19702,NaN,17877_Viterbo,NaN,70-74 años,193,43,150,0,NaN,43,...,0,5,0,1,0,0,0,0,0,0
19703,NaN,17877_Viterbo,NaN,75-79 años,149,41,108,0,NaN,41,...,0,4,0,1,0,0,0,0,0,0
19704,NaN,17877_Viterbo,NaN,80-84 años,98,24,74,0,NaN,24,...,0,1,1,0,0,0,0,0,0,0
19705,NaN,17877_Viterbo,NaN,85 años y más,87,23,64,0,NaN,23,...,0,4,1,0,0,0,0,0,0,0
19706,NaN,17877_Viterbo,Mujeres,Total,6538,755,5754,29,NaN,755,...,0,48,6,10,0,0,0,6,4,0
19707,NaN,17877_Viterbo,NaN,0-4 años,288,24,263,1,NaN,24,...,0,0,0,1,0,0,0,1,0,0
19708,NaN,17877_Viterbo,NaN,5-9 años,370,24,346,0,NaN,24,...,0,2,0,0,0,0,0,2,1,0
19709,NaN,17877_Viterbo,NaN,10-14 años,480,25,453,2,NaN,25,...,0,4,1,1,0,0,0,0,0,0
19710,NaN,17877_Viterbo,NaN,15-19 años,536,35,499,2,NaN,35,...,0,4,0,0,0,0,0,0,0,0
19711,NaN,17877_Viterbo,NaN,20-24 años,510,27,479,4,NaN,27,...,0,1,0,1,0,0,0,0,0,0
19712,NaN,17877_Viterbo,NaN,25-29 años,432,39,389,4,NaN,39,...,0,1,3,1,0,0,0,0,0,0
19713,NaN,17877_Viterbo,NaN,30-34 años,419,40,378,1,NaN,40,...,0,0,1,0,0,0,0,0,0,0
19714,NaN,17877_Viterbo,NaN,35-39 años,448,43,403,2,NaN,43,...,0,2,0,0,0,0,0,1,0,0
19715,NaN,17877_Viterbo,NaN,40-44 años,409,48,357,4,NaN,48,...,0,4,0,1,0,0,0,0,3,0
19716,NaN,17877_Viterbo,NaN,45-49 años,464,63,399,2,NaN,63,...,0,6,0,1,0,0,0,0,0,0
19717,NaN,17877_Viterbo,NaN,50-54 años,463,63,396,4,NaN,63,...,0,5,0,1,0,0,0,0,0,0
19718,NaN,17877_Viterbo,NaN,55-59 años,440,72,368,0,NaN,72,...,0,6,0,0,0,0,0,2,0,0
19719,NaN,17877_Viterbo,NaN,60-64 años,328,61,266,1,NaN,61,...,0,3,0,1,0,0,0,0,0,0
19720,NaN,17877_Viterbo,NaN,65-69 años,307,57,249,1,NaN,57,...,0,4,1,2,0,0,0,0,0,0
19721,NaN,17877_Viterbo,NaN,70-74 años,241,36,205,0,NaN,36,...,0,2,0,0,0,0,0,0,0,0
19722,NaN,17877_Viterbo,NaN,75-79 años,203,45,158,0,NaN,45,...,0,3,0,0,0,0,0,0,0,0
19723,NaN,17877_Viterbo,NaN,80-84 años,114,30,84,0,NaN,30,...,0,0,0,0,0,0,0,0,0,0
19724,NaN,17877_Viterbo,NaN,85 años y más,86,23,62,1,NaN,23,...,0,1,0,0,0,0,0,0,0,0

Debido a la agrupación de columnas por área, se separan los datos por subconjuntos dependiendo del área y al final serán reunidos en un mismo dataframe con el área presente en las filas, se eliminan columnas con resumenes de datos, aka totales.

In [86]:
ls_df = []
area_type = ['cabecera', 'centro_poblado', 'rural_disperso']
for i, area in zip(range(22, 70, 17), area_type):
    df_14pm_with_area = pd.concat([df_14pm[['Unnamed: 2', 'Unnamed: 3']], df_14pm.iloc[:,i:i+14].assign(Area=area)], axis=1)
    df_14pm_with_area.drop(df_14pm_with_area.columns[5], axis=1, inplace=True)
    ls_df.append(df_14pm_with_area)

for df in ls_df:
    df.rename(columns=dict(zip(list(df.columns.values[2:-1]), actual_headers[:])), inplace=True)

df_14pm = pd.concat(ls_df)
df_14pm.rename(columns={'Unnamed: 2': 'Sexo', 'Unnamed: 3': 'Grupo de edad'}, inplace=True)
df_14pm

,Sexo,Grupo de edad,Sí,No,Sin informacion enfermedad ultimos 30 dias,Total personas que tuvieron alguna enfermedad,Sin informacion servicio de salud donde acudieron,A la entidad de seguridad social en salud a la cual está afliado(a),A un médico particular,"A un boticario,farmacéuta, droguista",A terapias alternativas,Acudió a una autoridad indígena espiritual,Otro médico de un grupo étnico,Usó remedios caseros,Se autorrecetó,Area
19668,Total,Total,1218,9391,55,1218,1,1006,59,64,1,0,1,32,15,cabecera
19669,NaN,0-4 años,56,460,3,56,0,43,7,4,0,0,0,2,0,cabecera
19670,NaN,5-9 años,43,576,1,43,1,37,1,0,0,0,0,3,0,cabecera
19671,NaN,10-14 años,38,738,3,38,0,30,0,2,0,0,0,3,2,cabecera
19672,NaN,15-19 años,57,821,5,57,0,44,5,3,0,0,0,1,1,cabecera
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19720,NaN,65-69 años,7,27,0,7,0,4,1,2,0,0,0,0,0,rural_disperso
19721,NaN,70-74 años,2,23,0,2,0,2,0,0,0,0,0,0,0,rural_disperso
19722,NaN,75-79 años,3,8,0,3,0,3,0,0,0,0,0,0,0,rural_disperso
19723,NaN,80-84 años,0,3,0,0,0,0,0,0,0,0,0,0,0,rural_disperso
19724,NaN,85 años y más,1,3,0,1,0,1,0,0,0,0,0,0,0,rural_disperso

Se propaga el valor de la columna 'Sexo' para completar los datos faltantes.

In [87]:
df_14pm['Sexo'] = df_14pm['Sexo'].ffill()
df_14pm

,Sexo,Grupo de edad,Sí,No,Sin informacion enfermedad ultimos 30 dias,Total personas que tuvieron alguna enfermedad,Sin informacion servicio de salud donde acudieron,A la entidad de seguridad social en salud a la cual está afliado(a),A un médico particular,"A un boticario,farmacéuta, droguista",A terapias alternativas,Acudió a una autoridad indígena espiritual,Otro médico de un grupo étnico,Usó remedios caseros,Se autorrecetó,Area
19668,Total,Total,1218,9391,55,1218,1,1006,59,64,1,0,1,32,15,cabecera
19669,Total,0-4 años,56,460,3,56,0,43,7,4,0,0,0,2,0,cabecera
19670,Total,5-9 años,43,576,1,43,1,37,1,0,0,0,0,3,0,cabecera
19671,Total,10-14 años,38,738,3,38,0,30,0,2,0,0,0,3,2,cabecera
19672,Total,15-19 años,57,821,5,57,0,44,5,3,0,0,0,1,1,cabecera
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19720,Mujeres,65-69 años,7,27,0,7,0,4,1,2,0,0,0,0,0,rural_disperso
19721,Mujeres,70-74 años,2,23,0,2,0,2,0,0,0,0,0,0,0,rural_disperso
19722,Mujeres,75-79 años,3,8,0,3,0,3,0,0,0,0,0,0,0,rural_disperso
19723,Mujeres,80-84 años,0,3,0,0,0,0,0,0,0,0,0,0,0,rural_disperso
19724,Mujeres,85 años y más,1,3,0,1,0,1,0,0,0,0,0,0,0,rural_disperso

Se renombran los headers que tienen tildes y ñ.

In [ ]:
df_14pm.rename(columns={'Sí': 'Si',
 'A la entidad de seguridad social en salud a la cual está afliado(a)': 'A la entidad de seguridad social en salud a la cual esta afliado(a)',
 'A un médico particular': 'A un medico particular',
 'A un boticario,farmacéuta, droguista': 'A un boticario,farmaceuta, droguista',
 'Acudió a una autoridad indígena espiritual': 'Acudio a una autoridad indigena espiritual',
 'Otro médico de un grupo étnico': 'Otro medico de un grupo etnico',
 'Usó remedios caseros': 'Uso remedios caseros',
 'Se autorrecetó': 'Se autorreceto'}, inplace=True)

df_14pm

,Sexo,Grupo de edad,Si,No,Sin informacion enfermedad ultimos 30 dias,Total personas que tuvieron alguna enfermedad,Sin informacion servicio de salud donde acudieron,A la entidad de seguridad social en salud a la cual esta afliado(a),A un medico particular,"A un boticario,farmaceuta, droguista",A terapias alternativas,Acudio a una autoridad indigena espiritual,Otro medico de un grupo etnico,Uso remedios caseros,Se autorreceto,Area
19668,Total,Total,1218,9391,55,1218,1,1006,59,64,1,0,1,32,15,cabecera
19669,Total,0-4 años,56,460,3,56,0,43,7,4,0,0,0,2,0,cabecera
19670,Total,5-9 años,43,576,1,43,1,37,1,0,0,0,0,3,0,cabecera
19671,Total,10-14 años,38,738,3,38,0,30,0,2,0,0,0,3,2,cabecera
19672,Total,15-19 años,57,821,5,57,0,44,5,3,0,0,0,1,1,cabecera
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19720,Mujeres,65-69 años,7,27,0,7,0,4,1,2,0,0,0,0,0,rural_disperso
19721,Mujeres,70-74 años,2,23,0,2,0,2,0,0,0,0,0,0,0,rural_disperso
19722,Mujeres,75-79 años,3,8,0,3,0,3,0,0,0,0,0,0,0,rural_disperso
19723,Mujeres,80-84 años,0,3,0,0,0,0,0,0,0,0,0,0,0,rural_disperso
19724,Mujeres,85 años y más,1,3,0,1,0,1,0,0,0,0,0,0,0,rural_disperso

Se cambian los datos que contienen tildes y ñ.

In [91]:
replacements = str.maketrans({'ñ':'ni', 'á':'a'})
df_14pm.loc[:,'Grupo de edad'] = df_14pm['Grupo de edad'].str.translate(replacements)
df_14pm

,Sexo,Grupo de edad,Si,No,Sin informacion enfermedad ultimos 30 dias,Total personas que tuvieron alguna enfermedad,Sin informacion servicio de salud donde acudieron,A la entidad de seguridad social en salud a la cual esta afliado(a),A un medico particular,"A un boticario,farmaceuta, droguista",A terapias alternativas,Acudio a una autoridad indigena espiritual,Otro medico de un grupo etnico,Uso remedios caseros,Se autorreceto,Area
19668,Total,Total,1218,9391,55,1218,1,1006,59,64,1,0,1,32,15,cabecera
19669,Total,0-4 anios,56,460,3,56,0,43,7,4,0,0,0,2,0,cabecera
19670,Total,5-9 anios,43,576,1,43,1,37,1,0,0,0,0,3,0,cabecera
19671,Total,10-14 anios,38,738,3,38,0,30,0,2,0,0,0,3,2,cabecera
19672,Total,15-19 anios,57,821,5,57,0,44,5,3,0,0,0,1,1,cabecera
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19720,Mujeres,65-69 anios,7,27,0,7,0,4,1,2,0,0,0,0,0,rural_disperso
19721,Mujeres,70-74 anios,2,23,0,2,0,2,0,0,0,0,0,0,0,rural_disperso
19722,Mujeres,75-79 anios,3,8,0,3,0,3,0,0,0,0,0,0,0,rural_disperso
19723,Mujeres,80-84 anios,0,3,0,0,0,0,0,0,0,0,0,0,0,rural_disperso
19724,Mujeres,85 anios y mas,1,3,0,1,0,1,0,0,0,0,0,0,0,rural_disperso

El dataframe está listo para ser exportado a CSV.

In [92]:
df_14pm.to_csv(csv_path, index=False)