In [1]:
# imports
import pandas as pd

In [2]:
# Ruta relativa del xslx que contiene los datos
original_data_path = 'Data\\Original\\PERSONAS_DEMOGRAFICO_Cuadros_CNPV_2018.xlsx'

# Nombre del csv objetivo
csv_total_filename = 'caldas_viterbo_total_16PM.csv'
csv_filename = 'caldas_viterbo_16PM.csv'

# Ruta relativa del csv objetivo
csv_total_path = 'Data\\Datasets\\' + csv_total_filename
csv_path = 'Data\\Datasets\\' + csv_filename

In [4]:
# Lee archivo xlsx
df_16pm = pd.read_excel(original_data_path, sheet_name='16PM', skiprows=9)
df_16pm.head()

,"Departamento, municipio, áreas (Total, Cabecera y Centros poblados y Rural disperso), sexo y grupo edades",Unnamed: 1,Unnamed: 2,Unnamed: 3,Sabe leer y escribir,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,NaN,NaN,NaN,Total,NaN,NaN,NaN,Si,NaN,NaN,NaN,No,NaN,NaN,NaN,Sin información,NaN,NaN
1,NaN,NaN,NaN,NaN,Total,Hombre,Mujer,NaN,Total,Hombre,Mujer,NaN,Total,Hombre,Mujer,NaN,Total,Hombre,Mujer
2,Total Nacional,NaN,Total,De 5 años y más,40802017,19763734,21038283,NaN,37872479,18279901,19592578,NaN,2432568,1236330,1196238,NaN,496970,247503,249467
3,NaN,NaN,NaN,De 15 años y más,33902671,16233105,17669566,NaN,31784478,15182231,16602247,NaN,1729239,858479,870760,NaN,388954,192395,196559
4,NaN,NaN,NaN,Entre 15 y 24 años,7675817,3855473,3820344,NaN,7473797,3740551,3733246,NaN,111918,68125,43793,NaN,90102,46797,43305

In [5]:
first_row = list(df_16pm.iloc[0])[:]
for (i, value) in enumerate(first_row):
    print(i, value)

0 nan
1 nan
2 nan
3 nan
4 Total
5 nan
6 nan
7 nan
8 Si
9 nan
10 nan
11 nan
12 No
13 nan
14 nan
15 nan
16 Sin información
17 nan
18 nan

In [6]:
second_row = list(df_16pm.iloc[1])[:]
for (i, value) in enumerate(second_row):
    print(i, value)

0 nan
1 nan
2 nan
3 nan
4 Total
5 Hombre
6 Mujer
7 nan
8 Total
9 Hombre
10 Mujer
11 nan
12 Total
13 Hombre
14 Mujer
15 nan
16 Total
17 Hombre
18 Mujer

Se observan columnas y subcolumnas, se dividirán en diferentes datasets, se asignará una nueva columna "Sabe leer y escribir" y se asignaran los valores correspondientes desagrupando el dataframe en este item, y se unirán los diferentes dataframes.

In [7]:
actual_headers = list(df_16pm.iloc[1][4:])
cleaned_headers = [x for x in actual_headers if not pd.isnull(x)]
cleaned_headers

['Total',
 'Hombre',
 'Mujer',
 'Total',
 'Hombre',
 'Mujer',
 'Total',
 'Hombre',
 'Mujer',
 'Total',
 'Hombre',
 'Mujer']

Se filtrarán los datos que no corresponden al municipio de Viterbo Caldas, para ello se propagará el municipio, el cual se encuentra en la columna "Unnamed: 1" y se seleccionarán solo los registros que contengan el identificador de Viterbo dentro del dataframe, para este caso es "17877_Viterbo".

In [8]:
df_16pm['Unnamed: 1'] = df_16pm['Unnamed: 1'].ffill()
df_16pm = df_16pm.loc[df_16pm['Unnamed: 1'] == '17877_Viterbo']
df_16pm

,"Departamento, municipio, áreas (Total, Cabecera y Centros poblados y Rural disperso), sexo y grupo edades",Unnamed: 1,Unnamed: 2,Unnamed: 3,Sabe leer y escribir,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
3836,NaN,17877_Viterbo,Total,De 5 años y más,11809,5559,6250,NaN,10859,5052,5807,NaN,890,474,416,NaN,60,33,27
3837,NaN,17877_Viterbo,NaN,De 15 años y más,10126,4726,5400,NaN,9376,4318,5058,NaN,699,381,318,NaN,51,27,24
3838,NaN,17877_Viterbo,NaN,Entre 15 y 24 años,2028,982,1046,NaN,1980,948,1032,NaN,33,25,8,NaN,15,9,6
3839,NaN,17877_Viterbo,Cabecera,De 5 años y más,10145,4674,5471,NaN,9339,4263,5076,NaN,752,382,370,NaN,54,29,25
3840,NaN,17877_Viterbo,NaN,De 15 años y más,8746,3994,4752,NaN,8107,3666,4441,NaN,593,304,289,NaN,46,24,22
3841,NaN,17877_Viterbo,NaN,Entre 15 y 24 años,1718,820,898,NaN,1676,791,885,NaN,27,20,7,NaN,15,9,6
3842,NaN,17877_Viterbo,Rural disperso,De 5 años y más,1664,885,779,NaN,1520,789,731,NaN,138,92,46,NaN,6,4,2
3843,NaN,17877_Viterbo,NaN,De 15 años y más,1380,732,648,NaN,1269,652,617,NaN,106,77,29,NaN,5,3,2
3844,NaN,17877_Viterbo,NaN,Entre 15 y 24 años,310,162,148,NaN,304,157,147,NaN,6,5,1,NaN,0,0,0

Debido a la agrupación de columnas por capacidad de leer y escribir, se separan los datos por subconjuntos dependiendo si los censados saben leer y escribir y al final serán reunidos en un mismo dataframe con el valor presente en las filas.

In [9]:
ls_df = []
literate = ['total', 'si', 'no', 'sin_informacion']
for i, literate_status in zip(range(4, 19, 4), literate):
    df_16pm_with_literate_status = pd.concat([df_16pm[['Unnamed: 2', 'Unnamed: 3']], df_16pm.iloc[:,i:i+3].assign(Sabe_leer_y_escribir=literate_status)], axis=1)
    ls_df.append(df_16pm_with_literate_status)

for df in ls_df:
    df.rename(columns=dict(zip(list(df.columns.values[2:-1]), cleaned_headers[:])), inplace=True)

df_16pm = pd.concat(ls_df)
df_16pm.rename(columns={'Unnamed: 2': 'Area', 'Unnamed: 3': 'Grupo de edad'}, inplace=True)

df_16pm

,Area,Grupo de edad,Total,Hombre,Mujer,Sabe_leer_y_escribir
3836,Total,De 5 años y más,11809,5559,6250,total
3837,NaN,De 15 años y más,10126,4726,5400,total
3838,NaN,Entre 15 y 24 años,2028,982,1046,total
3839,Cabecera,De 5 años y más,10145,4674,5471,total
3840,NaN,De 15 años y más,8746,3994,4752,total
3841,NaN,Entre 15 y 24 años,1718,820,898,total
3842,Rural disperso,De 5 años y más,1664,885,779,total
3843,NaN,De 15 años y más,1380,732,648,total
3844,NaN,Entre 15 y 24 años,310,162,148,total
3836,Total,De 5 años y más,10859,5052,5807,si
3837,NaN,De 15 años y más,9376,4318,5058,si
3838,NaN,Entre 15 y 24 años,1980,948,1032,si
3839,Cabecera,De 5 años y más,9339,4263,5076,si
3840,NaN,De 15 años y más,8107,3666,4441,si
3841,NaN,Entre 15 y 24 años,1676,791,885,si
3842,Rural disperso,De 5 años y más,1520,789,731,si
3843,NaN,De 15 años y más,1269,652,617,si
3844,NaN,Entre 15 y 24 años,304,157,147,si
3836,Total,De 5 años y más,890,474,416,no
3837,NaN,De 15 años y más,699,381,318,no
3838,NaN,Entre 15 y 24 años,33,25,8,no
3839,Cabecera,De 5 años y más,752,382,370,no
3840,NaN,De 15 años y más,593,304,289,no
3841,NaN,Entre 15 y 24 años,27,20,7,no
3842,Rural disperso,De 5 años y más,138,92,46,no
3843,NaN,De 15 años y más,106,77,29,no
3844,NaN,Entre 15 y 24 años,6,5,1,no
3836,Total,De 5 años y más,60,33,27,sin_informacion
3837,NaN,De 15 años y más,51,27,24,sin_informacion
3838,NaN,Entre 15 y 24 años,15,9,6,sin_informacion
3839,Cabecera,De 5 años y más,54,29,25,sin_informacion
3840,NaN,De 15 años y más,46,24,22,sin_informacion
3841,NaN,Entre 15 y 24 años,15,9,6,sin_informacion
3842,Rural disperso,De 5 años y más,6,4,2,sin_informacion
3843,NaN,De 15 años y más,5,3,2,sin_informacion
3844,NaN,Entre 15 y 24 años,0,0,0,sin_informacion

Se propaga el valor de la columna 'Area' para completar los datos faltantes.

In [10]:
df_16pm['Area'] = df_16pm['Area'].ffill()
df_16pm

,Area,Grupo de edad,Total,Hombre,Mujer,Sabe_leer_y_escribir
3836,Total,De 5 años y más,11809,5559,6250,total
3837,Total,De 15 años y más,10126,4726,5400,total
3838,Total,Entre 15 y 24 años,2028,982,1046,total
3839,Cabecera,De 5 años y más,10145,4674,5471,total
3840,Cabecera,De 15 años y más,8746,3994,4752,total
3841,Cabecera,Entre 15 y 24 años,1718,820,898,total
3842,Rural disperso,De 5 años y más,1664,885,779,total
3843,Rural disperso,De 15 años y más,1380,732,648,total
3844,Rural disperso,Entre 15 y 24 años,310,162,148,total
3836,Total,De 5 años y más,10859,5052,5807,si
3837,Total,De 15 años y más,9376,4318,5058,si
3838,Total,Entre 15 y 24 años,1980,948,1032,si
3839,Cabecera,De 5 años y más,9339,4263,5076,si
3840,Cabecera,De 15 años y más,8107,3666,4441,si
3841,Cabecera,Entre 15 y 24 años,1676,791,885,si
3842,Rural disperso,De 5 años y más,1520,789,731,si
3843,Rural disperso,De 15 años y más,1269,652,617,si
3844,Rural disperso,Entre 15 y 24 años,304,157,147,si
3836,Total,De 5 años y más,890,474,416,no
3837,Total,De 15 años y más,699,381,318,no
3838,Total,Entre 15 y 24 años,33,25,8,no
3839,Cabecera,De 5 años y más,752,382,370,no
3840,Cabecera,De 15 años y más,593,304,289,no
3841,Cabecera,Entre 15 y 24 años,27,20,7,no
3842,Rural disperso,De 5 años y más,138,92,46,no
3843,Rural disperso,De 15 años y más,106,77,29,no
3844,Rural disperso,Entre 15 y 24 años,6,5,1,no
3836,Total,De 5 años y más,60,33,27,sin_informacion
3837,Total,De 15 años y más,51,27,24,sin_informacion
3838,Total,Entre 15 y 24 años,15,9,6,sin_informacion
3839,Cabecera,De 5 años y más,54,29,25,sin_informacion
3840,Cabecera,De 15 años y más,46,24,22,sin_informacion
3841,Cabecera,Entre 15 y 24 años,15,9,6,sin_informacion
3842,Rural disperso,De 5 años y más,6,4,2,sin_informacion
3843,Rural disperso,De 15 años y más,5,3,2,sin_informacion
3844,Rural disperso,Entre 15 y 24 años,0,0,0,sin_informacion

Se cambian los datos que contienen tildes y ñ.

In [11]:
replacements = str.maketrans({'ñ':'ni', 'á':'a'})
df_16pm.loc[:,'Grupo de edad'] = df_16pm['Grupo de edad'].str.translate(replacements)
df_16pm

,Area,Grupo de edad,Total,Hombre,Mujer,Sabe_leer_y_escribir
3836,Total,De 5 anios y mas,11809,5559,6250,total
3837,Total,De 15 anios y mas,10126,4726,5400,total
3838,Total,Entre 15 y 24 anios,2028,982,1046,total
3839,Cabecera,De 5 anios y mas,10145,4674,5471,total
3840,Cabecera,De 15 anios y mas,8746,3994,4752,total
3841,Cabecera,Entre 15 y 24 anios,1718,820,898,total
3842,Rural disperso,De 5 anios y mas,1664,885,779,total
3843,Rural disperso,De 15 anios y mas,1380,732,648,total
3844,Rural disperso,Entre 15 y 24 anios,310,162,148,total
3836,Total,De 5 anios y mas,10859,5052,5807,si
3837,Total,De 15 anios y mas,9376,4318,5058,si
3838,Total,Entre 15 y 24 anios,1980,948,1032,si
3839,Cabecera,De 5 anios y mas,9339,4263,5076,si
3840,Cabecera,De 15 anios y mas,8107,3666,4441,si
3841,Cabecera,Entre 15 y 24 anios,1676,791,885,si
3842,Rural disperso,De 5 anios y mas,1520,789,731,si
3843,Rural disperso,De 15 anios y mas,1269,652,617,si
3844,Rural disperso,Entre 15 y 24 anios,304,157,147,si
3836,Total,De 5 anios y mas,890,474,416,no
3837,Total,De 15 anios y mas,699,381,318,no
3838,Total,Entre 15 y 24 anios,33,25,8,no
3839,Cabecera,De 5 anios y mas,752,382,370,no
3840,Cabecera,De 15 anios y mas,593,304,289,no
3841,Cabecera,Entre 15 y 24 anios,27,20,7,no
3842,Rural disperso,De 5 anios y mas,138,92,46,no
3843,Rural disperso,De 15 anios y mas,106,77,29,no
3844,Rural disperso,Entre 15 y 24 anios,6,5,1,no
3836,Total,De 5 anios y mas,60,33,27,sin_informacion
3837,Total,De 15 anios y mas,51,27,24,sin_informacion
3838,Total,Entre 15 y 24 anios,15,9,6,sin_informacion
3839,Cabecera,De 5 anios y mas,54,29,25,sin_informacion
3840,Cabecera,De 15 anios y mas,46,24,22,sin_informacion
3841,Cabecera,Entre 15 y 24 anios,15,9,6,sin_informacion
3842,Rural disperso,De 5 anios y mas,6,4,2,sin_informacion
3843,Rural disperso,De 15 anios y mas,5,3,2,sin_informacion
3844,Rural disperso,Entre 15 y 24 anios,0,0,0,sin_informacion

Se creará una copia del dataframe y se removerán las filas y columnas con resumenes de datos para el csv que no contiene resúmenes.

In [12]:
df_16pm_cleaned = df_16pm.copy()
df_16pm_cleaned.drop(['Total'], axis=1, inplace=True)
df_16pm_cleaned

                Area        Grupo de edad Hombre Mujer Sabe_leer_y_escribir
3836           Total     De 5 anios y mas   5559  6250                total
3837           Total    De 15 anios y mas   4726  5400                total
3838           Total  Entre 15 y 24 anios    982  1046                total
3839        Cabecera     De 5 anios y mas   4674  5471                total
3840        Cabecera    De 15 anios y mas   3994  4752                total
3841        Cabecera  Entre 15 y 24 anios    820   898                total
3842  Rural disperso     De 5 anios y mas    885   779                total
3843  Rural disperso    De 15 anios y mas    732   648                total
3844  Rural disperso  Entre 15 y 24 anios    162   148                total
3836           Total     De 5 anios y mas   5052  5807                   si
3837           Total    De 15 anios y mas   4318  5058                   si
3838           Total  Entre 15 y 24 anios    948  1032                   si
3839        Cabecera     De 5 anios y mas   4263  5076                   si
3840        Cabecera    De 15 anios y mas   3666  4441                   si
3841        Cabecera  Entre 15 y 24 anios    791   885                   si
3842  Rural disperso     De 5 anios y mas    789   731                   si
3843  Rural disperso    De 15 anios y mas    652   617                   si
3844  Rural disperso  Entre 15 y 24 anios    157   147                   si
3836           Total     De 5 anios y mas    474   416                   no
3837           Total    De 15 anios y mas    381   318                   no
3838           Total  Entre 15 y 24 anios     25     8                   no
3839        Cabecera     De 5 anios y mas    382   370                   no
3840        Cabecera    De 15 anios y mas    304   289                   no
3841        Cabecera  Entre 15 y 24 anios     20     7                   no
3842  Rural disperso     De 5 anios y mas     92    46                   no
3843  Rural disperso    De 15 anios y mas     77    29                   no
3844  Rural disperso  Entre 15 y 24 anios      5     1                   no
3836           Total     De 5 anios y mas     33    27      sin_informacion
3837           Total    De 15 anios y mas     27    24      sin_informacion
3838           Total  Entre 15 y 24 anios      9     6      sin_informacion
3839        Cabecera     De 5 anios y mas     29    25      sin_informacion
3840        Cabecera    De 15 anios y mas     24    22      sin_informacion
3841        Cabecera  Entre 15 y 24 anios      9     6      sin_informacion
3842  Rural disperso     De 5 anios y mas      4     2      sin_informacion
3843  Rural disperso    De 15 anios y mas      3     2      sin_informacion
3844  Rural disperso  Entre 15 y 24 anios      0     0      sin_informacion

In [13]:
df_16pm_cleaned = df_16pm_cleaned.loc[(df_16pm_cleaned['Area'] != 'Total') & (df_16pm_cleaned['Sabe_leer_y_escribir'] != 'total')]
df_16pm_cleaned

                Area        Grupo de edad Hombre Mujer Sabe_leer_y_escribir
3839        Cabecera     De 5 anios y mas   4263  5076                   si
3840        Cabecera    De 15 anios y mas   3666  4441                   si
3841        Cabecera  Entre 15 y 24 anios    791   885                   si
3842  Rural disperso     De 5 anios y mas    789   731                   si
3843  Rural disperso    De 15 anios y mas    652   617                   si
3844  Rural disperso  Entre 15 y 24 anios    157   147                   si
3839        Cabecera     De 5 anios y mas    382   370                   no
3840        Cabecera    De 15 anios y mas    304   289                   no
3841        Cabecera  Entre 15 y 24 anios     20     7                   no
3842  Rural disperso     De 5 anios y mas     92    46                   no
3843  Rural disperso    De 15 anios y mas     77    29                   no
3844  Rural disperso  Entre 15 y 24 anios      5     1                   no
3839        Cabecera     De 5 anios y mas     29    25      sin_informacion
3840        Cabecera    De 15 anios y mas     24    22      sin_informacion
3841        Cabecera  Entre 15 y 24 anios      9     6      sin_informacion
3842  Rural disperso     De 5 anios y mas      4     2      sin_informacion
3843  Rural disperso    De 15 anios y mas      3     2      sin_informacion
3844  Rural disperso  Entre 15 y 24 anios      0     0      sin_informacion

Los dataframes están listos para ser exportados a CSV.

In [14]:
df_16pm.to_csv(csv_total_path, index=False)
df_16pm_cleaned.to_csv(csv_path, index=False)