In [1]:
# imports
import pandas as pd

In [2]:
# Ruta relativa del xslx que contiene los datos
original_data_path = 'Data\\Original\\PERSONAS_DEMOGRAFICO_Cuadros_CNPV_2018.xlsx'

# Nombre del csv objetivo
csv_filename = 'caldas_viterbo_4PM.csv'

# Ruta relativa del csv objetivo
csv_path = 'Data\\Datasets\\' + csv_filename

In [3]:
# Lee archivo xlsx
df_4pm = pd.read_excel(original_data_path, sheet_name='4PM', skiprows=9)
df_4pm.head()

,"Municipio, área (Total, Cabecera y Centros poblados y Rural disperso) y sexo",Unnamed: 1,Unnamed: 2,Unnamed: 3,Total,Relación o parentesco con el Jefe(a) del hogar,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,NaN,NaN,NaN,NaN,NaN,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
1,Total Nacional,NaN,Total,Total,43835324.0,14243223,7562979,15194806,811145,386171,...,24573,195901,782684,17996,188590,2139901,35640,1029584,50822,551032
2,NaN,NaN,NaN,Hombre,21317034.0,8440991,1494377,8046302,424474,196314,...,15647,47777,417472,9943,103275,1134220,7681,534876,5343,293655
3,NaN,NaN,NaN,Mujer,22518290.0,5802232,6068602,7148504,386671,189857,...,8926,148124,365212,8053,85315,1005681,27959,494708,45479,257377
4,NaN,NaN,Cabecera,Total,33905550.0,11128226,5755449,11480205,604243,319161,...,20024,164645,655272,14164,156720,1691914,30164,849820,43124,459551

Se observa que los headers se encuentran en la primera fila, para ellos se creará un diccionario con el nombre actual de la columna como llave y el nombre correspondiente de la primera fila como valor, para luego reemplazarlos.

In [4]:
df_new_headers = {}
current_headers = list(df_4pm.columns.values)[5:]
actual_headers = list(df_4pm.iloc[0])[5:]

for key, value in zip(current_headers, actual_headers):
    df_new_headers[key] = value

df_4pm = df_4pm.rename(columns=df_new_headers)
df_4pm

,"Municipio, área (Total, Cabecera y Centros poblados y Rural disperso) y sexo",Unnamed: 1,Unnamed: 2,Unnamed: 3,Total,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
0,NaN,NaN,NaN,NaN,NaN,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
1,Total Nacional,NaN,Total,Total,43835324.0,14243223,7562979,15194806,811145,386171,...,24573,195901,782684,17996,188590,2139901,35640,1029584,50822,551032
2,NaN,NaN,NaN,Hombre,21317034.0,8440991,1494377,8046302,424474,196314,...,15647,47777,417472,9943,103275,1134220,7681,534876,5343,293655
3,NaN,NaN,NaN,Mujer,22518290.0,5802232,6068602,7148504,386671,189857,...,8926,148124,365212,8053,85315,1005681,27959,494708,45479,257377
4,NaN,NaN,Cabecera,Total,33905550.0,11128226,5755449,11480205,604243,319161,...,20024,164645,655272,14164,156720,1691914,30164,849820,43124,459551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12838,NaN,NaN,Rural disperso,Total,36514.0,8413,5905,18736,443,148,...,21,58,312,36,83,1039,58,894,34,199
12839,NaN,NaN,NaN,Hombre,19226.0,6798,355,10239,227,89,...,12,17,200,21,53,553,18,467,25,110
12840,NaN,NaN,NaN,Mujer,17288.0,1615,5550,8497,216,59,...,9,41,112,15,30,486,40,427,9,89
12841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12842,Fuente: DANE - Censo Nacional de Población y V...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Se cambian los nombres de las columnas restantes por nombres más descriptivos.

In [5]:
df_4pm = df_4pm.rename(columns={'Unnamed: 1':'Municipio', 'Unnamed: 2':'Area', 'Unnamed: 3':'Sexo'})
df_4pm

,"Municipio, área (Total, Cabecera y Centros poblados y Rural disperso) y sexo",Municipio,Area,Sexo,Total,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
0,NaN,NaN,NaN,NaN,NaN,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
1,Total Nacional,NaN,Total,Total,43835324.0,14243223,7562979,15194806,811145,386171,...,24573,195901,782684,17996,188590,2139901,35640,1029584,50822,551032
2,NaN,NaN,NaN,Hombre,21317034.0,8440991,1494377,8046302,424474,196314,...,15647,47777,417472,9943,103275,1134220,7681,534876,5343,293655
3,NaN,NaN,NaN,Mujer,22518290.0,5802232,6068602,7148504,386671,189857,...,8926,148124,365212,8053,85315,1005681,27959,494708,45479,257377
4,NaN,NaN,Cabecera,Total,33905550.0,11128226,5755449,11480205,604243,319161,...,20024,164645,655272,14164,156720,1691914,30164,849820,43124,459551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12838,NaN,NaN,Rural disperso,Total,36514.0,8413,5905,18736,443,148,...,21,58,312,36,83,1039,58,894,34,199
12839,NaN,NaN,NaN,Hombre,19226.0,6798,355,10239,227,89,...,12,17,200,21,53,553,18,467,25,110
12840,NaN,NaN,NaN,Mujer,17288.0,1615,5550,8497,216,59,...,9,41,112,15,30,486,40,427,9,89
12841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12842,Fuente: DANE - Censo Nacional de Población y V...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Se propagan los identificadores de municipio para filtrar los datos que no corresponden a Viterbo, Caldas.

In [6]:
df_4pm['Municipio'] = df_4pm['Municipio'].ffill()
df_4pm = df_4pm.loc[df_4pm['Municipio'] == '17877_Viterbo']
df_4pm

,"Municipio, área (Total, Cabecera y Centros poblados y Rural disperso) y sexo",Municipio,Area,Sexo,Total,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,...,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
3835,NaN,17877_Viterbo,Total,Total,12425.0,4069,2102,3703,347,133,...,11,77,315,7,95,785,10,325,6,229
3836,NaN,17877_Viterbo,NaN,Hombre,5887.0,2583,149,1895,169,78,...,6,24,150,6,59,407,6,176,0,127
3837,NaN,17877_Viterbo,NaN,Mujer,6538.0,1486,1953,1808,178,55,...,5,53,165,1,36,378,4,149,6,102
3838,NaN,17877_Viterbo,Cabecera,Total,10664.0,3544,1729,3176,280,115,...,5,65,289,4,76,710,10,276,3,192
3839,NaN,17877_Viterbo,NaN,Hombre,4958.0,2137,142,1617,131,69,...,4,18,135,4,43,363,6,141,0,104
3840,NaN,17877_Viterbo,NaN,Mujer,5706.0,1407,1587,1559,149,46,...,1,47,154,0,33,347,4,135,3,88
3841,NaN,17877_Viterbo,Rural disperso,Total,1761.0,525,373,527,67,18,...,6,12,26,3,19,75,0,49,3,37
3842,NaN,17877_Viterbo,NaN,Hombre,929.0,446,7,278,38,9,...,2,6,15,2,16,44,0,35,0,23
3843,NaN,17877_Viterbo,NaN,Mujer,832.0,79,366,249,29,9,...,4,6,11,1,3,31,0,14,3,14

Se eliminan columnas que no contienen datos relevantes para el dataset y aquellas que contienen resumenes de datos.

In [7]:
df_4pm = df_4pm.drop(['Municipio, área (Total, Cabecera y Centros poblados y Rural disperso) y sexo', 'Municipio'], axis=1)
df_4pm

,Area,Sexo,Total,Jefe(a) del hogar,"Pareja (Conyuge, compañero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cuñado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio doméstico,No pariente
3835,Total,Total,12425.0,4069,2102,3703,347,133,211,11,77,315,7,95,785,10,325,6,229
3836,NaN,Hombre,5887.0,2583,149,1895,169,78,52,6,24,150,6,59,407,6,176,0,127
3837,NaN,Mujer,6538.0,1486,1953,1808,178,55,159,5,53,165,1,36,378,4,149,6,102
3838,Cabecera,Total,10664.0,3544,1729,3176,280,115,190,5,65,289,4,76,710,10,276,3,192
3839,NaN,Hombre,4958.0,2137,142,1617,131,69,44,4,18,135,4,43,363,6,141,0,104
3840,NaN,Mujer,5706.0,1407,1587,1559,149,46,146,1,47,154,0,33,347,4,135,3,88
3841,Rural disperso,Total,1761.0,525,373,527,67,18,21,6,12,26,3,19,75,0,49,3,37
3842,NaN,Hombre,929.0,446,7,278,38,9,8,2,6,15,2,16,44,0,35,0,23
3843,NaN,Mujer,832.0,79,366,249,29,9,13,4,6,11,1,3,31,0,14,3,14

Se renombran los headers que tienen tildes y ñ.

In [8]:
df_4pm = df_4pm.rename(columns={'Pareja (Conyuge, compañero(a), esposo(a))':'Pareja (Conyuge, companero(a), esposo(a))',
                       'Cuñado(a)':'Cunado(a)',
                       'Empleado(a) del servicio doméstico':'Empleado(a) del servicio domestico'})
df_4pm

,Area,Sexo,Total,Jefe(a) del hogar,"Pareja (Conyuge, companero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cunado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio domestico,No pariente
3835,Total,Total,12425.0,4069,2102,3703,347,133,211,11,77,315,7,95,785,10,325,6,229
3836,NaN,Hombre,5887.0,2583,149,1895,169,78,52,6,24,150,6,59,407,6,176,0,127
3837,NaN,Mujer,6538.0,1486,1953,1808,178,55,159,5,53,165,1,36,378,4,149,6,102
3838,Cabecera,Total,10664.0,3544,1729,3176,280,115,190,5,65,289,4,76,710,10,276,3,192
3839,NaN,Hombre,4958.0,2137,142,1617,131,69,44,4,18,135,4,43,363,6,141,0,104
3840,NaN,Mujer,5706.0,1407,1587,1559,149,46,146,1,47,154,0,33,347,4,135,3,88
3841,Rural disperso,Total,1761.0,525,373,527,67,18,21,6,12,26,3,19,75,0,49,3,37
3842,NaN,Hombre,929.0,446,7,278,38,9,8,2,6,15,2,16,44,0,35,0,23
3843,NaN,Mujer,832.0,79,366,249,29,9,13,4,6,11,1,3,31,0,14,3,14

Se propaga el area para reemplazar valores NaN.

In [9]:
df_4pm['Area'] = df_4pm['Area'].ffill()
df_4pm

,Area,Sexo,Total,Jefe(a) del hogar,"Pareja (Conyuge, companero(a), esposo(a))",Hijo(a),Hijastro(a),Yerno/nuera,Padre/madre,"Padrastro, madrastra",Suegro(a),Hermano(a),Hermanastro(a),Cunado(a),Nieto(a),Abuelo(a),Otro pariente,Empleado(a) del servicio domestico,No pariente
3835,Total,Total,12425.0,4069,2102,3703,347,133,211,11,77,315,7,95,785,10,325,6,229
3836,Total,Hombre,5887.0,2583,149,1895,169,78,52,6,24,150,6,59,407,6,176,0,127
3837,Total,Mujer,6538.0,1486,1953,1808,178,55,159,5,53,165,1,36,378,4,149,6,102
3838,Cabecera,Total,10664.0,3544,1729,3176,280,115,190,5,65,289,4,76,710,10,276,3,192
3839,Cabecera,Hombre,4958.0,2137,142,1617,131,69,44,4,18,135,4,43,363,6,141,0,104
3840,Cabecera,Mujer,5706.0,1407,1587,1559,149,46,146,1,47,154,0,33,347,4,135,3,88
3841,Rural disperso,Total,1761.0,525,373,527,67,18,21,6,12,26,3,19,75,0,49,3,37
3842,Rural disperso,Hombre,929.0,446,7,278,38,9,8,2,6,15,2,16,44,0,35,0,23
3843,Rural disperso,Mujer,832.0,79,366,249,29,9,13,4,6,11,1,3,31,0,14,3,14

El dataframe está listo para ser exportado a csv.

In [10]:
df_4pm.to_csv(csv_path, index=False)