In [13]:
# imports
import pandas as pd

In [14]:
# Ruta relativa del xslx que contiene los datos
original_data_path = 'Data\\Original\\PERSONAS_DEMOGRAFICO_Cuadros_CNPV_2018.xlsx'

# Nombre del csv objetivo
csv_total_filename = 'caldas_viterbo_total_19PM.csv'
csv_filename = 'caldas_viterbo_19PM.csv'

# Ruta relativa del csv objetivo
csv_total_path = 'Data\\Datasets\\' + csv_total_filename
csv_path = 'Data\\Datasets\\' + csv_filename

In [15]:
# Lee archivo xlsx
df_19pm = pd.read_excel(original_data_path, sheet_name='19PM', skiprows=10)
df_19pm.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Total,Ninguno,Preescolar,Primaria Completa,Primaria Incompleta,...,Secundaria Incompleta,Media Completa,Media Incompleta,Normal Completa,Normal Incompleta,Tecnico,Tecnologico,Universitario,Especialización - Doctorado,Sin Información
0,Total Nacional,NaN,Total,Hombre,Indígena,846175.0,98195.0,26960.0,111910.0,247545.0,...,117360.0,118762.0,23088.0,1182.0,1928.0,15579.0,6181.0,26302.0,4296.0,16181.0
1,NaN,NaN,NaN,NaN,Gitano(a) o Rrom,1276.0,71.0,31.0,154.0,353.0,...,143.0,179.0,31.0,0.0,15.0,55.0,24.0,83.0,49.0,47.0
2,NaN,NaN,NaN,NaN,"Raizal del Archipielago de San Andrés, Provide...",11686.0,176.0,210.0,746.0,1257.0,...,1868.0,3030.0,460.0,9.0,44.0,1003.0,414.0,1391.0,337.0,138.0
3,NaN,NaN,NaN,NaN,Palenquero(a) de San Basilio,3154.0,324.0,74.0,313.0,559.0,...,349.0,640.0,68.0,2.0,28.0,148.0,64.0,341.0,84.0,53.0
4,NaN,NaN,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",1319785.0,82812.0,35025.0,145690.0,287488.0,...,204195.0,269325.0,41810.0,1343.0,5257.0,55082.0,24440.0,75344.0,19728.0,16833.0

Se filtrarán los datos que no corresponden al municipio de Viterbo Caldas, para ello se propagará el municipio, el cual se encuentra en la columna "Unnamed: 1" y se seleccionarán solo los registros que contengan el identificador de Viterbo dentro del dataframe, para este caso es "17877_Viterbo".

In [16]:
df_19pm['Unnamed: 1'] = df_19pm['Unnamed: 1'].ffill()
df_19pm = df_19pm.loc[df_19pm['Unnamed: 1'] == '17877_Viterbo']
df_19pm

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Total,Ninguno,Preescolar,Primaria Completa,Primaria Incompleta,...,Secundaria Incompleta,Media Completa,Media Incompleta,Normal Completa,Normal Incompleta,Tecnico,Tecnologico,Universitario,Especialización - Doctorado,Sin Información
18199,NaN,17877_Viterbo,Total,Hombre,Indígena,74.0,2.0,2.0,10.0,33.0,...,13.0,10.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18200,NaN,17877_Viterbo,NaN,NaN,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18201,NaN,17877_Viterbo,NaN,NaN,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18202,NaN,17877_Viterbo,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",43.0,2.0,1.0,4.0,7.0,...,8.0,9.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18203,NaN,17877_Viterbo,NaN,NaN,Ningún grupo étnico,5410.0,300.0,120.0,817.0,1280.0,...,836.0,1217.0,137.0,0.0,9.0,120.0,56.0,252.0,57.0,21.0
18204,NaN,17877_Viterbo,NaN,NaN,Sin Información,30.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,28.0
18205,NaN,17877_Viterbo,NaN,NaN,Total,5559.0,304.0,123.0,831.0,1321.0,...,857.0,1238.0,139.0,0.0,9.0,122.0,57.0,256.0,57.0,51.0
18206,NaN,17877_Viterbo,NaN,Mujer,Indígena,81.0,6.0,2.0,16.0,18.0,...,8.0,17.0,3.0,0.0,0.0,2.0,1.0,3.0,0.0,1.0
18207,NaN,17877_Viterbo,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",44.0,4.0,0.0,4.0,7.0,...,13.0,10.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18208,NaN,17877_Viterbo,NaN,NaN,Ningún grupo étnico,6104.0,262.0,128.0,853.0,1268.0,...,899.0,1579.0,157.0,6.0,4.0,235.0,59.0,322.0,63.0,17.0
18209,NaN,17877_Viterbo,NaN,NaN,Sin Información,24.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,23.0
18210,NaN,17877_Viterbo,NaN,NaN,Total,6253.0,272.0,130.0,873.0,1293.0,...,920.0,1606.0,160.0,6.0,4.0,238.0,60.0,328.0,64.0,41.0
18211,NaN,17877_Viterbo,NaN,Total,Indígena,155.0,8.0,4.0,26.0,51.0,...,21.0,27.0,3.0,0.0,0.0,3.0,2.0,3.0,0.0,1.0
18212,NaN,17877_Viterbo,NaN,NaN,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18213,NaN,17877_Viterbo,NaN,NaN,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18214,NaN,17877_Viterbo,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",87.0,6.0,1.0,8.0,14.0,...,21.0,19.0,2.0,0.0,0.0,2.0,0.0,5.0,1.0,2.0
18215,NaN,17877_Viterbo,NaN,NaN,Ningún grupo étnico,11514.0,562.0,248.0,1670.0,2548.0,...,1735.0,2796.0,294.0,6.0,13.0,355.0,115.0,574.0,120.0,38.0
18216,NaN,17877_Viterbo,NaN,NaN,Sin Información,54.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,51.0
18217,NaN,17877_Viterbo,NaN,NaN,Total,11812.0,576.0,253.0,1704.0,2614.0,...,1777.0,2844.0,299.0,6.0,13.0,360.0,117.0,584.0,121.0,92.0
18218,NaN,17877_Viterbo,Cabecera,Hombre,Indígena,27.0,0.0,0.0,5.0,9.0,...,4.0,7.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18219,NaN,17877_Viterbo,NaN,NaN,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18220,NaN,17877_Viterbo,NaN,NaN,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18221,NaN,17877_Viterbo,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",39.0,1.0,1.0,4.0,7.0,...,7.0,8.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18222,NaN,17877_Viterbo,NaN,NaN,Ningún grupo étnico,4579.0,257.0,96.0,690.0,976.0,...,705.0,1099.0,115.0,0.0,9.0,117.0,56.0,228.0,47.0,19.0
18223,NaN,17877_Viterbo,NaN,NaN,Sin Información,27.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,25.0
18224,NaN,17877_Viterbo,NaN,NaN,Total,4674.0,258.0,97.0,699.0,993.0,...,716.0,1116.0,117.0,0.0,9.0,119.0,57.0,232.0,47.0,46.0
18225,NaN,17877_Viterbo,NaN,Mujer,Indígena,39.0,2.0,0.0,8.0,6.0,...,6.0,8.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0
18226,NaN,17877_Viterbo,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",40.0,3.0,0.0,3.0,7.0,...,12.0,9.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18227,NaN,17877_Viterbo,NaN,NaN,Ningún grupo étnico,5373.0,246.0,113.0,742.0,1038.0,...,772.0,1447.0,137.0,5.0,3.0,227.0,54.0,304.0,56.0,17.0
18228,NaN,17877_Viterbo,NaN,NaN,Sin Información,22.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,21.0
18229,NaN,17877_Viterbo,NaN,NaN,Total,5474.0,251.0,113.0,753.0,1051.0,...,790.0,1464.0,138.0,5.0,3.0,229.0,55.0,310.0,57.0,39.0
18230,NaN,17877_Viterbo,NaN,Total,Indígena,66.0,2.0,0.0,13.0,15.0,...,10.0,15.0,1.0,0.0,0.0,2.0,2.0,3.0,0.0,1.0
18231,NaN,17877_Viterbo,NaN,NaN,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18232,NaN,17877_Viterbo,NaN,NaN,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18233,NaN,17877_Viterbo,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",79.0,4.0,1.0,7.0,14.0,...,19.0,17.0,2.0,0.0,0.0,2.0,0.0,5.0,1.0,2.0
18234,NaN,17877_Viterbo,NaN,NaN,Ningún grupo étnico,9952.0,503.0,209.0,1432.0,2014.0,...,1477.0,2546.0,252.0,5.0,12.0,344.0,110.0,532.0,103.0,36.0
18235,NaN,17877_Viterbo,NaN,NaN,Sin Información,49.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,46.0
18236,NaN,17877_Viterbo,NaN,NaN,Total,10148.0,509.0,210.0,1452.0,2044.0,...,1506.0,2580.0,255.0,5.0,12.0,348.0,112.0,542.0,104.0,85.0
18237,NaN,17877_Viterbo,Rural disperso,Hombre,Indígena,47.0,2.0,2.0,5.0,24.0,...,9.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18238,NaN,17877_Viterbo,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",4.0,1.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18239,NaN,17877_Viterbo,NaN,NaN,Ningún grupo étnico,831.0,43.0,24.0,127.0,304.0,...,131.0,118.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,2.0
18240,NaN,17877_Viterbo,NaN,NaN,Sin Información,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
18241,NaN,17877_Viterbo,NaN,NaN,Total,885.0,46.0,26.0,132.0,328.0,...,141.0,122.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,5.0
18242,NaN,17877_Viterbo,NaN,Mujer,Indígena,42.0,4.0,2.0,8.0,12.0,...,2.0,9.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18243,NaN,17877_Viterbo,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",4.0,1.0,0.0,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18244,NaN,17877_Viterbo,NaN,NaN,Ningún grupo étnico,731.0,16.0,15.0,111.0,230.0,...,127.0,132.0,20.0,1.0,1.0,8.0,5.0,18.0,7.0,0.0
18245,NaN,17877_Viterbo,NaN,NaN,Sin Información,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
18246,NaN,17877_Viterbo,NaN,NaN,Total,779.0,21.0,17.0,120.0,242.0,...,130.0,142.0,22.0,1.0,1.0,9.0,5.0,18.0,7.0,2.0
18247,NaN,17877_Viterbo,NaN,Total,Indígena,89.0,6.0,4.0,13.0,36.0,...,11.0,12.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18248,NaN,17877_Viterbo,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",8.0,2.0,0.0,1.0,0.0,...,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18249,NaN,17877_Viterbo,NaN,NaN,Ningún grupo étnico,1562.0,59.0,39.0,238.0,534.0,...,258.0,250.0,42.0,1.0,1.0,11.0,5.0,42.0,17.0,2.0
18250,NaN,17877_Viterbo,NaN,NaN,Sin Información,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
18251,NaN,17877_Viterbo,NaN,NaN,Total,1664.0,67.0,43.0,252.0,570.0,...,271.0,264.0,44.0,1.0,1.0,12.0,5.0,42.0,17.0,7.0

Se eliminan las columnas con datos irrelevantes.

In [17]:
df_19pm.drop(columns=['Unnamed: 0', 'Unnamed: 1'], inplace=True)
df_19pm

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Total,Ninguno,Preescolar,Primaria Completa,Primaria Incompleta,Secundaria Completa,Secundaria Incompleta,Media Completa,Media Incompleta,Normal Completa,Normal Incompleta,Tecnico,Tecnologico,Universitario,Especialización - Doctorado,Sin Información
18199,Total,Hombre,Indígena,74.0,2.0,2.0,10.0,33.0,2.0,13.0,10.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18200,NaN,NaN,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18201,NaN,NaN,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18202,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",43.0,2.0,1.0,4.0,7.0,4.0,8.0,9.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18203,NaN,NaN,Ningún grupo étnico,5410.0,300.0,120.0,817.0,1280.0,188.0,836.0,1217.0,137.0,0.0,9.0,120.0,56.0,252.0,57.0,21.0
18204,NaN,NaN,Sin Información,30.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,28.0
18205,NaN,NaN,Total,5559.0,304.0,123.0,831.0,1321.0,194.0,857.0,1238.0,139.0,0.0,9.0,122.0,57.0,256.0,57.0,51.0
18206,NaN,Mujer,Indígena,81.0,6.0,2.0,16.0,18.0,4.0,8.0,17.0,3.0,0.0,0.0,2.0,1.0,3.0,0.0,1.0
18207,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",44.0,4.0,0.0,4.0,7.0,2.0,13.0,10.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18208,NaN,NaN,Ningún grupo étnico,6104.0,262.0,128.0,853.0,1268.0,252.0,899.0,1579.0,157.0,6.0,4.0,235.0,59.0,322.0,63.0,17.0
18209,NaN,NaN,Sin Información,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,23.0
18210,NaN,NaN,Total,6253.0,272.0,130.0,873.0,1293.0,258.0,920.0,1606.0,160.0,6.0,4.0,238.0,60.0,328.0,64.0,41.0
18211,NaN,Total,Indígena,155.0,8.0,4.0,26.0,51.0,6.0,21.0,27.0,3.0,0.0,0.0,3.0,2.0,3.0,0.0,1.0
18212,NaN,NaN,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18213,NaN,NaN,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18214,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",87.0,6.0,1.0,8.0,14.0,6.0,21.0,19.0,2.0,0.0,0.0,2.0,0.0,5.0,1.0,2.0
18215,NaN,NaN,Ningún grupo étnico,11514.0,562.0,248.0,1670.0,2548.0,440.0,1735.0,2796.0,294.0,6.0,13.0,355.0,115.0,574.0,120.0,38.0
18216,NaN,NaN,Sin Información,54.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,51.0
18217,NaN,NaN,Total,11812.0,576.0,253.0,1704.0,2614.0,452.0,1777.0,2844.0,299.0,6.0,13.0,360.0,117.0,584.0,121.0,92.0
18218,Cabecera,Hombre,Indígena,27.0,0.0,0.0,5.0,9.0,0.0,4.0,7.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18219,NaN,NaN,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18220,NaN,NaN,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18221,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",39.0,1.0,1.0,4.0,7.0,3.0,7.0,8.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18222,NaN,NaN,Ningún grupo étnico,4579.0,257.0,96.0,690.0,976.0,165.0,705.0,1099.0,115.0,0.0,9.0,117.0,56.0,228.0,47.0,19.0
18223,NaN,NaN,Sin Información,27.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,25.0
18224,NaN,NaN,Total,4674.0,258.0,97.0,699.0,993.0,168.0,716.0,1116.0,117.0,0.0,9.0,119.0,57.0,232.0,47.0,46.0
18225,NaN,Mujer,Indígena,39.0,2.0,0.0,8.0,6.0,2.0,6.0,8.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0
18226,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",40.0,3.0,0.0,3.0,7.0,2.0,12.0,9.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18227,NaN,NaN,Ningún grupo étnico,5373.0,246.0,113.0,742.0,1038.0,212.0,772.0,1447.0,137.0,5.0,3.0,227.0,54.0,304.0,56.0,17.0
18228,NaN,NaN,Sin Información,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,21.0
18229,NaN,NaN,Total,5474.0,251.0,113.0,753.0,1051.0,216.0,790.0,1464.0,138.0,5.0,3.0,229.0,55.0,310.0,57.0,39.0
18230,NaN,Total,Indígena,66.0,2.0,0.0,13.0,15.0,2.0,10.0,15.0,1.0,0.0,0.0,2.0,2.0,3.0,0.0,1.0
18231,NaN,NaN,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18232,NaN,NaN,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18233,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",79.0,4.0,1.0,7.0,14.0,5.0,19.0,17.0,2.0,0.0,0.0,2.0,0.0,5.0,1.0,2.0
18234,NaN,NaN,Ningún grupo étnico,9952.0,503.0,209.0,1432.0,2014.0,377.0,1477.0,2546.0,252.0,5.0,12.0,344.0,110.0,532.0,103.0,36.0
18235,NaN,NaN,Sin Información,49.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,46.0
18236,NaN,NaN,Total,10148.0,509.0,210.0,1452.0,2044.0,384.0,1506.0,2580.0,255.0,5.0,12.0,348.0,112.0,542.0,104.0,85.0
18237,Rural disperso,Hombre,Indígena,47.0,2.0,2.0,5.0,24.0,2.0,9.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18238,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",4.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18239,NaN,NaN,Ningún grupo étnico,831.0,43.0,24.0,127.0,304.0,23.0,131.0,118.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,2.0
18240,NaN,NaN,Sin Información,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
18241,NaN,NaN,Total,885.0,46.0,26.0,132.0,328.0,26.0,141.0,122.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,5.0
18242,NaN,Mujer,Indígena,42.0,4.0,2.0,8.0,12.0,2.0,2.0,9.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18243,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",4.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18244,NaN,NaN,Ningún grupo étnico,731.0,16.0,15.0,111.0,230.0,40.0,127.0,132.0,20.0,1.0,1.0,8.0,5.0,18.0,7.0,0.0
18245,NaN,NaN,Sin Información,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
18246,NaN,NaN,Total,779.0,21.0,17.0,120.0,242.0,42.0,130.0,142.0,22.0,1.0,1.0,9.0,5.0,18.0,7.0,2.0
18247,NaN,Total,Indígena,89.0,6.0,4.0,13.0,36.0,4.0,11.0,12.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18248,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",8.0,2.0,0.0,1.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18249,NaN,NaN,Ningún grupo étnico,1562.0,59.0,39.0,238.0,534.0,63.0,258.0,250.0,42.0,1.0,1.0,11.0,5.0,42.0,17.0,2.0
18250,NaN,NaN,Sin Información,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
18251,NaN,NaN,Total,1664.0,67.0,43.0,252.0,570.0,68.0,271.0,264.0,44.0,1.0,1.0,12.0,5.0,42.0,17.0,7.0

Se renombran los headers sin nombre.

In [18]:
df_19pm.rename(columns={'Unnamed: 2': 'area', 'Unnamed: 3': 'sexo', 'Unnamed: 4': 'pertenencia_etnica'}, inplace=True)
df_19pm

,area,sexo,pertenencia_etnica,Total,Ninguno,Preescolar,Primaria Completa,Primaria Incompleta,Secundaria Completa,Secundaria Incompleta,Media Completa,Media Incompleta,Normal Completa,Normal Incompleta,Tecnico,Tecnologico,Universitario,Especialización - Doctorado,Sin Información
18199,Total,Hombre,Indígena,74.0,2.0,2.0,10.0,33.0,2.0,13.0,10.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18200,NaN,NaN,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18201,NaN,NaN,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18202,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",43.0,2.0,1.0,4.0,7.0,4.0,8.0,9.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18203,NaN,NaN,Ningún grupo étnico,5410.0,300.0,120.0,817.0,1280.0,188.0,836.0,1217.0,137.0,0.0,9.0,120.0,56.0,252.0,57.0,21.0
18204,NaN,NaN,Sin Información,30.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,28.0
18205,NaN,NaN,Total,5559.0,304.0,123.0,831.0,1321.0,194.0,857.0,1238.0,139.0,0.0,9.0,122.0,57.0,256.0,57.0,51.0
18206,NaN,Mujer,Indígena,81.0,6.0,2.0,16.0,18.0,4.0,8.0,17.0,3.0,0.0,0.0,2.0,1.0,3.0,0.0,1.0
18207,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",44.0,4.0,0.0,4.0,7.0,2.0,13.0,10.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18208,NaN,NaN,Ningún grupo étnico,6104.0,262.0,128.0,853.0,1268.0,252.0,899.0,1579.0,157.0,6.0,4.0,235.0,59.0,322.0,63.0,17.0
18209,NaN,NaN,Sin Información,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,23.0
18210,NaN,NaN,Total,6253.0,272.0,130.0,873.0,1293.0,258.0,920.0,1606.0,160.0,6.0,4.0,238.0,60.0,328.0,64.0,41.0
18211,NaN,Total,Indígena,155.0,8.0,4.0,26.0,51.0,6.0,21.0,27.0,3.0,0.0,0.0,3.0,2.0,3.0,0.0,1.0
18212,NaN,NaN,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18213,NaN,NaN,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18214,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",87.0,6.0,1.0,8.0,14.0,6.0,21.0,19.0,2.0,0.0,0.0,2.0,0.0,5.0,1.0,2.0
18215,NaN,NaN,Ningún grupo étnico,11514.0,562.0,248.0,1670.0,2548.0,440.0,1735.0,2796.0,294.0,6.0,13.0,355.0,115.0,574.0,120.0,38.0
18216,NaN,NaN,Sin Información,54.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,51.0
18217,NaN,NaN,Total,11812.0,576.0,253.0,1704.0,2614.0,452.0,1777.0,2844.0,299.0,6.0,13.0,360.0,117.0,584.0,121.0,92.0
18218,Cabecera,Hombre,Indígena,27.0,0.0,0.0,5.0,9.0,0.0,4.0,7.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18219,NaN,NaN,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18220,NaN,NaN,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18221,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",39.0,1.0,1.0,4.0,7.0,3.0,7.0,8.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18222,NaN,NaN,Ningún grupo étnico,4579.0,257.0,96.0,690.0,976.0,165.0,705.0,1099.0,115.0,0.0,9.0,117.0,56.0,228.0,47.0,19.0
18223,NaN,NaN,Sin Información,27.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,25.0
18224,NaN,NaN,Total,4674.0,258.0,97.0,699.0,993.0,168.0,716.0,1116.0,117.0,0.0,9.0,119.0,57.0,232.0,47.0,46.0
18225,NaN,Mujer,Indígena,39.0,2.0,0.0,8.0,6.0,2.0,6.0,8.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0
18226,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",40.0,3.0,0.0,3.0,7.0,2.0,12.0,9.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18227,NaN,NaN,Ningún grupo étnico,5373.0,246.0,113.0,742.0,1038.0,212.0,772.0,1447.0,137.0,5.0,3.0,227.0,54.0,304.0,56.0,17.0
18228,NaN,NaN,Sin Información,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,21.0
18229,NaN,NaN,Total,5474.0,251.0,113.0,753.0,1051.0,216.0,790.0,1464.0,138.0,5.0,3.0,229.0,55.0,310.0,57.0,39.0
18230,NaN,Total,Indígena,66.0,2.0,0.0,13.0,15.0,2.0,10.0,15.0,1.0,0.0,0.0,2.0,2.0,3.0,0.0,1.0
18231,NaN,NaN,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18232,NaN,NaN,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18233,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",79.0,4.0,1.0,7.0,14.0,5.0,19.0,17.0,2.0,0.0,0.0,2.0,0.0,5.0,1.0,2.0
18234,NaN,NaN,Ningún grupo étnico,9952.0,503.0,209.0,1432.0,2014.0,377.0,1477.0,2546.0,252.0,5.0,12.0,344.0,110.0,532.0,103.0,36.0
18235,NaN,NaN,Sin Información,49.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,46.0
18236,NaN,NaN,Total,10148.0,509.0,210.0,1452.0,2044.0,384.0,1506.0,2580.0,255.0,5.0,12.0,348.0,112.0,542.0,104.0,85.0
18237,Rural disperso,Hombre,Indígena,47.0,2.0,2.0,5.0,24.0,2.0,9.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18238,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",4.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18239,NaN,NaN,Ningún grupo étnico,831.0,43.0,24.0,127.0,304.0,23.0,131.0,118.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,2.0
18240,NaN,NaN,Sin Información,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
18241,NaN,NaN,Total,885.0,46.0,26.0,132.0,328.0,26.0,141.0,122.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,5.0
18242,NaN,Mujer,Indígena,42.0,4.0,2.0,8.0,12.0,2.0,2.0,9.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18243,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",4.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18244,NaN,NaN,Ningún grupo étnico,731.0,16.0,15.0,111.0,230.0,40.0,127.0,132.0,20.0,1.0,1.0,8.0,5.0,18.0,7.0,0.0
18245,NaN,NaN,Sin Información,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
18246,NaN,NaN,Total,779.0,21.0,17.0,120.0,242.0,42.0,130.0,142.0,22.0,1.0,1.0,9.0,5.0,18.0,7.0,2.0
18247,NaN,Total,Indígena,89.0,6.0,4.0,13.0,36.0,4.0,11.0,12.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18248,NaN,NaN,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",8.0,2.0,0.0,1.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18249,NaN,NaN,Ningún grupo étnico,1562.0,59.0,39.0,238.0,534.0,63.0,258.0,250.0,42.0,1.0,1.0,11.0,5.0,42.0,17.0,2.0
18250,NaN,NaN,Sin Información,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
18251,NaN,NaN,Total,1664.0,67.0,43.0,252.0,570.0,68.0,271.0,264.0,44.0,1.0,1.0,12.0,5.0,42.0,17.0,7.0

Se propagan los valores de las columnas con valores faltantes.

In [19]:
df_19pm['area'] = df_19pm['area'].ffill()
df_19pm['sexo'] = df_19pm['sexo'].ffill()
df_19pm

,area,sexo,pertenencia_etnica,Total,Ninguno,Preescolar,Primaria Completa,Primaria Incompleta,Secundaria Completa,Secundaria Incompleta,Media Completa,Media Incompleta,Normal Completa,Normal Incompleta,Tecnico,Tecnologico,Universitario,Especialización - Doctorado,Sin Información
18199,Total,Hombre,Indígena,74.0,2.0,2.0,10.0,33.0,2.0,13.0,10.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18200,Total,Hombre,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18201,Total,Hombre,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18202,Total,Hombre,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",43.0,2.0,1.0,4.0,7.0,4.0,8.0,9.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18203,Total,Hombre,Ningún grupo étnico,5410.0,300.0,120.0,817.0,1280.0,188.0,836.0,1217.0,137.0,0.0,9.0,120.0,56.0,252.0,57.0,21.0
18204,Total,Hombre,Sin Información,30.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,28.0
18205,Total,Hombre,Total,5559.0,304.0,123.0,831.0,1321.0,194.0,857.0,1238.0,139.0,0.0,9.0,122.0,57.0,256.0,57.0,51.0
18206,Total,Mujer,Indígena,81.0,6.0,2.0,16.0,18.0,4.0,8.0,17.0,3.0,0.0,0.0,2.0,1.0,3.0,0.0,1.0
18207,Total,Mujer,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",44.0,4.0,0.0,4.0,7.0,2.0,13.0,10.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18208,Total,Mujer,Ningún grupo étnico,6104.0,262.0,128.0,853.0,1268.0,252.0,899.0,1579.0,157.0,6.0,4.0,235.0,59.0,322.0,63.0,17.0
18209,Total,Mujer,Sin Información,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,23.0
18210,Total,Mujer,Total,6253.0,272.0,130.0,873.0,1293.0,258.0,920.0,1606.0,160.0,6.0,4.0,238.0,60.0,328.0,64.0,41.0
18211,Total,Total,Indígena,155.0,8.0,4.0,26.0,51.0,6.0,21.0,27.0,3.0,0.0,0.0,3.0,2.0,3.0,0.0,1.0
18212,Total,Total,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18213,Total,Total,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18214,Total,Total,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",87.0,6.0,1.0,8.0,14.0,6.0,21.0,19.0,2.0,0.0,0.0,2.0,0.0,5.0,1.0,2.0
18215,Total,Total,Ningún grupo étnico,11514.0,562.0,248.0,1670.0,2548.0,440.0,1735.0,2796.0,294.0,6.0,13.0,355.0,115.0,574.0,120.0,38.0
18216,Total,Total,Sin Información,54.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,51.0
18217,Total,Total,Total,11812.0,576.0,253.0,1704.0,2614.0,452.0,1777.0,2844.0,299.0,6.0,13.0,360.0,117.0,584.0,121.0,92.0
18218,Cabecera,Hombre,Indígena,27.0,0.0,0.0,5.0,9.0,0.0,4.0,7.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18219,Cabecera,Hombre,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18220,Cabecera,Hombre,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18221,Cabecera,Hombre,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",39.0,1.0,1.0,4.0,7.0,3.0,7.0,8.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18222,Cabecera,Hombre,Ningún grupo étnico,4579.0,257.0,96.0,690.0,976.0,165.0,705.0,1099.0,115.0,0.0,9.0,117.0,56.0,228.0,47.0,19.0
18223,Cabecera,Hombre,Sin Información,27.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,25.0
18224,Cabecera,Hombre,Total,4674.0,258.0,97.0,699.0,993.0,168.0,716.0,1116.0,117.0,0.0,9.0,119.0,57.0,232.0,47.0,46.0
18225,Cabecera,Mujer,Indígena,39.0,2.0,0.0,8.0,6.0,2.0,6.0,8.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0
18226,Cabecera,Mujer,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",40.0,3.0,0.0,3.0,7.0,2.0,12.0,9.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18227,Cabecera,Mujer,Ningún grupo étnico,5373.0,246.0,113.0,742.0,1038.0,212.0,772.0,1447.0,137.0,5.0,3.0,227.0,54.0,304.0,56.0,17.0
18228,Cabecera,Mujer,Sin Información,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,21.0
18229,Cabecera,Mujer,Total,5474.0,251.0,113.0,753.0,1051.0,216.0,790.0,1464.0,138.0,5.0,3.0,229.0,55.0,310.0,57.0,39.0
18230,Cabecera,Total,Indígena,66.0,2.0,0.0,13.0,15.0,2.0,10.0,15.0,1.0,0.0,0.0,2.0,2.0,3.0,0.0,1.0
18231,Cabecera,Total,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18232,Cabecera,Total,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18233,Cabecera,Total,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",79.0,4.0,1.0,7.0,14.0,5.0,19.0,17.0,2.0,0.0,0.0,2.0,0.0,5.0,1.0,2.0
18234,Cabecera,Total,Ningún grupo étnico,9952.0,503.0,209.0,1432.0,2014.0,377.0,1477.0,2546.0,252.0,5.0,12.0,344.0,110.0,532.0,103.0,36.0
18235,Cabecera,Total,Sin Información,49.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,46.0
18236,Cabecera,Total,Total,10148.0,509.0,210.0,1452.0,2044.0,384.0,1506.0,2580.0,255.0,5.0,12.0,348.0,112.0,542.0,104.0,85.0
18237,Rural disperso,Hombre,Indígena,47.0,2.0,2.0,5.0,24.0,2.0,9.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18238,Rural disperso,Hombre,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",4.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18239,Rural disperso,Hombre,Ningún grupo étnico,831.0,43.0,24.0,127.0,304.0,23.0,131.0,118.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,2.0
18240,Rural disperso,Hombre,Sin Información,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
18241,Rural disperso,Hombre,Total,885.0,46.0,26.0,132.0,328.0,26.0,141.0,122.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,5.0
18242,Rural disperso,Mujer,Indígena,42.0,4.0,2.0,8.0,12.0,2.0,2.0,9.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18243,Rural disperso,Mujer,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",4.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18244,Rural disperso,Mujer,Ningún grupo étnico,731.0,16.0,15.0,111.0,230.0,40.0,127.0,132.0,20.0,1.0,1.0,8.0,5.0,18.0,7.0,0.0
18245,Rural disperso,Mujer,Sin Información,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
18246,Rural disperso,Mujer,Total,779.0,21.0,17.0,120.0,242.0,42.0,130.0,142.0,22.0,1.0,1.0,9.0,5.0,18.0,7.0,2.0
18247,Rural disperso,Total,Indígena,89.0,6.0,4.0,13.0,36.0,4.0,11.0,12.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18248,Rural disperso,Total,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",8.0,2.0,0.0,1.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18249,Rural disperso,Total,Ningún grupo étnico,1562.0,59.0,39.0,238.0,534.0,63.0,258.0,250.0,42.0,1.0,1.0,11.0,5.0,42.0,17.0,2.0
18250,Rural disperso,Total,Sin Información,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
18251,Rural disperso,Total,Total,1664.0,67.0,43.0,252.0,570.0,68.0,271.0,264.0,44.0,1.0,1.0,12.0,5.0,42.0,17.0,7.0

Se modifican los headers con tildes y ñ.

In [20]:
df_19pm.columns.values

array(['area', 'sexo', 'pertenencia_etnica', 'Total', 'Ninguno',
       'Preescolar', 'Primaria Completa', 'Primaria Incompleta',
       'Secundaria Completa', 'Secundaria Incompleta', 'Media Completa',
       'Media Incompleta', 'Normal Completa', 'Normal Incompleta',
       'Tecnico', 'Tecnologico', 'Universitario',
       'Especialización - Doctorado', 'Sin Información'], dtype=object)

In [21]:
headers_replacement = str.maketrans({'-': ' ', 'ó': 'o'})
df_19pm.columns = ["_".join(header.translate(headers_replacement).split()).lower() for header in df_19pm.columns]
df_19pm

,area,sexo,pertenencia_etnica,total,ninguno,preescolar,primaria_completa,primaria_incompleta,secundaria_completa,secundaria_incompleta,media_completa,media_incompleta,normal_completa,normal_incompleta,tecnico,tecnologico,universitario,especializacion_doctorado,sin_informacion
18199,Total,Hombre,Indígena,74.0,2.0,2.0,10.0,33.0,2.0,13.0,10.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18200,Total,Hombre,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18201,Total,Hombre,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18202,Total,Hombre,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",43.0,2.0,1.0,4.0,7.0,4.0,8.0,9.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18203,Total,Hombre,Ningún grupo étnico,5410.0,300.0,120.0,817.0,1280.0,188.0,836.0,1217.0,137.0,0.0,9.0,120.0,56.0,252.0,57.0,21.0
18204,Total,Hombre,Sin Información,30.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,28.0
18205,Total,Hombre,Total,5559.0,304.0,123.0,831.0,1321.0,194.0,857.0,1238.0,139.0,0.0,9.0,122.0,57.0,256.0,57.0,51.0
18206,Total,Mujer,Indígena,81.0,6.0,2.0,16.0,18.0,4.0,8.0,17.0,3.0,0.0,0.0,2.0,1.0,3.0,0.0,1.0
18207,Total,Mujer,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",44.0,4.0,0.0,4.0,7.0,2.0,13.0,10.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18208,Total,Mujer,Ningún grupo étnico,6104.0,262.0,128.0,853.0,1268.0,252.0,899.0,1579.0,157.0,6.0,4.0,235.0,59.0,322.0,63.0,17.0
18209,Total,Mujer,Sin Información,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,23.0
18210,Total,Mujer,Total,6253.0,272.0,130.0,873.0,1293.0,258.0,920.0,1606.0,160.0,6.0,4.0,238.0,60.0,328.0,64.0,41.0
18211,Total,Total,Indígena,155.0,8.0,4.0,26.0,51.0,6.0,21.0,27.0,3.0,0.0,0.0,3.0,2.0,3.0,0.0,1.0
18212,Total,Total,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18213,Total,Total,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18214,Total,Total,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",87.0,6.0,1.0,8.0,14.0,6.0,21.0,19.0,2.0,0.0,0.0,2.0,0.0,5.0,1.0,2.0
18215,Total,Total,Ningún grupo étnico,11514.0,562.0,248.0,1670.0,2548.0,440.0,1735.0,2796.0,294.0,6.0,13.0,355.0,115.0,574.0,120.0,38.0
18216,Total,Total,Sin Información,54.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,51.0
18217,Total,Total,Total,11812.0,576.0,253.0,1704.0,2614.0,452.0,1777.0,2844.0,299.0,6.0,13.0,360.0,117.0,584.0,121.0,92.0
18218,Cabecera,Hombre,Indígena,27.0,0.0,0.0,5.0,9.0,0.0,4.0,7.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18219,Cabecera,Hombre,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18220,Cabecera,Hombre,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18221,Cabecera,Hombre,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",39.0,1.0,1.0,4.0,7.0,3.0,7.0,8.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18222,Cabecera,Hombre,Ningún grupo étnico,4579.0,257.0,96.0,690.0,976.0,165.0,705.0,1099.0,115.0,0.0,9.0,117.0,56.0,228.0,47.0,19.0
18223,Cabecera,Hombre,Sin Información,27.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,25.0
18224,Cabecera,Hombre,Total,4674.0,258.0,97.0,699.0,993.0,168.0,716.0,1116.0,117.0,0.0,9.0,119.0,57.0,232.0,47.0,46.0
18225,Cabecera,Mujer,Indígena,39.0,2.0,0.0,8.0,6.0,2.0,6.0,8.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0
18226,Cabecera,Mujer,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",40.0,3.0,0.0,3.0,7.0,2.0,12.0,9.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18227,Cabecera,Mujer,Ningún grupo étnico,5373.0,246.0,113.0,742.0,1038.0,212.0,772.0,1447.0,137.0,5.0,3.0,227.0,54.0,304.0,56.0,17.0
18228,Cabecera,Mujer,Sin Información,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,21.0
18229,Cabecera,Mujer,Total,5474.0,251.0,113.0,753.0,1051.0,216.0,790.0,1464.0,138.0,5.0,3.0,229.0,55.0,310.0,57.0,39.0
18230,Cabecera,Total,Indígena,66.0,2.0,0.0,13.0,15.0,2.0,10.0,15.0,1.0,0.0,0.0,2.0,2.0,3.0,0.0,1.0
18231,Cabecera,Total,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18232,Cabecera,Total,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18233,Cabecera,Total,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",79.0,4.0,1.0,7.0,14.0,5.0,19.0,17.0,2.0,0.0,0.0,2.0,0.0,5.0,1.0,2.0
18234,Cabecera,Total,Ningún grupo étnico,9952.0,503.0,209.0,1432.0,2014.0,377.0,1477.0,2546.0,252.0,5.0,12.0,344.0,110.0,532.0,103.0,36.0
18235,Cabecera,Total,Sin Información,49.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,46.0
18236,Cabecera,Total,Total,10148.0,509.0,210.0,1452.0,2044.0,384.0,1506.0,2580.0,255.0,5.0,12.0,348.0,112.0,542.0,104.0,85.0
18237,Rural disperso,Hombre,Indígena,47.0,2.0,2.0,5.0,24.0,2.0,9.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18238,Rural disperso,Hombre,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",4.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18239,Rural disperso,Hombre,Ningún grupo étnico,831.0,43.0,24.0,127.0,304.0,23.0,131.0,118.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,2.0
18240,Rural disperso,Hombre,Sin Información,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
18241,Rural disperso,Hombre,Total,885.0,46.0,26.0,132.0,328.0,26.0,141.0,122.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,5.0
18242,Rural disperso,Mujer,Indígena,42.0,4.0,2.0,8.0,12.0,2.0,2.0,9.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18243,Rural disperso,Mujer,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",4.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18244,Rural disperso,Mujer,Ningún grupo étnico,731.0,16.0,15.0,111.0,230.0,40.0,127.0,132.0,20.0,1.0,1.0,8.0,5.0,18.0,7.0,0.0
18245,Rural disperso,Mujer,Sin Información,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
18246,Rural disperso,Mujer,Total,779.0,21.0,17.0,120.0,242.0,42.0,130.0,142.0,22.0,1.0,1.0,9.0,5.0,18.0,7.0,2.0
18247,Rural disperso,Total,Indígena,89.0,6.0,4.0,13.0,36.0,4.0,11.0,12.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18248,Rural disperso,Total,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",8.0,2.0,0.0,1.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18249,Rural disperso,Total,Ningún grupo étnico,1562.0,59.0,39.0,238.0,534.0,63.0,258.0,250.0,42.0,1.0,1.0,11.0,5.0,42.0,17.0,2.0
18250,Rural disperso,Total,Sin Información,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
18251,Rural disperso,Total,Total,1664.0,67.0,43.0,252.0,570.0,68.0,271.0,264.0,44.0,1.0,1.0,12.0,5.0,42.0,17.0,7.0

Se modifican los datos con tildes y ñ.

In [22]:
replacements = str.maketrans({'é': 'e', 'í': 'i', 'ó': 'o', 'ú': 'u'})
df_19pm.loc[:, 'pertenencia_etnica'] = df_19pm['pertenencia_etnica'].str.translate(replacements)
df_19pm

,area,sexo,pertenencia_etnica,total,ninguno,preescolar,primaria_completa,primaria_incompleta,secundaria_completa,secundaria_incompleta,media_completa,media_incompleta,normal_completa,normal_incompleta,tecnico,tecnologico,universitario,especializacion_doctorado,sin_informacion
18199,Total,Hombre,Indigena,74.0,2.0,2.0,10.0,33.0,2.0,13.0,10.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18200,Total,Hombre,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18201,Total,Hombre,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18202,Total,Hombre,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",43.0,2.0,1.0,4.0,7.0,4.0,8.0,9.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18203,Total,Hombre,Ningun grupo etnico,5410.0,300.0,120.0,817.0,1280.0,188.0,836.0,1217.0,137.0,0.0,9.0,120.0,56.0,252.0,57.0,21.0
18204,Total,Hombre,Sin Informacion,30.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,28.0
18205,Total,Hombre,Total,5559.0,304.0,123.0,831.0,1321.0,194.0,857.0,1238.0,139.0,0.0,9.0,122.0,57.0,256.0,57.0,51.0
18206,Total,Mujer,Indigena,81.0,6.0,2.0,16.0,18.0,4.0,8.0,17.0,3.0,0.0,0.0,2.0,1.0,3.0,0.0,1.0
18207,Total,Mujer,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",44.0,4.0,0.0,4.0,7.0,2.0,13.0,10.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18208,Total,Mujer,Ningun grupo etnico,6104.0,262.0,128.0,853.0,1268.0,252.0,899.0,1579.0,157.0,6.0,4.0,235.0,59.0,322.0,63.0,17.0
18209,Total,Mujer,Sin Informacion,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,23.0
18210,Total,Mujer,Total,6253.0,272.0,130.0,873.0,1293.0,258.0,920.0,1606.0,160.0,6.0,4.0,238.0,60.0,328.0,64.0,41.0
18211,Total,Total,Indigena,155.0,8.0,4.0,26.0,51.0,6.0,21.0,27.0,3.0,0.0,0.0,3.0,2.0,3.0,0.0,1.0
18212,Total,Total,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18213,Total,Total,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18214,Total,Total,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",87.0,6.0,1.0,8.0,14.0,6.0,21.0,19.0,2.0,0.0,0.0,2.0,0.0,5.0,1.0,2.0
18215,Total,Total,Ningun grupo etnico,11514.0,562.0,248.0,1670.0,2548.0,440.0,1735.0,2796.0,294.0,6.0,13.0,355.0,115.0,574.0,120.0,38.0
18216,Total,Total,Sin Informacion,54.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,51.0
18217,Total,Total,Total,11812.0,576.0,253.0,1704.0,2614.0,452.0,1777.0,2844.0,299.0,6.0,13.0,360.0,117.0,584.0,121.0,92.0
18218,Cabecera,Hombre,Indigena,27.0,0.0,0.0,5.0,9.0,0.0,4.0,7.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18219,Cabecera,Hombre,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18220,Cabecera,Hombre,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18221,Cabecera,Hombre,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",39.0,1.0,1.0,4.0,7.0,3.0,7.0,8.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18222,Cabecera,Hombre,Ningun grupo etnico,4579.0,257.0,96.0,690.0,976.0,165.0,705.0,1099.0,115.0,0.0,9.0,117.0,56.0,228.0,47.0,19.0
18223,Cabecera,Hombre,Sin Informacion,27.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,25.0
18224,Cabecera,Hombre,Total,4674.0,258.0,97.0,699.0,993.0,168.0,716.0,1116.0,117.0,0.0,9.0,119.0,57.0,232.0,47.0,46.0
18225,Cabecera,Mujer,Indigena,39.0,2.0,0.0,8.0,6.0,2.0,6.0,8.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0
18226,Cabecera,Mujer,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",40.0,3.0,0.0,3.0,7.0,2.0,12.0,9.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18227,Cabecera,Mujer,Ningun grupo etnico,5373.0,246.0,113.0,742.0,1038.0,212.0,772.0,1447.0,137.0,5.0,3.0,227.0,54.0,304.0,56.0,17.0
18228,Cabecera,Mujer,Sin Informacion,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,21.0
18229,Cabecera,Mujer,Total,5474.0,251.0,113.0,753.0,1051.0,216.0,790.0,1464.0,138.0,5.0,3.0,229.0,55.0,310.0,57.0,39.0
18230,Cabecera,Total,Indigena,66.0,2.0,0.0,13.0,15.0,2.0,10.0,15.0,1.0,0.0,0.0,2.0,2.0,3.0,0.0,1.0
18231,Cabecera,Total,Gitano(a) o Rrom,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18232,Cabecera,Total,Palenquero(a) de San Basilio,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18233,Cabecera,Total,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",79.0,4.0,1.0,7.0,14.0,5.0,19.0,17.0,2.0,0.0,0.0,2.0,0.0,5.0,1.0,2.0
18234,Cabecera,Total,Ningun grupo etnico,9952.0,503.0,209.0,1432.0,2014.0,377.0,1477.0,2546.0,252.0,5.0,12.0,344.0,110.0,532.0,103.0,36.0
18235,Cabecera,Total,Sin Informacion,49.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,46.0
18236,Cabecera,Total,Total,10148.0,509.0,210.0,1452.0,2044.0,384.0,1506.0,2580.0,255.0,5.0,12.0,348.0,112.0,542.0,104.0,85.0
18237,Rural disperso,Hombre,Indigena,47.0,2.0,2.0,5.0,24.0,2.0,9.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18238,Rural disperso,Hombre,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",4.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18239,Rural disperso,Hombre,Ningun grupo etnico,831.0,43.0,24.0,127.0,304.0,23.0,131.0,118.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,2.0
18240,Rural disperso,Hombre,Sin Informacion,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
18241,Rural disperso,Hombre,Total,885.0,46.0,26.0,132.0,328.0,26.0,141.0,122.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,5.0
18242,Rural disperso,Mujer,Indigena,42.0,4.0,2.0,8.0,12.0,2.0,2.0,9.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18243,Rural disperso,Mujer,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",4.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18244,Rural disperso,Mujer,Ningun grupo etnico,731.0,16.0,15.0,111.0,230.0,40.0,127.0,132.0,20.0,1.0,1.0,8.0,5.0,18.0,7.0,0.0
18245,Rural disperso,Mujer,Sin Informacion,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
18246,Rural disperso,Mujer,Total,779.0,21.0,17.0,120.0,242.0,42.0,130.0,142.0,22.0,1.0,1.0,9.0,5.0,18.0,7.0,2.0
18247,Rural disperso,Total,Indigena,89.0,6.0,4.0,13.0,36.0,4.0,11.0,12.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18248,Rural disperso,Total,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",8.0,2.0,0.0,1.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18249,Rural disperso,Total,Ningun grupo etnico,1562.0,59.0,39.0,238.0,534.0,63.0,258.0,250.0,42.0,1.0,1.0,11.0,5.0,42.0,17.0,2.0
18250,Rural disperso,Total,Sin Informacion,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
18251,Rural disperso,Total,Total,1664.0,67.0,43.0,252.0,570.0,68.0,271.0,264.0,44.0,1.0,1.0,12.0,5.0,42.0,17.0,7.0

Se creará una copia del dataframe y se removerán las filas y columnas con resumenes de datos para el csv que no contiene resúmenes.

In [23]:
df_19pm_cleaned = df_19pm.copy()
df_19pm_cleaned.drop(['total'], axis=1, inplace=True)
df_19pm_cleaned

,area,sexo,pertenencia_etnica,ninguno,preescolar,primaria_completa,primaria_incompleta,secundaria_completa,secundaria_incompleta,media_completa,media_incompleta,normal_completa,normal_incompleta,tecnico,tecnologico,universitario,especializacion_doctorado,sin_informacion
18199,Total,Hombre,Indigena,2.0,2.0,10.0,33.0,2.0,13.0,10.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18200,Total,Hombre,Gitano(a) o Rrom,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18201,Total,Hombre,Palenquero(a) de San Basilio,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18202,Total,Hombre,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",2.0,1.0,4.0,7.0,4.0,8.0,9.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18203,Total,Hombre,Ningun grupo etnico,300.0,120.0,817.0,1280.0,188.0,836.0,1217.0,137.0,0.0,9.0,120.0,56.0,252.0,57.0,21.0
18204,Total,Hombre,Sin Informacion,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,28.0
18205,Total,Hombre,Total,304.0,123.0,831.0,1321.0,194.0,857.0,1238.0,139.0,0.0,9.0,122.0,57.0,256.0,57.0,51.0
18206,Total,Mujer,Indigena,6.0,2.0,16.0,18.0,4.0,8.0,17.0,3.0,0.0,0.0,2.0,1.0,3.0,0.0,1.0
18207,Total,Mujer,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",4.0,0.0,4.0,7.0,2.0,13.0,10.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18208,Total,Mujer,Ningun grupo etnico,262.0,128.0,853.0,1268.0,252.0,899.0,1579.0,157.0,6.0,4.0,235.0,59.0,322.0,63.0,17.0
18209,Total,Mujer,Sin Informacion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,23.0
18210,Total,Mujer,Total,272.0,130.0,873.0,1293.0,258.0,920.0,1606.0,160.0,6.0,4.0,238.0,60.0,328.0,64.0,41.0
18211,Total,Total,Indigena,8.0,4.0,26.0,51.0,6.0,21.0,27.0,3.0,0.0,0.0,3.0,2.0,3.0,0.0,1.0
18212,Total,Total,Gitano(a) o Rrom,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18213,Total,Total,Palenquero(a) de San Basilio,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18214,Total,Total,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",6.0,1.0,8.0,14.0,6.0,21.0,19.0,2.0,0.0,0.0,2.0,0.0,5.0,1.0,2.0
18215,Total,Total,Ningun grupo etnico,562.0,248.0,1670.0,2548.0,440.0,1735.0,2796.0,294.0,6.0,13.0,355.0,115.0,574.0,120.0,38.0
18216,Total,Total,Sin Informacion,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,51.0
18217,Total,Total,Total,576.0,253.0,1704.0,2614.0,452.0,1777.0,2844.0,299.0,6.0,13.0,360.0,117.0,584.0,121.0,92.0
18218,Cabecera,Hombre,Indigena,0.0,0.0,5.0,9.0,0.0,4.0,7.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18219,Cabecera,Hombre,Gitano(a) o Rrom,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18220,Cabecera,Hombre,Palenquero(a) de San Basilio,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18221,Cabecera,Hombre,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",1.0,1.0,4.0,7.0,3.0,7.0,8.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18222,Cabecera,Hombre,Ningun grupo etnico,257.0,96.0,690.0,976.0,165.0,705.0,1099.0,115.0,0.0,9.0,117.0,56.0,228.0,47.0,19.0
18223,Cabecera,Hombre,Sin Informacion,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,25.0
18224,Cabecera,Hombre,Total,258.0,97.0,699.0,993.0,168.0,716.0,1116.0,117.0,0.0,9.0,119.0,57.0,232.0,47.0,46.0
18225,Cabecera,Mujer,Indigena,2.0,0.0,8.0,6.0,2.0,6.0,8.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0
18226,Cabecera,Mujer,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",3.0,0.0,3.0,7.0,2.0,12.0,9.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18227,Cabecera,Mujer,Ningun grupo etnico,246.0,113.0,742.0,1038.0,212.0,772.0,1447.0,137.0,5.0,3.0,227.0,54.0,304.0,56.0,17.0
18228,Cabecera,Mujer,Sin Informacion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,21.0
18229,Cabecera,Mujer,Total,251.0,113.0,753.0,1051.0,216.0,790.0,1464.0,138.0,5.0,3.0,229.0,55.0,310.0,57.0,39.0
18230,Cabecera,Total,Indigena,2.0,0.0,13.0,15.0,2.0,10.0,15.0,1.0,0.0,0.0,2.0,2.0,3.0,0.0,1.0
18231,Cabecera,Total,Gitano(a) o Rrom,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18232,Cabecera,Total,Palenquero(a) de San Basilio,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18233,Cabecera,Total,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",4.0,1.0,7.0,14.0,5.0,19.0,17.0,2.0,0.0,0.0,2.0,0.0,5.0,1.0,2.0
18234,Cabecera,Total,Ningun grupo etnico,503.0,209.0,1432.0,2014.0,377.0,1477.0,2546.0,252.0,5.0,12.0,344.0,110.0,532.0,103.0,36.0
18235,Cabecera,Total,Sin Informacion,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,46.0
18236,Cabecera,Total,Total,509.0,210.0,1452.0,2044.0,384.0,1506.0,2580.0,255.0,5.0,12.0,348.0,112.0,542.0,104.0,85.0
18237,Rural disperso,Hombre,Indigena,2.0,2.0,5.0,24.0,2.0,9.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18238,Rural disperso,Hombre,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18239,Rural disperso,Hombre,Ningun grupo etnico,43.0,24.0,127.0,304.0,23.0,131.0,118.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,2.0
18240,Rural disperso,Hombre,Sin Informacion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
18241,Rural disperso,Hombre,Total,46.0,26.0,132.0,328.0,26.0,141.0,122.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,5.0
18242,Rural disperso,Mujer,Indigena,4.0,2.0,8.0,12.0,2.0,2.0,9.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18243,Rural disperso,Mujer,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18244,Rural disperso,Mujer,Ningun grupo etnico,16.0,15.0,111.0,230.0,40.0,127.0,132.0,20.0,1.0,1.0,8.0,5.0,18.0,7.0,0.0
18245,Rural disperso,Mujer,Sin Informacion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
18246,Rural disperso,Mujer,Total,21.0,17.0,120.0,242.0,42.0,130.0,142.0,22.0,1.0,1.0,9.0,5.0,18.0,7.0,2.0
18247,Rural disperso,Total,Indigena,6.0,4.0,13.0,36.0,4.0,11.0,12.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18248,Rural disperso,Total,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",2.0,0.0,1.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18249,Rural disperso,Total,Ningun grupo etnico,59.0,39.0,238.0,534.0,63.0,258.0,250.0,42.0,1.0,1.0,11.0,5.0,42.0,17.0,2.0
18250,Rural disperso,Total,Sin Informacion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
18251,Rural disperso,Total,Total,67.0,43.0,252.0,570.0,68.0,271.0,264.0,44.0,1.0,1.0,12.0,5.0,42.0,17.0,7.0

In [24]:
df_19pm_cleaned = df_19pm_cleaned.loc[(df_19pm_cleaned['area'] != 'Total') & (df_19pm_cleaned['sexo'] != 'Total') & (df_19pm_cleaned['pertenencia_etnica'] != 'Total')]
df_19pm_cleaned

,area,sexo,pertenencia_etnica,ninguno,preescolar,primaria_completa,primaria_incompleta,secundaria_completa,secundaria_incompleta,media_completa,media_incompleta,normal_completa,normal_incompleta,tecnico,tecnologico,universitario,especializacion_doctorado,sin_informacion
18218,Cabecera,Hombre,Indigena,0.0,0.0,5.0,9.0,0.0,4.0,7.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
18219,Cabecera,Hombre,Gitano(a) o Rrom,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18220,Cabecera,Hombre,Palenquero(a) de San Basilio,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18221,Cabecera,Hombre,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",1.0,1.0,4.0,7.0,3.0,7.0,8.0,2.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0
18222,Cabecera,Hombre,Ningun grupo etnico,257.0,96.0,690.0,976.0,165.0,705.0,1099.0,115.0,0.0,9.0,117.0,56.0,228.0,47.0,19.0
18223,Cabecera,Hombre,Sin Informacion,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,25.0
18225,Cabecera,Mujer,Indigena,2.0,0.0,8.0,6.0,2.0,6.0,8.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0
18226,Cabecera,Mujer,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",3.0,0.0,3.0,7.0,2.0,12.0,9.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0
18227,Cabecera,Mujer,Ningun grupo etnico,246.0,113.0,742.0,1038.0,212.0,772.0,1447.0,137.0,5.0,3.0,227.0,54.0,304.0,56.0,17.0
18228,Cabecera,Mujer,Sin Informacion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,21.0
18237,Rural disperso,Hombre,Indigena,2.0,2.0,5.0,24.0,2.0,9.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18238,Rural disperso,Hombre,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18239,Rural disperso,Hombre,Ningun grupo etnico,43.0,24.0,127.0,304.0,23.0,131.0,118.0,22.0,0.0,0.0,3.0,0.0,24.0,10.0,2.0
18240,Rural disperso,Hombre,Sin Informacion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
18242,Rural disperso,Mujer,Indigena,4.0,2.0,8.0,12.0,2.0,2.0,9.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18243,Rural disperso,Mujer,"Negro(a), Mulato(a), Afrodescendiente, Afrocol...",1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18244,Rural disperso,Mujer,Ningun grupo etnico,16.0,15.0,111.0,230.0,40.0,127.0,132.0,20.0,1.0,1.0,8.0,5.0,18.0,7.0,0.0
18245,Rural disperso,Mujer,Sin Informacion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0

Los dataframes están listos para ser exportados a CSV.

In [25]:
df_19pm.to_csv(csv_total_path, index=False)
df_19pm_cleaned.to_csv(csv_path, index=False)