In [13]:
# imports
import pandas as pd

In [14]:
# Ruta relativa del xslx que contiene los datos
original_data_path = 'Data\\Original\\PERSONAS_DEMOGRAFICO_Cuadros_CNPV_2018.xlsx'

# Nombre del csv objetivo
csv_total_filename = 'caldas_viterbo_total_18PM.csv'
csv_filename = 'caldas_viterbo_18PM.csv'

# Ruta relativa del csv objetivo
csv_total_path = 'Data\\Datasets\\' + csv_total_filename
csv_path = 'Data\\Datasets\\' + csv_filename

In [15]:
# Lee archivo xlsx
df_18pm = pd.read_excel(original_data_path, sheet_name='18PM', skiprows=9)
df_18pm.head()

,"Departamento y áreas (Total, Cabecera y Centros poblados y Rural disperso), sexo y grupo edades",Unnamed: 1,Unnamed: 2,Unnamed: 3,Asistencia a alguna institución educativa,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,NaN,NaN,NaN,Total,NaN,NaN,NaN,Si,NaN,NaN,NaN,No,NaN,NaN,NaN,Sin información,NaN,NaN
1,NaN,NaN,NaN,NaN,Total,Hombre,Mujer,NaN,Total,Hombre,Mujer,NaN,Total,Hombre,Mujer,NaN,Total,Hombre,Mujer
2,Total Nacional,NaN,Total,De 5 años y más,40802017,19763734,21038283,NaN,11398412,5632536,5765876,NaN,28867110,13864111,15002999,NaN,536495,267087,269408
3,NaN,NaN,NaN,Entre 5 y 6 años,1300787,664458,636329,NaN,1107866,564309,543557,NaN,126355,66123,60232,NaN,66566,34026,32540
4,NaN,NaN,NaN,Entre 5 y 17 años,9129229,4663464,4465765,NaN,8012058,4068189,3943869,NaN,982382,526596,455786,NaN,134789,68679,66110

In [16]:
first_row = list(df_18pm.iloc[0])[:]
for (i, value) in enumerate(first_row):
    print(i, value)

0 nan
1 nan
2 nan
3 nan
4 Total
5 nan
6 nan
7 nan
8 Si
9 nan
10 nan
11 nan
12 No
13 nan
14 nan
15 nan
16 Sin información
17 nan
18 nan

In [17]:
second_row = list(df_18pm.iloc[1])[:]
for (i, value) in enumerate(second_row):
    print(i, value)

0 nan
1 nan
2 nan
3 nan
4 Total
5 Hombre
6 Mujer
7 nan
8 Total
9 Hombre
10 Mujer
11 nan
12 Total
13 Hombre
14 Mujer
15 nan
16 Total
17 Hombre
18 Mujer

Se observan columnas y subcolumnas, se dividirán en diferentes datasets, se asignará una nueva columna "Asistencia a alguna institucion educativa" y se asignaran los valores correspondientes desagrupando el dataframe en este item, y se unirán los diferentes dataframes.

In [18]:
actual_headers = list(df_18pm.iloc[1][4:])
cleaned_headers = [x.lower() for x in actual_headers if not pd.isnull(x)]
cleaned_headers

['total',
 'hombre',
 'mujer',
 'total',
 'hombre',
 'mujer',
 'total',
 'hombre',
 'mujer',
 'total',
 'hombre',
 'mujer']

Se filtrarán los datos que no corresponden al municipio de Viterbo Caldas, para ello se propagará el municipio, el cual se encuentra en la columna "Unnamed: 1" y se seleccionarán solo los registros que contengan el identificador de Viterbo dentro del dataframe, para este caso es "17877_Viterbo".

In [19]:
df_18pm['Unnamed: 1'] = df_18pm['Unnamed: 1'].ffill()
df_18pm = df_18pm.loc[df_18pm['Unnamed: 1'] == '17877_Viterbo']
df_18pm

,"Departamento y áreas (Total, Cabecera y Centros poblados y Rural disperso), sexo y grupo edades",Unnamed: 1,Unnamed: 2,Unnamed: 3,Asistencia a alguna institución educativa,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
8948,NaN,17877_Viterbo,Total,De 5 años y más,11809,5559,6250,NaN,2659,1251,1408,NaN,9088,4275,4813,NaN,62,33,29
8949,NaN,17877_Viterbo,NaN,Entre 5 y 6 años,266,128,138,NaN,250,118,132,NaN,10,5,5,NaN,6,5,1
8950,NaN,17877_Viterbo,NaN,Entre 5 y 17 años,2336,1171,1165,NaN,2123,1042,1081,NaN,202,121,81,NaN,11,8,3
8951,NaN,17877_Viterbo,NaN,Entre 7 y 11 años,828,429,399,NaN,809,419,390,NaN,18,10,8,NaN,1,0,1
8952,NaN,17877_Viterbo,NaN,Entre 12 y 17 años,1242,614,628,NaN,1064,505,559,NaN,174,106,68,NaN,4,3,1
8953,NaN,17877_Viterbo,NaN,Entre 18 y 24 años,1375,644,731,NaN,335,127,208,NaN,1027,510,517,NaN,13,7,6
8954,NaN,17877_Viterbo,NaN,De 25 años y más,8098,3744,4354,NaN,201,82,119,NaN,7859,3644,4215,NaN,38,18,20
8955,NaN,17877_Viterbo,Cabecera,De 5 años y más,10145,4674,5471,NaN,2249,1038,1211,NaN,7840,3607,4233,NaN,56,29,27
8956,NaN,17877_Viterbo,NaN,Entre 5 y 6 años,224,101,123,NaN,212,94,118,NaN,7,3,4,NaN,5,4,1
8957,NaN,17877_Viterbo,NaN,Entre 5 y 17 años,1940,952,988,NaN,1783,857,926,NaN,147,88,59,NaN,10,7,3
8958,NaN,17877_Viterbo,NaN,Entre 7 y 11 años,685,354,331,NaN,672,348,324,NaN,12,6,6,NaN,1,0,1
8959,NaN,17877_Viterbo,NaN,Entre 12 y 17 años,1031,497,534,NaN,899,415,484,NaN,128,79,49,NaN,4,3,1
8960,NaN,17877_Viterbo,NaN,Entre 18 y 24 años,1177,548,629,NaN,286,110,176,NaN,878,431,447,NaN,13,7,6
8961,NaN,17877_Viterbo,NaN,De 25 años y más,7028,3174,3854,NaN,180,71,109,NaN,6815,3088,3727,NaN,33,15,18
8962,NaN,17877_Viterbo,Rural disperso,De 5 años y más,1664,885,779,NaN,410,213,197,NaN,1248,668,580,NaN,6,4,2
8963,NaN,17877_Viterbo,NaN,Entre 5 y 6 años,42,27,15,NaN,38,24,14,NaN,3,2,1,NaN,1,1,0
8964,NaN,17877_Viterbo,NaN,Entre 5 y 17 años,396,219,177,NaN,340,185,155,NaN,55,33,22,NaN,1,1,0
8965,NaN,17877_Viterbo,NaN,Entre 7 y 11 años,143,75,68,NaN,137,71,66,NaN,6,4,2,NaN,0,0,0
8966,NaN,17877_Viterbo,NaN,Entre 12 y 17 años,211,117,94,NaN,165,90,75,NaN,46,27,19,NaN,0,0,0
8967,NaN,17877_Viterbo,NaN,Entre 18 y 24 años,198,96,102,NaN,49,17,32,NaN,149,79,70,NaN,0,0,0
8968,NaN,17877_Viterbo,NaN,De 25 años y más,1070,570,500,NaN,21,11,10,NaN,1044,556,488,NaN,5,3,2

Debido a la agrupación de columnas por asistencia a alguna institución educativa, se separan los datos por subconjuntos dependiendo si los censados asisten a alguna institución educativa y al final serán reunidos en un mismo dataframe con el valor presente en las filas.

In [20]:
ls_df = []
academic_institution_atendee = ['Total', 'Si', 'No', 'Sin informacion']
for i, atendee in zip(range(4, 19, 4), academic_institution_atendee):
    df_18pm_with_academic_atendance = pd.concat([df_18pm[['Unnamed: 2', 'Unnamed: 3']], df_18pm.iloc[:, i:i+3].assign(asiste_a_alguna_institucion_educativa=atendee)], axis=1)
    ls_df.append(df_18pm_with_academic_atendance)

for df in ls_df:
    df.rename(columns=dict(zip(list(df.columns.values[2:-1]), cleaned_headers[:])), inplace=True)

df_18pm = pd.concat(ls_df)
df_18pm.rename(columns={'Unnamed: 2': 'area', 'Unnamed: 3': 'grupo_de_edad'}, inplace=True)
df_18pm

,area,grupo_de_edad,total,hombre,mujer,asiste_a_alguna_institucion_educativa
8948,Total,De 5 años y más,11809,5559,6250,Total
8949,NaN,Entre 5 y 6 años,266,128,138,Total
8950,NaN,Entre 5 y 17 años,2336,1171,1165,Total
8951,NaN,Entre 7 y 11 años,828,429,399,Total
8952,NaN,Entre 12 y 17 años,1242,614,628,Total
...,...,...,...,...,...,...
8964,NaN,Entre 5 y 17 años,1,1,0,Sin informacion
8965,NaN,Entre 7 y 11 años,0,0,0,Sin informacion
8966,NaN,Entre 12 y 17 años,0,0,0,Sin informacion
8967,NaN,Entre 18 y 24 años,0,0,0,Sin informacion
8968,NaN,De 25 años y más,5,3,2,Sin informacion

Se propaga el valor de la columna 'Area' para completar los datos faltantes.

In [21]:
df_18pm['area'] = df_18pm['area'].ffill()
df_18pm

,area,grupo_de_edad,total,hombre,mujer,asiste_a_alguna_institucion_educativa
8948,Total,De 5 años y más,11809,5559,6250,Total
8949,Total,Entre 5 y 6 años,266,128,138,Total
8950,Total,Entre 5 y 17 años,2336,1171,1165,Total
8951,Total,Entre 7 y 11 años,828,429,399,Total
8952,Total,Entre 12 y 17 años,1242,614,628,Total
...,...,...,...,...,...,...
8964,Rural disperso,Entre 5 y 17 años,1,1,0,Sin informacion
8965,Rural disperso,Entre 7 y 11 años,0,0,0,Sin informacion
8966,Rural disperso,Entre 12 y 17 años,0,0,0,Sin informacion
8967,Rural disperso,Entre 18 y 24 años,0,0,0,Sin informacion
8968,Rural disperso,De 25 años y más,5,3,2,Sin informacion

Se reemplazan los datos que contienen tildes y ñ.

In [22]:
replacements = str.maketrans({'ñ': 'ni', 'á': 'a'})
df_18pm.loc[:, 'grupo_de_edad'] = df_18pm['grupo_de_edad'].str.translate(replacements)
df_18pm

,area,grupo_de_edad,total,hombre,mujer,asiste_a_alguna_institucion_educativa
8948,Total,De 5 anios y mas,11809,5559,6250,Total
8949,Total,Entre 5 y 6 anios,266,128,138,Total
8950,Total,Entre 5 y 17 anios,2336,1171,1165,Total
8951,Total,Entre 7 y 11 anios,828,429,399,Total
8952,Total,Entre 12 y 17 anios,1242,614,628,Total
...,...,...,...,...,...,...
8964,Rural disperso,Entre 5 y 17 anios,1,1,0,Sin informacion
8965,Rural disperso,Entre 7 y 11 anios,0,0,0,Sin informacion
8966,Rural disperso,Entre 12 y 17 anios,0,0,0,Sin informacion
8967,Rural disperso,Entre 18 y 24 anios,0,0,0,Sin informacion
8968,Rural disperso,De 25 anios y mas,5,3,2,Sin informacion

Se creará una copia del dataframe y se removerán las filas y columnas con resumenes de datos para el csv que no contiene resúmenes.

In [23]:
df_18pm_cleaned = df_18pm.copy()
df_18pm_cleaned.drop(['total'], axis=1, inplace=True)
df_18pm_cleaned

,area,grupo_de_edad,hombre,mujer,asiste_a_alguna_institucion_educativa
8948,Total,De 5 anios y mas,5559,6250,Total
8949,Total,Entre 5 y 6 anios,128,138,Total
8950,Total,Entre 5 y 17 anios,1171,1165,Total
8951,Total,Entre 7 y 11 anios,429,399,Total
8952,Total,Entre 12 y 17 anios,614,628,Total
...,...,...,...,...,...
8964,Rural disperso,Entre 5 y 17 anios,1,0,Sin informacion
8965,Rural disperso,Entre 7 y 11 anios,0,0,Sin informacion
8966,Rural disperso,Entre 12 y 17 anios,0,0,Sin informacion
8967,Rural disperso,Entre 18 y 24 anios,0,0,Sin informacion
8968,Rural disperso,De 25 anios y mas,3,2,Sin informacion

In [24]:
df_18pm_cleaned = df_18pm_cleaned.loc[(df_18pm_cleaned['area'] != 'Total') & (df_18pm_cleaned['asiste_a_alguna_institucion_educativa'] != 'Total')]
df_18pm_cleaned

,area,grupo_de_edad,hombre,mujer,asiste_a_alguna_institucion_educativa
8955,Cabecera,De 5 anios y mas,1038,1211,Si
8956,Cabecera,Entre 5 y 6 anios,94,118,Si
8957,Cabecera,Entre 5 y 17 anios,857,926,Si
8958,Cabecera,Entre 7 y 11 anios,348,324,Si
8959,Cabecera,Entre 12 y 17 anios,415,484,Si
8960,Cabecera,Entre 18 y 24 anios,110,176,Si
8961,Cabecera,De 25 anios y mas,71,109,Si
8962,Rural disperso,De 5 anios y mas,213,197,Si
8963,Rural disperso,Entre 5 y 6 anios,24,14,Si
8964,Rural disperso,Entre 5 y 17 anios,185,155,Si
8965,Rural disperso,Entre 7 y 11 anios,71,66,Si
8966,Rural disperso,Entre 12 y 17 anios,90,75,Si
8967,Rural disperso,Entre 18 y 24 anios,17,32,Si
8968,Rural disperso,De 25 anios y mas,11,10,Si
8955,Cabecera,De 5 anios y mas,3607,4233,No
8956,Cabecera,Entre 5 y 6 anios,3,4,No
8957,Cabecera,Entre 5 y 17 anios,88,59,No
8958,Cabecera,Entre 7 y 11 anios,6,6,No
8959,Cabecera,Entre 12 y 17 anios,79,49,No
8960,Cabecera,Entre 18 y 24 anios,431,447,No
8961,Cabecera,De 25 anios y mas,3088,3727,No
8962,Rural disperso,De 5 anios y mas,668,580,No
8963,Rural disperso,Entre 5 y 6 anios,2,1,No
8964,Rural disperso,Entre 5 y 17 anios,33,22,No
8965,Rural disperso,Entre 7 y 11 anios,4,2,No
8966,Rural disperso,Entre 12 y 17 anios,27,19,No
8967,Rural disperso,Entre 18 y 24 anios,79,70,No
8968,Rural disperso,De 25 anios y mas,556,488,No
8955,Cabecera,De 5 anios y mas,29,27,Sin informacion
8956,Cabecera,Entre 5 y 6 anios,4,1,Sin informacion
8957,Cabecera,Entre 5 y 17 anios,7,3,Sin informacion
8958,Cabecera,Entre 7 y 11 anios,0,1,Sin informacion
8959,Cabecera,Entre 12 y 17 anios,3,1,Sin informacion
8960,Cabecera,Entre 18 y 24 anios,7,6,Sin informacion
8961,Cabecera,De 25 anios y mas,15,18,Sin informacion
8962,Rural disperso,De 5 anios y mas,4,2,Sin informacion
8963,Rural disperso,Entre 5 y 6 anios,1,0,Sin informacion
8964,Rural disperso,Entre 5 y 17 anios,1,0,Sin informacion
8965,Rural disperso,Entre 7 y 11 anios,0,0,Sin informacion
8966,Rural disperso,Entre 12 y 17 anios,0,0,Sin informacion
8967,Rural disperso,Entre 18 y 24 anios,0,0,Sin informacion
8968,Rural disperso,De 25 anios y mas,3,2,Sin informacion

Los dataframes están listos para ser exportados a CSV.

In [25]:
df_18pm.to_csv(csv_total_path, index=False)
df_18pm_cleaned.to_csv(csv_path, index=False)